### ISSUE TITLE
Defold 1.3.5 does not stop on breakpoints in the debugger

### ISSUE THREAD

**Issue by greay** [defold/defold#6894] opened 2022-08-18 20:50 UTC
**Describe the bug (REQUIRED)**
Latest version of the Defold editor no longer stops on breakpoints in the debugger.
 
**To Reproduce (REQUIRED)**
1. Set a breakpoint in the code
2. Click on Debug -> Start/Attach
3. Do whatever to try & trigger the breakpoint
4. Notice it does not stop

**Expected behavior (REQUIRED)**
It should hit the breakpoint & pause execution

**Defold version (REQUIRED):**
  - Version 1.3.5

**Platforms (REQUIRED):**
 - OS: macOS 12.5

**Comment by britzl** [comment] 2022-08-18 21:26
Duplicate of https://github.com/defold/defold/issues/6885

**Closed by britzl** 2022-08-18 21:26 UTC
Labels: bug
