### ISSUE TITLE
engine problem

### ISSUE THREAD

**Issue by OURABIG** [defold/defold#7043] opened 2022-10-07 21:43 UTC
**Describe the bug (REQUIRED)**
when updated to the new defold version the engine seems to have some problem like slow building and sometimes it just block for 10 seconds and then work

**To Reproduce (REQUIRED)**
please tell me if the problem is in my PC or in the engine

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  1.3.6

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]

**Comment by britzl** [comment] 2022-10-08 06:02
> please tell me if the problem is in my PC or in the engine

It is hard to tell. This happens when you do Project->Build? Does it also happen when you do this multiple times without changing anything in the project?

**Comment by Outseet** [comment] 2022-10-08 06:08
> > please tell me if the problem is in my PC or in the engine
> 
> It is hard to tell. This happens when you do Project->Build? Does it also happen when you do this multiple times without changing anything in the project?

Yes when I built multiple time the engine just freeze for 10 second or when I click Ctrl s

**Comment by britzl** [comment] 2022-10-08 06:09
> Yes when I built multiple time the engine just freeze for 10 second or when I click Ctrl s

This could indicate an issue with anti-virus doing some scanning of the launched engine or the changed files. Could you please try and whitelist Defold.exe (the editor) and dmengine.exe (the engine)?

**Comment by Outseet** [comment] 2022-10-08 14:34
> > Yes when I built multiple time the engine just freeze for 10 second or when I click Ctrl s
> 
> This could indicate an issue with anti-virus doing some scanning of the launched engine or the changed files. Could you please try and whitelist Defold.exe (the editor) and dmengine.exe (the engine)?

i don't have an anti virus there's only windows anti virus

**Comment by britzl** [comment] 2022-10-09 07:47
Does this issue happen with all projects, even an empty one?

**Comment by Outseet** [comment] 2022-10-09 10:19
> Does this issue happen with all projects, even an empty one?

Yes

**Comment by britzl** [comment] 2022-10-10 06:41
Hmm, and it is both when saving the project and when building and running? Those are two very different operations and I might be able to explain them separately.

> i don't have an anti virus there's only windows defender

Windows Defender is an anti-virus software isn't it?

> slow building and sometimes it just block for 10 seconds and then work

You select Project->Build and then nothing happens in the editor console panel and no window opens? It just hangs for 10s and then everything happens? Or do you get some indication that the build has started?

**Comment by britzl** [comment] 2022-12-02 19:28
Unable to reproduce and no solid information to go by to pinpoint the problem. Closing.

**Closed by britzl** 2022-12-02 19:28 UTC
Labels: bug, more info, windows
