### ISSUE TITLE
Toggle comment shortcut is not working

### ISSUE THREAD

**Issue by lzralbu** [defold/defold#7605] opened 2023-04-25 18:37 UTC
### Expected behaviour

Ctrl+/ should toggle comment.

### Actual behaviour

It doesn't.

### Steps to reproduce

Open a script file inside the editor and try to Ctrl+/. 

<hr/>

<table>
<tr><td>Build time</td><td>2023-04-24T12:04:18.309625</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>754a711814bb48e5b9a96ae113158894344f93ac</td></tr>
<tr><td>Defold engine sha</td><td>3dbbf1dbebd3a8146f6a917d101882a61f56afdc</td></tr>
<tr><td>Defold version</td><td>1.4.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"16a0726ecd534686b36dbf4036c9ab6b"'>16a0726ecd534686b36dbf4036c9ab6b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon 6600M and 6700M Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151.1008</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by lzralbu** [comment] 2023-04-25 18:42
Changing the keyboard layout from "Portugues (Brazil ABNT 2)" to "US Keyboard" makes the key combination "Ctrl + ;" toggle comments.

**Comment by britzl** [comment] 2023-04-26 07:58
Duplicate of https://github.com/defold/defold/issues/5047

**Closed by britzl** 2023-04-26 07:58 UTC
