### ISSUE TITLE
Add information about version of engine that was used to open/build project last time

### ISSUE THREAD

**Issue by vbif1** [defold/defold#8802] opened 2024-04-16 08:46 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
Currently if i have an old project and open it in a new version of engine it may fail due to breaking chages. And at this point I need to figure out what version I used back then when project were written. Which sometimes is impossible.

**Describe the solution you'd like (REQUIRED):**
I think having information about last version you used to work with a project would help with migration to a new version. Maybe we can have it in game.project or some other file that can be putted to version system.

**Comment by AGulev** [comment] 2024-04-16 08:49
duplicate of https://github.com/defold/defold/issues/4843

**Closed** 2024-04-22 07:02 UTC
Labels: feature request
