### ISSUE TITLE
Improve debugger performance on big projects

### ISSUE THREAD

**Issue by vlaaad** [defold/defold#6683] opened 2022-06-09 08:19 UTC
**Task (REQUIRED):**
The debugger is too slow in big projects. We should see if there is anything that can be improved there.

**Expected outcome (REQUIRED):**
The debugger is useful in big projects.

**Comment by britzl** [comment] 2022-09-01 13:32
Duplicate of #3380

**Closed by britzl** 2022-09-01 13:32 UTC
Labels: task, editor
