### ISSUE TITLE
Side Scroller Tutorial : Error when opening factory.go file

### ISSUE THREAD

**Issue by lizzaraga** [defold/defold#6496] opened 2022-03-26 20:38 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-19T07:58:42.238373</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3a65f70359804b08b36f6cc05ed72571"'>3a65f70359804b08b36f6cc05ed72571</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.2.2</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.11-76051511-generic</td></tr>
<table>

**Comment by britzl** [comment] 2022-03-27 08:18
We're working on a Linux launch script to better handle this.

Please try this workaround: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-03-27 14:55
Duplicate of https://github.com/defold/defold/issues/4851

**Closed by britzl** 2022-03-27 14:55 UTC
Labels: editor, linux
