### ISSUE TITLE
Resizing the window results in a torrent of resized messages when letting go of the mouse (DEF-2776)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3468] opened 2019-05-23 10:37 UTC
*Description:*
Reszing the window does nothing except display black when resizing. until you let go of the mouse, but then you don't just get a window_resized message for that particular size, but also for all the sizes it had during the resize drag process.

*Expected result:*
Only one window_resized message is sent.

*Actual result:*
Gazillion resize messages are sent at the same time when releasing the mouse.

**Comment by AGulev** [comment] 2024-03-08 20:05
close as duplicate of https://github.com/defold/defold/issues/3738

**Closed by AGulev** 2024-03-08 20:05 UTC
Labels: bug, engine
