### ISSUE TITLE
SocketException: Connection reset

### ISSUE THREAD

**Issue by lessnoon** [defold/defold#5935] opened 2021-07-14 10:20 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8023d1a6e43f43679e85eacdd7d707ec"'>8023d1a6e43f43679e85eacdd7d707ec</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2021-07-14 14:32
```
java.net.SocketInputStream.read.class java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:186)
    at java.net.SocketInputStream.read(SocketInputStream.java:140)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
    at java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:351)
    at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:746)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
    at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:717)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1604)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:678)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1401)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1367)
    at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:257)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1152)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1040)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:943)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
    at javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
    at jdk.internal.reflect.GeneratedMethodAccessor12.invoke
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    ....
```

**Comment by britzl** [comment] 2021-07-14 14:41
I believe this is a duplicate of https://github.com/defold/defold/issues/5890

@lessnoon do you have a network connection and have you allowed the Defold editor to make network requests?

**Comment by britzl** [comment] 2021-07-19 08:15
Duplicate of https://github.com/defold/defold/issues/5533

**Closed by britzl** 2021-07-19 08:15 UTC
Labels: editor, more info, windows
