### ISSUE TITLE
I got this error when I added a new collection proxy

### ISSUE THREAD

**Issue by hrkhaki** [defold/defold#6636] opened 2022-05-26 09:43 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-19T08:43:47.250124</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"849dbe4f0bde46ca8c49f3bdb4a94b88"'>849dbe4f0bde46ca8c49f3bdb4a94b88</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) RX Vega 11 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.14761 Compatibility Profile Context 21.30.14 30.0.13014.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-05-27 06:55
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1318)
    at editor.collection$CollectionNode$behavior$build_targets.invokeStatic(collection.clj:460)
    at editor.collection$CollectionNode$behavior$build_targets.invoke(collection.clj:460)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1145)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets$fn.invoke(collection_proxy.clj:89)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets.invokeStatic(collection_proxy.clj:89)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets.invoke(collection_proxy.clj:89)
```

**Comment by britzl** [comment] 2022-05-27 06:56
It seems like you have a cyclic dependency with one collection referencing another and vice versa

**Comment by britzl** [comment] 2022-06-20 05:05
Duplicate of #3919

**Closed by britzl** 2022-06-20 05:05 UTC
Labels: bug, editor
