### ISSUE TITLE
Error when pushing to github

### ISSUE THREAD

**Issue by Dzuvan** [defold/defold#5970] opened 2021-08-06 09:56 UTC
### Expected behaviour
Code is pushed without error. Code is pushed, it's just the error that appears.
### Actual behaviour
The erorr ops 
### Steps to reproduce
Add code, synchronize, try to push.
<hr/>

<table>
<tr><td>Build time</td><td>2021-07-29T20:48:50.037370</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold engine sha</td><td>0a8d3e879724132afb18d47e0040c2034be07504</td></tr>
<tr><td>Defold version</td><td>1.2.185</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0d383b6ad23f489fb5ef79f41342cf9f"'>0d383b6ad23f489fb5ef79f41342cf9f</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 5700 XT</td></tr>
<tr><td>GPU Driver</td><td>4.5.14831 Compatibility Profile Context 21.5.2 27.20.21003.8013</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2021-08-09 04:49
```
dynamo.graph$collect_overridden_properties$fn__7290.invoke.class clojure.lang.ExceptionInfo: Duplicate node key `no` from :editor.code.script/ScriptPropertyNode
    at dynamo.graph$collect_overridden_properties$fn.invoke(graph.clj:1262)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at dynamo.graph$collect_overridden_properties.invokeStatic(graph.clj:1276)
    at editor.defold_project$perform_resource_change_plan$fn.invoke(defold_project.clj:439)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:442)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:540)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:709)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:347)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:340)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:84)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment] 2021-08-09 04:49
Does this happen all the time?

**Comment by Dzuvan** [comment] 2021-08-09 09:27
No, this is happening at the moment on one project where I have a collection with several gos and each go has same script and go.property no which is a number  for which I get the error above. 
It happens both on pull and push via editor.

**Comment by britzl** [comment] 2022-12-02 20:12
Seems like there are two `go.property("no", ...)` in a script somewhere. Bad error message though.

**Comment by britzl** [comment] 2022-12-02 20:13
Unable to reproduce. Closing.

**Closed by britzl** 2022-12-02 20:13 UTC
Labels: bug, more info, editor
