### ISSUE TITLE
Mouse input messages are sometimes not sent

### ISSUE THREAD

**Issue by totebo** [defold/defold#5044] opened 2020-07-27 08:50 UTC
**Describe the bug**
Pressing and holding then releasing and pressing again quickly sometimes doesn't trigger mouse input messages.

**To Reproduce**
1. Build project (command + B).
2. Press and hold mouse button.
3. Release mouse button and quickly press again.
4. The release and press are not sent.

The issue is exacerbated when frame cap is reduced to lower than 60. The issue is always reproducible regardless of frame cap setting. 

**Expected behavior**
Input messages should include all inputs.

**Defold version:**
v1.2.170

**Platforms:**
MacOS

**Minimal repro case project:**
[MouseInputIssue.zip](https://github.com/defold/defold/files/4980879/MouseInputIssue.zip)

**Video replicating the issue:**

The circle indicates when the mouse is pressed.

https://youtu.be/JUMDCobgeII

1. Pressed (printed)
2. Released (printed)
3. Pressed (printed)
4. Released (**not printed**)
5. Pressed (**not printed**)
6. Released (printed)

**Additional context:**

Theory: The release and press happen during the same frame, preventing the input messages from being sent.  

Forum discussion: https://forum.defold.com/t/missing-mouse-input/65884/7

**Comment by xavierbasc** [comment] 2023-08-28 09:14
Any news about the correction of entries in macos? It happens to me too and it's annoying, I'm not considering launching the version in macos for this reason since it prevents you from pressing buttons on certain occasions, and it gives the feeling that the application does not work good.

**Comment by britzl** [comment] 2023-08-29 05:44
> Any news about the correction of entries in macos?

No news. I don't think anyone has looked into this issue yet.

**Comment by AGulev** [comment] 2023-08-29 06:31
> Any news about the correction of entries in macos? It happens to me too and it's annoying, I'm not considering launching the version in macos for this reason since it prevents you from pressing buttons on certain occasions, and it gives the feeling that the application does not work good.

I read your message and I think you are talking about this issue: https://github.com/defold/defold/issues/6709

**Comment by AGulev** [comment] 2023-08-29 07:42
I've just watched the video, and now I think it is the same issue. hmm

**Comment by gianmichelemariani** [comment] 2023-08-29 08:24
I believe I have been running into the same issue as well but thought it was something with the editor not being Arm native since re-launching the build process would work. 
Looking at the mentioned ticket it might be same.

**Comment by AGulev** [comment] 2023-09-04 08:04
Closed as duplicate of https://github.com/defold/defold/issues/6709 (should be fixed in 1.5.1)

**Closed by AGulev** 2023-09-04 08:04 UTC
Labels: bug, engine, input, macos
