### ISSUE TITLE
Cycle detected on node type editor.collection/CollectionNode

### ISSUE THREAD

**Issue by olliecotter** [defold/defold#6501] opened 2022-03-28 17:33 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-19T08:00:46.134016</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"972c89b0aaf54eecbd904a40a816f04b"'>972c89b0aaf54eecbd904a40a816f04b</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment] 2022-03-29 06:49
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1322)
    at editor.collection$CollectionNode$behavior$build_targets.invokeStatic(collection.clj:460)
    at editor.collection$CollectionNode$behavior$build_targets.invoke(collection.clj:460)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1146)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets$fn.invoke(collection_proxy.clj:89)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets.invokeStatic(collection_proxy.clj:89)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets.invoke(collection_proxy.clj:89)
    at clojure.lang.Var.invoke(Var.java:393)
```

**Comment by britzl** [comment] 2022-03-29 06:52
@olliecotter this is most likely caused by a cyclic dependency in your code. It could for instance be that you have a collection A with a collection proxy or collection factory referencing collection B. And in collection B you have a reference back to collection A.

A similar issue can happen when Lua module A requires Lua module B and vice versa.

**Comment by britzl** [comment] 2022-03-29 06:53
Duplicate of #3919

**Closed by britzl** 2022-03-29 06:53 UTC
Labels: bug, editor

**Comment by olliecotter** [comment] 2022-03-29 09:07
Thank you very much, I have solved the issue.
