### ISSUE TITLE
Show unsaved files in Changed Files panel (DEFEDIT-1142)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3954] opened 2019-05-27 05:36 UTC
List files with unsaved changes alongside files with modified Git status in the Changed Files panel.
2017-09-28 10:22:07 (Mats.Gisselson)
Work can continue on this once DEFEDIT-1143 has been addressed.

**Comment by AGulev** [comment] 2024-05-03 21:45
duplicate of https://github.com/defold/defold/issues/7999

**Closed by AGulev** 2024-05-03 21:45 UTC
Labels: feature request, editor
