### ISSUE TITLE
Physics debug shapes sometimes flicker when fixed timestep is enabled

### ISSUE THREAD

**Issue by totebo** [defold/defold#9409] opened 2024-09-10 13:06 UTC
**Describe the bug (REQUIRED)**
Physics debug shapes sometimes flicker when fixed timestep is enabled.

**To Reproduce (REQUIRED)**
Enable both physics debug and fixed timestep and build project. 

**Expected behavior (REQUIRED)**
Stable rendering of debug shapes.

**Defold version (REQUIRED):**
1.9.2

**Platforms (REQUIRED):**
macOS

**Minimal repro case project (OPTIONAL):**
Build this minimal project:
[FixedUpdateDebugPhysics.zip](https://github.com/user-attachments/files/16945209/FixedUpdateDebugPhysics.zip)

**Screenshots (OPTIONAL):**
https://www.youtube.com/watch?v=loI9TjrV6Wg

**Comment by AGulev** [comment] 2024-09-10 13:15
duplicate of https://github.com/defold/defold/issues/7617

**Closed** 2024-09-16 07:10 UTC
Labels: bug
