### ISSUE TITLE
Collision object AABB broken if parent go is rotated (DEFEDIT-1602)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3862] opened 2019-05-27 05:34 UTC
The reason is that we currently treat the aabb as a 3d box (-1 -1 -1)-(1 1 1) so for instance rotating a box around Y (up to 45) will of course make it grow in X. We always render the box as a flat (2d) rectangle.

TODO:
- Respect the physics type (2d/3d) when drawing and for aabb
- Mimic the engine support for collision objects. For instance, when using 2d physics the engine only respects rotations around Z.

**Comment by AGulev** [comment] 2024-03-08 20:16
closed as duplicate of https://github.com/defold/defold/issues/5253
(data pasted there)

**Closed by AGulev** 2024-03-08 20:16 UTC
Labels: bug, editor
