### ISSUE TITLE
Press the restart button on the size property of a template in the gui properties panel.

### ISSUE THREAD

**Issue by FelipeSuarezPlazas** [defold/defold#9152] opened 2024-07-01 22:12 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:29:23.653181</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4aaf4d6b533e455caae3e50822c5e7a9"'>4aaf4d6b533e455caae3e50822c5e7a9</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by AGulev** [comment] 2024-07-02 07:04
duplicate of https://github.com/defold/defold/issues/8546

**Comment by AGulev** [comment] 2024-07-02 07:06
```
clojure.lang.PersistentVector.arrayFor.class java.lang.IndexOutOfBoundsException: null
    at clojure.lang.PersistentVector.arrayFor(PersistentVector.java:158)
    at clojure.lang.PersistentVector.nth(PersistentVector.java:162)
    at clojure.lang.RT.nth(RT.java:892)
    at editor.properties_view$create_multi_textfield_BANG_$fn$fn.invoke(properties_view.clj:162)
    at clojure.core$map$fn.invoke(core.clj:2753)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.LazySeq.first(LazySeq.java:73)
    at clojure.lang.RT.first(RT.java:688)
    at clojure.core$first__5369.invokeStatic(core.clj:55)
    at editor.properties$unify_values.invokeStatic(properties.clj:556)
    at editor.properties_view$update_multi_text_fn.invokeStatic(properties_view.clj:54)
    at editor.properties_view$update_multi_text_fn.invoke(properties_view.clj:50)
    at clojure.core$partial$fn.invoke(core.clj:2640)
    at editor.properties_view$create_properties_row$update_ui_fn.invoke(properties_view.clj:553)
    at editor.properties_view$refresh_pane_BANG_.invokeStatic(properties_view.clj:636)
    at editor.properties_view$update_pane_BANG_.invokeStatic(properties_view.clj:658)
    at editor.properties_view$fn$fn.invoke(properties_view.clj:677)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Closed** 2024-07-06 16:05 UTC
Labels: bug, editor
