### ISSUE TITLE
HTML5 crash on joystick connect

### ISSUE THREAD

**Issue by FlexYourBrain** [defold/defold#5731] opened 2021-04-09 01:30 UTC
Defold version 1.2.181
OS: Windows
Browser's tested: Chrome and Firefox

Description: Using menu in editor to build - (Project / Build HTML5) produces error on loading in browser. I have tested simple project with html5 build in the past and worked fine. Project does not contain audio.

Reproduce: I have created a minimal test project and have tried a few example projects from britzl and receive the exact same error when building HTML5 from editor.

(Debug in chrome seen here)
![Defold_html5_build_error](https://user-images.githubusercontent.com/28400489/114113173-ab8a7080-98a3-11eb-8dc8-411170930546.png)

**Comment by FlexYourBrain** [comment] 2021-04-09 03:43
After generating App Manifest to exclude the following, building HTML5 from editor now works.

Excluded:
 Physics 2D 
 Physics 3D 
 Record 
 Profiler 
 Sound

**Comment by britzl** [comment] 2021-04-10 09:10
The AudioContext warning is likely not the problem. Browsers have a policy that they do not allow websites to play sounds immediately on load. You are only allowed to play sounds as a result of user interaction (key, mouse, touch etc).

The stack trace of the error mentions onJoystickConnected which is interesting. Do you have a gamepad connected?

**Comment by FlexYourBrain** [comment] 2021-04-10 19:43
@britzl Thank you for pointing out about possible gamepad issue. At the time I did not have a controller connected. After digging a little deeper I found an issue on my end with razer nostromo driver causing the above error. After uninstalling the driver I no longer get the joystick error and can now build HTML5 normally. I still get AudioContext warning and favicon.ico error but not concerned. Issue resolved. Thank you for your time.

**Comment by britzl** [comment] 2021-04-11 05:57
Interesting about the driver! I think we'd like to look into that crash anyway though. We do not like it when Defold is crashing for any reason :-)

**Comment by FlexYourBrain** [comment] 2021-04-11 19:28
@britzl Ah apologies. To clarify a bit more I was using a legacy driver from 2013 for the device. I reinstalled the legacy driver and got the same issue. Then I installed the most up to date driver using razer synapse and can build HTML5 from editor without crashing in browser, driver no longer conflicts. Seems to me to be more of a legacy issue and not a Defold issue , but if you would like more info or anything I can do, just let me know and I will try to provide the information. Thank you.

**Comment by britzl** [comment] 2021-04-11 20:30
Thanks. I'll take a quick look at our code to see if I spot anything obvious.

**Comment by britzl** [comment] 2021-04-12 09:16
The function signature for alloc() has changed in a recent Emscripten release:

https://emscripten.org/docs/api_reference/advanced-apis.html#allocate

Use in the engine here:

* https://github.com/defold/defold/blob/dev/engine/glfw/js/library_glfw.js#L508
* https://github.com/defold/defold/blob/dev/engine/script/lib/js/library_script.js#L17

And in extensions:

* https://github.com/defold/extension-fbinstant/blob/master/fbinstant/lib/web/library_fbinstant.js#L23

**Comment by AGulev** [comment] 2021-04-13 06:38
@britzl 
To be honest i don't get it, in all examples you showed here, we use function with 3 parameters, but in you fix you removed the second one. Does that mean that all the extensions and the other places should be fixed and use only 2 parameters?

**Comment by britzl** [comment] 2021-04-13 07:10
Exactly. The problem is that the alloc() function in Emscripten has changed and now only takes two argument. This means that we need to change in the engine (glfw.js and script.js) and in all extensions.

Note: We should maybe use Module._malloc() instead as that seems to be a public method, while the alloc() method is mentioned as internal in the Emscripten docs.

**Closed** 2021-04-19 08:47 UTC
Labels: bug, html5, more info
