### ISSUE TITLE
Run with debugger is slow (DEFEDIT-1567)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3874] opened 2019-05-27 05:34 UTC
We pass in the start.lua file which requires debugger.lua and calls debugger.start() which sets up mobdebug. This will call mobdebug.coro() which will enable the debugger.

If the editor could be set into "debug" mode we could provide the developer with access to the editor instance of mobdebug and let the developer choose via code when to enable mobdebug.

**Comment by AGulev** [comment] 2022-02-12 15:59
duplicate of https://github.com/defold/defold/issues/3380

**Closed by AGulev** 2022-02-12 15:59 UTC
Labels: feature request, editor
