### ISSUE TITLE
Try build the project getting error "Optimization pass failed"

### ISSUE THREAD

**Issue by AndreErvilha** [defold/defold#8231] opened 2023-11-09 22:31 UTC
### Expected behaviour
build the GAME
### Actual behaviour
![image](https://github.com/defold/defold/assets/56570862/eb2fd6ad-8285-4ceb-b5fe-90e35c697d83)

### Steps to reproduce
folow steps of https://github.com/defold/tutorial-war-battles until after create map, and then go project>build
<hr/>

<table>
<tr><td>Build time</td><td>2023-11-03T14:02:18.830742</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>36a0c9ec890ce4d1a12239163a1b44a9bb80de3c</td></tr>
<tr><td>Defold engine sha</td><td>a90c50928623cf23b3687a7eec05972d11427202</td></tr>
<tr><td>Defold version</td><td>1.6.1</td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 27.20.100.8729</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2023-11-10 07:57
Hmm, could you please try to update the editor (there is a Restart to Update in lower right corner) and try again?

**Comment by AGulev** [comment] 2023-11-10 07:59
Please try to update your Intel GPU drivers using Intel® Driver & Support Assistant :
https://forum.defold.com/t/engine-building-error-solved/68798/29?u=agulev

**Comment by AGulev** [comment] 2023-11-30 20:39
Duplicate of https://github.com/defold/defold/issues/8277
take a look this ticket for workaround

**Closed by AGulev** 2023-11-30 20:39 UTC
Labels: bug, more info, editor, pipeline
