### ISSUE TITLE
Editor works extremely slow when trying to open font with a big count of glyphs

### ISSUE THREAD

**Issue by AGulev** [defold/defold#7187] opened 2022-11-28 13:20 UTC
The editor becomes unresponsible when open a font with big count of glyphs.
1. Open the attached project
2. Double click `KlokanTechNotoSansCJK-Bold.font` file
[SlowFontEditorRepo.zip](https://github.com/defold/defold/files/10104052/SlowFontEditorRepo.zip)

**Comment by 8bitskull** [comment] 2022-12-07 09:44
+1 for me. Any time I make changes to my localised game I have to update multiple fonts for 4 languages (Chinese x2, Japanese, Korean). The larger font sizes in particular freeze up for 15 seconds or so when updated, and this is for a game with relatively little text.

**Comment by vlaaad** [comment] 2023-02-03 10:52
Fixed in #7358

**Closed by vlaaad** 2023-02-03 10:52 UTC
Labels: bug, editor, font, performance

**Comment by 8bitskull** [comment] 2023-02-03 13:10
@vlaaad Nice work on this! Is this change live in editor fbc1a7c69c312b9f263010b1f2b098220b7602b3?

I tested it and it seems not to be working as intended. See the screenshot below: 

![image](https://user-images.githubusercontent.com/24439991/216611301-19acfc35-0771-46ce-9cfb-b43db212222b.png)

The Chinese characters don't seem to be rendered at all anymore (at least in this instance).

**Comment by vlaaad** [comment] 2023-02-03 13:59
That's a separate issue: in the editor we have a single texture for characters, and with such a big font size not many characters can fit into the texture.
