### ISSUE TITLE
Requiring penlight stringx throws an error

### ISSUE THREAD

**Issue by hsjunnesson** [defold/defold#5184] opened 2020-09-09 17:21 UTC
### Expected behaviour

requiring penlight should work!

### Actual behaviour

The editor asserts with:

```
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
```

### Steps to reproduce

Download the 1.8.0 release of Penlight, place it in your project. Then:
```
local stringx = require 'main.pl.stringx'
```

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-20T10:48:17.000583</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5797e374b07cac16d71a29c264bd89e63cfe7652</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"77affc5b44e141449c4b8bb885271ec7"'>77affc5b44e141449c4b8bb885271ec7</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 452.06</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-09-10 05:56
I believe this is caused by a cyclic dependencie in the Penlight library (a requires b and b requires a).

**Comment by britzl** [comment] 2022-03-22 07:32
Duplicate of https://github.com/defold/defold/issues/4893

**Closed by britzl** 2022-03-22 07:32 UTC
Labels: bug, editor
