### ISSUE TITLE
Add function to remove a stored live update resource

### ISSUE THREAD

**Issue by britzl** [defold/defold#4657] opened 2020-02-12 05:48 UTC
It should be possible to remove a stored Live Update resource (ie resource.remove_resource())

Useful when testing and when you need to make room for other resources.

https://forum.defold.com/t/could-not-publish-liveupdate-content-to-aws/64396/10

**Comment by AGulev** [comment] 2022-08-03 20:09
duplicate of https://github.com/defold/defold/issues/4722

**Closed by AGulev** 2022-08-03 20:09 UTC
Labels: feature request, engine, live update
