### ISSUE TITLE
Defold incapable of creating any type of new project unless there is an internet connection

### ISSUE THREAD

**Issue by DiiaBlood** [defold/defold#8031] opened 2023-09-22 19:16 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
On its own, Defold, cannot create any type of new project **unless** it has a connection to the internet. Which makes sense for the sample projects and demos, but the blank project? I don't feel so myself.

**Describe the solution you'd like (REQUIRED):**
A minimal solution is to either include the **Blank Project** itself with the engine, so it can do that at least. Or just all the templates.

**Describe alternatives you've considered (REQUIRED):**
I can download the template from GitHub or just copy it from another project. But I fail to understand why an offline reliable choice to a reliable engine doesn't seem to be the normal.

**Additional context (OPTIONAL):**
Maybe a lot of people don't feel it, but living in a not so well suited for technology location, internet can sometimes ✨not exist✨ which might lead to some... unnecessary scenarios.

Oh, upon further inspection, I have noticed that issue #3930 and this issue have the same goal, but considering the "2019" tag on the last update... I decided to continue and post this request. I do apologize if this breaks some rule. Thanks for your time.

I just noticed that I have been writing this entire thing like a job application! Like... why!?!?

**Comment by AGulev** [comment] 2024-03-09 13:48
duplicate of https://github.com/defold/defold/issues/8031

**Closed by AGulev** 2024-03-09 13:48 UTC
Labels: feature request, editor
