### ISSUE TITLE
report

### ISSUE THREAD

**Issue by hoosierflyboy** [defold/defold#6085] opened 2021-10-04 04:09 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-09-20T09:08:33.459678</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>03b14982258f69eb8a06d28810ae879e16bd63d7</td></tr>
<tr><td>Defold engine sha</td><td>581c6439ae93755a8a6bcf58732c39c724fa193c</td></tr>
<tr><td>Defold version</td><td>1.2.187</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"257de994dde04a8ea8014004c1641ee2"'>257de994dde04a8ea8014004c1641ee2</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-86-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-10-04 14:52
```
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

@hoosierflyboy please check this FAQ entry:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:14
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:14 UTC
Labels: bug, more info, editor, linux
