### ISSUE TITLE
I just can't right click on Atlas

### ISSUE THREAD

**Issue by MDdiamondOrigin** [defold/defold#6309] opened 2022-01-05 13:44 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T08:40:34.121967</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5369ecd3889f43879b8b3bfaf2e9cace"'>5369ecd3889f43879b8b3bfaf2e9cace</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 3GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 456.71</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-12-02 20:18
Unable to reproduce. No additional information provided. Closing.

**Closed by britzl** 2022-12-02 20:18 UTC
Labels: bug, more info, editor
