### ISSUE TITLE
Loader 

### ISSUE THREAD

**Issue by AriZz05** [defold/defold#7184] opened 2022-11-27 20:28 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-15T14:40:05.532720</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cb4cc114221bf2bdabb1dd3c988fb333dc1e836a</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a49d0a620b5d48769f914e6ef5b119a5"'>a49d0a620b5d48769f914e6ef5b119a5</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(R) Xe Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 31.0.101.3616</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-11-27 20:58
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1322)
    at editor.collection$CollectionNode$behavior$build_targets.invokeStatic(collection.clj:460)
    at editor.collection$CollectionNode$behavior$build_targets.invoke(collection.clj:460)
    at clojure.lang.Var.invoke(Var.java:393)
```

**Comment by britzl** [comment] 2022-11-27 21:02
Duplicate of https://github.com/defold/defold/issues/3919

**Comment by britzl** [comment] 2022-11-27 21:04
This is most likely caused by a cyclic dependency in your code. It could for instance be that you have a collection A with a collection proxy or collection factory referencing collection B. And in collection B you have a reference back to collection A.

**Closed by britzl** 2022-11-27 21:04 UTC
