### ISSUE TITLE
If a GO has a regular collisionobject along with a tilemap collision object, calling 'set_tile'  will fail. (DEF-3609)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3164] opened 2019-05-23 10:31 UTC
Reported here [(LINK REMOVED)and(LINK REMOVED)Probably an assumption in the implementation that there is only one (tilemap) collision object on a GO.

**Comment by AGulev** [comment] 2022-01-29 16:42
duplicate of https://github.com/defold/defold/issues/3167

**Closed by AGulev** 2022-01-29 16:42 UTC
Labels: bug, engine, physics, tilemap
