### ISSUE TITLE
IDE: Unsorted order of assets

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#6806] opened 2022-07-17 12:12 UTC
**Describe the bug (REQUIRED)**
It seems that the issue https://github.com/defold/defold/issues/5981 hasn't been fixed. Now, the order of the assets is messed up, yes?

![image](https://user-images.githubusercontent.com/193258/179397565-a1aaa4ab-5278-48e9-bfdd-58c9fbbd4594.png)

**To Reproduce (REQUIRED)**
Open the attached project in the latest editor.

**Expected order**
```
(FOLDERS)
builtins
editor_scripts
folder1
folder2
folder10
folder20
input
ld50
ld50_html5
ld50-test
main
monarch
monarch_3000
scene3d

(FILES)
game.project
README.md
```

**Defold version (REQUIRED):**
  - Version 1.3.4 
  - Editor SHA1 `c0ed825ede46b0112d1e4fd744fd50f460073229`
  - Engine SHA1 `80b1b73fd9cdbd4682c2583403fddfbaf0919107`

**Platforms (REQUIRED):**
 - OS: Windows 10

**Minimal repro case project (OPTIONAL):**
[test_natural_sort.zip](https://github.com/defold/defold/files/9127576/test_natural_sort.zip)

**Comment by vlaaad** [comment] 2022-07-17 13:35
Woah, folder order is super messed up. I'll check this once I'm back from the vacation. One idea I have in mind — our comparator might not try hard enough when sorting folders specifically..

**Comment by vlaaad** [comment] 2022-08-01 08:37
I see that editor sha `c0ed825` is fairly recent and should incorporate the sort order changes. I also cannot reproduce the issue — when I create more folders, they are correctly sorted. Weird.

**Comment by britzl** [comment] 2022-08-15 07:16
No additional information provided. Closing.

**Comment by aglitchman** [comment] 2022-08-15 08:40
1.3.5 BETA:
![image](https://user-images.githubusercontent.com/193258/184604165-05433617-8df2-4901-9900-eb62ab98eaf9.png)

**Comment by britzl** [comment] 2022-08-15 08:55
Huh. Reopening.

**Comment by britzl** [comment] 2022-08-15 08:56
@aglitchman does this happen immediately when you open the project?

**Comment by vlaaad** [comment] 2022-08-15 08:57
I believe it can be reproduced since the reported issue is for an editor SHA with a new natural ordering code. The problem is — I can't reproduce the issue locally, I tried both on mac and windows...

**Comment by britzl** [comment] 2022-08-15 09:04
Could it be related to the user locale and string comparison rules or something?

**Comment by aglitchman** [comment] 2022-08-15 09:04
> @aglitchman does this happen immediately when you open the project?

Yes, it happens immediately!

Previously, I thought it was an ordinary bug and it would be easy to reproduce, i.e. I tested the issue on both my work computers with Windows 10. They are absolutely usual PCs without any special software that can mess that things.

Now, I tried to download the beta editor and the project on my laptop with Ryzen 2500U/Windows 10 x64 and I got the same issue.

It's an absolutely weird 😢 

(the screenshot below is from laptop's screen)
![image](https://user-images.githubusercontent.com/193258/184607631-50be3381-3894-49c3-8d9b-549499d6de23.png)

**Comment by aglitchman** [comment] 2022-08-15 09:14
I managed to test the project on another PC that has **Windows 11** and a different hardware (Intel Core CPU + Geforce RTX 3060). The same:

![image](https://user-images.githubusercontent.com/193258/184609016-daf658e9-3088-4ea3-a27c-1144b27a854f.png)

**Comment by aglitchman** [comment] 2022-08-15 09:16
> Could it be related to the user locale and string comparison rules or something?



> Could it be related to the user locale and string comparison rules or something?

It can be! All computers have Russian system locale.

Additionally, I tried to move the editor and the project to the root of the system disk (`C:\`) to test behaviour on the different path to the project - the issue is still here 😭

**Comment by aglitchman** [comment] 2022-08-15 10:02
@britzl @vlaaad If you have any ideas, I would love to test them 🙏🏻

**Comment by vlaaad** [comment] 2022-08-15 13:55
Hmm, I'll try reproducing it with russian locale..

**Comment by vlaaad** [comment] 2022-08-17 08:58
This is actually not a "super messed up", it's a behavior of our old sorting approach. The behavior sorts on data structures like `["folder", 1]` and `["ld", 50, "-test"]`, where shorter arrays are always sorted first. This behavior was replaced with a correct one.

It seems that beta branches used older versions of the editor that didn't incorporate natural order changes. I "reproduced" it by downloading a version of the editor that didn't include the changes, it's not related to system locales. 

The problem will disappear once the beta branch is updated to a newer editor code.

**Closed by vlaaad** 2022-08-17 08:58 UTC
Labels: bug, more info, editor
