### ISSUE TITLE
Listening for debugger

### ISSUE THREAD

**Issue by kouba06** [defold/defold#5261] opened 2020-10-05 23:19 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-09-28T10:12:41.523768</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d429a186416e1b0fce254b7e4379d5802de060d9</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c142de1a4d124d39b80f1c7dd5afdb26"'>c142de1a4d124d39b80f1c7dd5afdb26</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 22.20.16.4836</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-10-06 06:48
Duplicate of #4904

**Closed by britzl** 2020-10-06 06:48 UTC
