### ISSUE TITLE
Adding image to editor via drag and drop and error was thrown. 

### ISSUE THREAD

**Issue by bar1tech** [defold/defold#7754] opened 2023-06-19 17:37 UTC
### Expected behaviour

Expected to drag and drop an image from the Documents folder on my Mac to the _Assets > Project Name > images_ folder in the in Defold editor Assets Panel.

### Actual behaviour

As the image was being dragged from the Documents folder into Defold this error was thrown when my mouse crossed over into Defold from the desktop.

### Steps to reproduce

Updated to 1.4.7 this morning and project started from empty project template.
Following along the tutorial at: https://www.youtube.com/watch?v=VU2aJSLmo7Y
Decided to add my own image to the project at the 23:48 mark.
Started to drag an image from the Documents folder on my Mac to the images folder in my project and when the mouse crossed over into Defold this error was thrown.

<hr/>

<table>
<tr><td>Build time</td><td>2023-06-19T12:41:28.343646</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>94b853c671eb5264895b206dc427071978277cfa</td></tr>
<tr><td>Defold engine sha</td><td>7a608d3ce6ed895d484956c1e76110ed8b78422a</td></tr>
<tr><td>Defold version</td><td>1.4.7</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"202c5b0356064c7986daac842793c60a"'>202c5b0356064c7986daac842793c60a</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.4</td></tr>
<table>

**Comment by bar1tech** [comment] 2023-06-19 17:40
Addendum:
After filling out this error report and returning back to Defold I successfully added the image via drag and drop to the project without closing and restarting Defold.

**Comment by britzl** [comment] 2023-06-20 09:55
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1017)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:276)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1301)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3079)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3148)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3910)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1887)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2620)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by bar1tech** [comment] 2023-06-29 12:34
This error is sporadically being thrown when focus is returned to Defold. 

If I move my mouse away from Defold to a Finder window and then return to Defold this error is sometimes thrown.  

I was working with a 6 to 7 year old project:  https://github.com/adamwestman/defkit

I could create a new issue every time but I don't want to bombard the server as it seems related to #7754.  If it is more conducive to report every error occurrence I will if desired. 
 

<img width="664" alt="Screenshot 2023-06-29 at 8 25 01 AM" src="https://github.com/defold/defold/assets/52499915/adbeee56-7acc-4813-add7-77ef01badc4b">

**Comment by bar1tech** [comment] 2023-07-13 01:25
Another variation of the drag-and-drop error. This occurred with the Mobile Project template.  

I was working with this project:  [Square Fall Tutorial Part 1](https://www.youtube.com/watch?v=Tz-AinJGDIM&list=PLEFCE8MJPFC6IjN9s-eAaBmR-HVS_s1L5&index=1)

At the 1:14 mark we drag and drop assets from our Finder to the project and this error was thrown.  After dismissing the error pop-up the files are present in the project and I proceeded to work without restarting Defold.


<img width="566" alt="Screenshot 2023-07-12 at 9 14 02 PM" src="https://github.com/defold/defold/assets/52499915/05ccfff8-d35c-424a-9ef3-82e18357a303">

--
Also included is the editor log:

[editor2.2023-07-12.log](https://github.com/defold/defold/files/12034441/editor2.2023-07-12.log)

**Comment by iustin-ghe** [comment] 2023-09-04 10:14
Same thing happens to me while trying to drag and drop assets from the Mac Finder window into Defolt. Copy pasting through keyboard shortcuts does work.

**Comment by britzl** [comment] 2023-09-25 12:54
Duplicate of https://github.com/defold/defold/issues/5875

**Closed by britzl** 2023-09-25 12:54 UTC
Labels: bug, editor, macos
