### ISSUE TITLE
Switching tab with visible auto-completion causes NullPointerException

### ISSUE THREAD

**Issue by TBDesignes** [defold/defold#4944] opened 2020-06-21 14:32 UTC
### Expected behaviour
I wrote down a bit of code in script editor. There was the auto-completion menu (ctrl+space) visible and I switched to tutorial.md tab.
### Actual behaviour
An error occured: NullPointerException 
### Steps to reproduce
Open auto-completion and switch to any .md tab
<hr/>

<table>
<tr><td>Build time</td><td>2020-06-17T10:06:38.299614</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e5389d28eab7bfdc5b8edccad637aadcd2832a29</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"329343593b5047afa98f669eab5faeca"'>329343593b5047afa98f669eab5faeca</a></td></tr>
<tr><td>GPU</td><td>GeForce MX150/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 417.71</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-06-21 20:52
javafx.scene.control.skin.TabPaneSkin in stopDrag

**Comment by britzl** [comment] 2020-06-21 20:53
Duplicate of #4852

**Closed by britzl** 2020-06-21 20:53 UTC
Labels: editor, javafx
