### ISSUE TITLE
error happened when adding script

### ISSUE THREAD

**Issue by Krunal-Gadhiya** [defold/defold#9235] opened 2024-07-26 12:08 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-22T13:12:02.990812</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c0a3bfcc2f85877ab9f46a3d71d38b1667ef59bc</td></tr>
<tr><td>Defold engine sha</td><td>3be87d89fd5a93a63f527351fbedb84f8a875812</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"01988f7b836a41d98e893159f23b96e6"'>01988f7b836a41d98e893159f23b96e6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 570 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.57, 6.9.9-1-MANJARO)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.1.3-manjaro1.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.9.9-1-MANJARO</td></tr>
<table>

**Comment by AGulev** [comment] 2024-07-26 12:10
```
editor.code.data$last_visible_row.invokeStatic.class java.lang.NullPointerException: Cannot read field "dropped_line_count" because "layout" is null
    at editor.code.data$last_visible_row.invokeStatic(data.clj:1188)
    at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:3078)
    at editor.code.view$make_view_BANG_$fn.invoke(view.clj:3660)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)

**Comment by vlaaad** [comment] 2024-07-29 12:00
Closing as duplicate of #9238 

I can't reproduce the issue on Linux, if you have a way to repro it, please share it in #9238

**Closed** 2024-07-29 12:05 UTC
Labels: bug, editor, linux
