### ISSUE TITLE
The second opened Defold window becomes unresponsive after a certain amount of time

### ISSUE THREAD

**Issue by pmaak** [defold/defold#7939] opened 2023-09-01 05:40 UTC
### Expected behaviour
When opening a second project using the "File/Open project" menu, a second instance of the Defold editor should launch.

### Actual behaviour
After a short period of working with the second editor window, it becomes unresponsive. The macOS spinning wheel appears consistently. The only solution is to force close the second window. The first opened instance of Defold remains functional.

### Steps to reproduce
1. Open a second window using the "File/Open project" menu.
2. Perform typical actions such as edit code, opening collections, moving game objects, and editing collections.
3. At a certain point, the window will become unresponsive.

<hr/>

<table>
<tr><td>Build time</td><td>2023-08-31T15:20:55.244036</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b55f345ff78d2f3d2d0d401d535e0f3a4756e282</td></tr>
<tr><td>Defold engine sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>GPU</td><td>Apple M1 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.4</td></tr>
<table>

**Comment by philousoph** [comment] 2023-09-20 12:38
Can confirm this, very annoying.

**Comment by AGulev** [comment] 2023-09-26 07:10
I think this is the same issue https://github.com/defold/defold/issues/7845

**Comment by AGulev** [comment] 2023-11-09 12:06
closed as duplicate of https://github.com/defold/defold/issues/7845

**Closed by AGulev** 2023-11-09 12:06 UTC
Labels: editor

**Comment by vlaaad** [comment] 2023-11-10 08:20
FYI, the fix to our upstream dependency that causes the issue is merged, and we expect to update the version soon (i.e. in 1-2 work days)
