### ISSUE TITLE
Problem opening template page of editor welcome screen

### ISSUE THREAD

**Issue by 3331615526** [defold/defold#5943] opened 2021-07-19 06:54 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:47:07.405749</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"964df08fd3b546799cb62d7fc28e7f6c"'>964df08fd3b546799cb62d7fc28e7f6c</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4400</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 10.18.14.4432</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by britzl** [comment] 2021-07-19 08:16
Duplicate of https://github.com/defold/defold/issues/5533

**Closed by britzl** 2021-07-19 08:16 UTC
Labels: bug, editor, windows
