### ISSUE TITLE
Error when attaching debugger

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#9016] opened 2024-06-01 18:05 UTC
Attaching to a already running instance doesn't work.

Starting with the debugger works. I get this error but the debugger still got attached and is working.

<hr/>

<table>
<tr><td>Build time</td><td>2024-05-28T13:22:19.138953</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold engine sha</td><td>fd1ad4c17bfdcd890ea7176f2672c35102384419</td></tr>
<tr><td>Defold version</td><td>1.8.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a96c51afddec43468b9a3f20850dd3c6"'>a96c51afddec43468b9a3f20850dd3c6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 7900 XT</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 24.3.1.240312</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment] 2024-06-01 18:44
```
editor.debugging.mobdebug$connect_BANG_$fn__62195.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by AGulev** [comment] 2024-06-03 07:11
duplicate of https://github.com/defold/defold/issues/8885

**Closed by AGulev** 2024-06-03 07:11 UTC
