### ISSUE TITLE
Template projects should have offline backups shipped with Defold and used when there is no Internet connection

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5175] opened 2020-09-08 03:10 UTC
Since these projects are small, versions of them should be shipped with Defold. If no net is connected (which can commonly happen to some people around the world), the local versions should be used when making new projects based on them. Otherwise newest ones from the net can be fetched.

**Comment by britzl** [comment] 2021-02-25 10:32
Duplicate of https://github.com/defold/defold/issues/3930

**Closed by britzl** 2021-02-25 10:32 UTC
Labels: editor, feature request
