### ISSUE TITLE
Different results for raycasts with no options and with "all" set to false

### ISSUE THREAD

**Issue by K-Klear** [defold/defold#7032] opened 2022-10-04 17:38 UTC
**Describe the bug (REQUIRED)**
A raycast without options set returns just the list of values, but if options are set to {all = false} then this list is encased in a table with a single index, similar to the case when {all = true}.

**To Reproduce (REQUIRED)**
Compare the results of two identical racasts, except one has "all" set to false.

**Expected behavior (REQUIRED)**
Both raycasts should return the values in the same format.

**Defold version (REQUIRED):**
1.3.6

**Platforms (REQUIRED):**
Windows

**Comment by britzl** [comment] 2022-10-15 15:29
Ah, I see what is happening here. The `options` table is new and did not exist in the original version of the raycast function. The original version of raycast returned the result just like you describe without an enclosing table. The new version where it is possible to specify that you want all hits will return the hits enclosed in a table.

This is not a bug but rather a way to keep the API backwards compatible. Closing.

**Closed by britzl** 2022-10-15 15:29 UTC
Labels: bug, physics, good first issue
