### ISSUE TITLE
Random Frame on Each Spawned Particle 

### ISSUE THREAD

**Issue by bvenzen** [defold/defold#8648] opened 2024-03-08 01:03 UTC
Having the ability to let an emitter choose a random frame from an atlas animation for each particle it spawns would be really helpful. Currently there is no way to set the emitter to spawn particles with a random animation frame.

It would be great if we could set up an "animation" in an atlas like the workflow for an animated spritesheet, then in the particle emitter when you chose which image to use you can choose that animation, but there is an added button in the emitter where we can select linear animation or random frame. If you choose random frame, a unique frame from that animation will be displayed on each particle and the particles hold on that frame for their entire life time. Each new particle spawned chooses a new frame to display giving you random frames on each. 

A workaround is to add a new emitter for each frame you want in your particle fx, but this is expensive, clunky, and difficult to keep updated.

![unnamed](https://github.com/defold/defold/assets/81985690/14968d86-47b1-4172-8500-be87cf0b355d)

**Comment by britzl** [comment] 2024-05-30 06:00
Duplicate of #5332

**Closed by britzl** 2024-05-30 06:00 UTC
Labels: feature request, engine, editor, particlefx, atlas
