### ISSUE TITLE
Editor : some shortcuts don't work with an AZERTY keyboard

### ISSUE THREAD

**Issue by Brun0oO** [defold/defold#5377] opened 2020-11-30 12:45 UTC
**Describe the bug (REQUIRED)**
Using an AZERTY keyboard (on a macbook pro laptop), some shortcuts like [cmd]+[a] ("select all") or [cmd]+[z] ("undo") for example don't work. It's also a little bit "annoying" because [cmd]+[a]  performs a [cmd]+[q] (AZERTY -> QWERTY) so my editor window immediately closes.

**To Reproduce (REQUIRED)**
1. Open the editor with an AZERTY keyboard on a Mac OS computer
2. Open a project
3. Open a script file
4. Call the [cmd]+[a] keyboard shortcut
5. The editor window immediatley closes!

**Expected behaviour (REQUIRED)**
[cmd]+[a] should call the select all shortcut
[cmd]+[z] should call the undo shortcut

**Defold version (REQUIRED):**
  - Version 1.2.176

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: Catalina

**Comment by britzl** [comment] 2020-11-30 13:05
We recently added support for customizing keyboard shortcuts:

https://defold.com/manuals/editor/#customizing-shortcuts

Perhaps this can help you?

**Comment by lost-in-hub** [comment] 2021-03-21 14:52
Hi, i'm not really used to all of this. I've followed my path through the Discord, then the forum, to land here. So please forgive me if i'm doing it wrong by posting here instead of opening a new bug report.
I am too a user of Mac OS Catalina, french AZERTY keyboard, and encountered the same bug.
I wanted to add a few details.
What confused me a lot and that i did not notice at first, is that the keyboard layout "switches" depending on the context. Let me explain this a bit more.
When editing code, the keyboard is mapped correctly ( AZERTY ) by default, only when i use shortcuts it is mapped to QWERTY.
When in game, it is mapped to QWERTY by default, and only when using shortcuts ( eg : Meta + Q to close ) it is mapped to AZERTY.
I have downloaded the macos keyboard map and done the customizing shortcuts path thing. Did not solve it, as the "keyboard map switch" still occurs.
Hoping this can help to solve it, and that i did not wrong posting here.

**Comment by beldenfox** [comment] 2023-05-26 18:42
This was due to a bug in JavaFX which was fixed with openjdk/jfx#425.

**Comment by AGulev** [comment] 2023-07-21 19:28
I've just tested it, and it works fine in the latest (1.4.8) editor

**Comment by beldenfox** [comment] 2023-07-21 20:07
I was able to reproduce the original bug with Defold 1.4.8 and a French keyboard on MacOS Ventura. The JavaFX PR was submitted in May and won't be publicly available until JFX 21 is released in September 2023.

**Comment by AGulev** [comment] 2023-07-21 20:13
@beldenfox we use 21-ea+23

maybe I misunderstand the issue, but when I test it 
- If I switch to AZERTY layout (I tested with french layout) where `A <-> Q` I exit using cmd+A (which is `Q` in AZERTY) and select all using cmd + Q (which is `A` in AZERTY)
- If I switch QWERTY layout (US) `cmd + Q` - exit, `cmd + A` - select all

What am I missing here?

**Comment by beldenfox** [comment] 2023-07-21 20:16
Sorry, I bungled my testing. The bug is fixed.

**Comment by AGulev** [comment] 2023-07-21 20:19
@beldenfox Phew! I thought maybe I misunderstood something. I'm happy to see it works!
Thank you very much for the fix of the issue in JavaFX!!!

**Closed by AGulev** 2023-07-21 20:19 UTC
Labels: bug, editor
