### ISSUE TITLE
I'm not able to open the collection to a sample game.

### ISSUE THREAD

**Issue by jayanthbagare** [defold/defold#4939] opened 2020-06-21 03:11 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-17T10:06:10.495866</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e5389d28eab7bfdc5b8edccad637aadcd2832a29</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4e2240d2448f4a5da899a7016f72b553"'>4e2240d2448f4a5da899a7016f72b553</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 530 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-37-generic</td></tr>
<table>

**Comment by britzl** [comment] 2020-06-21 10:10
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

**Comment by britzl** [comment] 2020-06-21 10:14
Duplicate of #4851

**Closed by britzl** 2020-06-21 10:14 UTC
Labels: editor, linux, opengl
