### ISSUE TITLE
Don't create component worlds if there are no components

### ISSUE THREAD

**Issue by mathiaswking** [defold/defold#4128] opened 2019-06-03 08:04 UTC
Since we create all component worlds for each collection, and each world can preallocate a predetermined amount of memory, it may become very wasteful.

We should make sure to avoid such cases.

Also take into account the game object factories.
Preferably, the worlds won't be created at all.
This most likely requires additional data in the collection header.

**Comment by britzl** [comment] 2021-06-20 08:37
Duplicate of #5843

**Closed by britzl** 2021-06-20 08:37 UTC
Labels: engine, feature request
