### ISSUE TITLE
Some forms doesn't use the available window width

### ISSUE THREAD

**Issue by JCash** [defold/defold#7942] opened 2023-09-01 10:37 UTC
The text is unnecessarily compressed/obfuscated which hinders readability.
E.g. there is no reason for a scrollbar in this case.

<img width="1164" alt="Screenshot 2023-09-01 at 12 33 46" src="https://github.com/defold/defold/assets/1349334/6bb3a35a-e2d9-4c02-a9a4-7a0a29924f7c">

**Comment by AGulev** [comment] 2024-03-09 09:48
duplicate of https://github.com/defold/defold/issues/7622

**Closed by AGulev** 2024-03-09 09:48 UTC
Labels: bug, editor
