### ISSUE TITLE
Mipmapping switches very visibly when scaling. (DEF-1281)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3813] opened 2019-05-23 10:49 UTC
Open the project: Beached Buddies.

On first screen look at water on the top right side.

**Comment by Jhonnyg** [comment] 2024-05-08 16:21
There's not enough info to understand what the issue is. What exactly is "beached buddies" anyway? Closing.

**Closed by Jhonnyg** 2024-05-08 16:21 UTC
Labels: bug, engine, render, 3d
