### ISSUE TITLE
Error loading main.collection

### ISSUE THREAD

**Issue by jgedri** [defold/defold#6063] opened 2021-09-21 18:33 UTC
### Expected behaviour
The `main.collection` file should load.

### Actual behaviour
The file fails to load, throwing an error.

`java.lang.ClassCastException: Unknown`
### Steps to reproduce
Create a mobile game project.
Double click on `main/main.collection`.
<hr/>

<table>
<tr><td>Build time</td><td>2021-09-20T09:08:33.459678</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>03b14982258f69eb8a06d28810ae879e16bd63d7</td></tr>
<tr><td>Defold engine sha</td><td>581c6439ae93755a8a6bcf58732c39c724fa193c</td></tr>
<tr><td>Defold version</td><td>1.2.187</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"14d819fb17684889ae47566876f7d97e"'>14d819fb17684889ae47566876f7d97e</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 610 (WHL GT1)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-34-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-09-21 21:06
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:191)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1370)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1370)
    at editor.app_view$open_resource$fn.invoke(app_view.clj:1600)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment] 2021-09-21 21:07
Please try this workaround: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:14
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:14 UTC
Labels: bug, more info, editor, linux
