### ISSUE TITLE
sprite.play_flipbook behaviour in collection proxies

### ISSUE THREAD

**Issue by alesis** [defold/defold#5625] opened 2021-03-07 00:35 UTC
**Bug Description**
When calling sprite.play_flipbook or msg.post(<url>, "play_animation", <animation>), where the game object is in a different collection loaded via a collection proxy (in other words, the socket part of the url is from a different "world"), an error 
`ERROR:GAMESYS: Could not send animation_done to instance: *`
is raised, but the expected animation change still happens.

**To Reproduce**
1. Create 2 collections (A and B) with a sprite in collection A
2. Load them using collection proxies
3. Have a scrip in collection B that calls `sprite.play_flipbook` on a sprite in collection A

**Expected behavior**
Either the response (the `animation_done` message) should be sent to the correct game object, or the behaviour should be prevented altogether (personally, I'd prefer the first outcome, but designers of the system will know best).

**Defold version:**
  - Version 1.2.179

**Workaround:**
Possible workaround is to send a message to a script in collection A which then calls the `sprite.play_flipbook`.

**Comment by britzl** [comment] 2021-08-20 10:35
@alesis I am unable to reproduce this issue. Could you please compare this sample project with your scenario and see if I misinterpreted the steps to reproduce?

[Archive.zip](https://github.com/defold/defold/files/7020907/Archive.zip)

**Comment by britzl** [comment] 2021-08-24 14:29
I've talked with the user on Discord and we agreed to close the issue until a sample project can be created where this issue happens.

**Closed by britzl** 2021-08-24 14:29 UTC
Labels: bug, more info, engine, sprite
