### ISSUE TITLE
Zooming in Editor

### ISSUE THREAD

**Issue by Alfagun74** [defold/defold#5102] opened 2020-08-17 18:31 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
I'm always frustrated when i cant zoom in the inbuild code editor like in vscode with CTRL + MOUSEWHEEL

**Describe the solution you'd like (REQUIRED):**
Implement a zooming shortcut so i can zoom in and out of code.

**Describe alternatives you've considered (REQUIRED):**
Maybe an Editor-Setting.

**Comment by britzl** [comment] 2020-08-17 21:39
You can change font size using cmd/ctrl and +/-

**Comment by Alfagun74** [comment] 2020-08-18 15:49
CTRL + Minus works but CTRL + Plus doesn't work on a german QUERTZ layouted keyboard.

And i still request the mouse thingy because you dont have to move your hand away then. :)

**Comment by britzl** [comment] 2020-08-18 17:02
> doesn't work on a german QUERTZ layouted keyboard

We're going to look into this quite soon. We have some ideas how to solve this. Thanks.

**Comment by arvie9** [comment] 2023-08-13 07:26
> 

Could someone please provide steps how to reset the editor text size? I got to the smallest size on my Mac (CMD + minus), and using CMD + plus doesn't work to increase it. Someone mentioned using buttons in the context menu... as a first time Defold user, I'm having a hard time finding it anywhere. Please help! I uninstalled and reinstalled the program already but the font size stayed super small. Thanks in advance :)

**Comment by britzl** [comment] 2023-08-13 07:42
Duplicate of #4842 and #5047

**Closed by britzl** 2023-08-13 07:42 UTC
Labels: feature request, editor, text-editor
