### ISSUE TITLE
Horizontal scrollbar shouldn't cover last line of Console Output

### ISSUE THREAD

**Issue by paweljarosz** [defold/defold#9525] opened 2024-10-02 19:42 UTC
**Task (REQUIRED):**
There is a problem when a horizontal scrollbar appears and covers a last line in Console output that has a clickable link. It is then very inconvenient to click on it.

![image](https://github.com/user-attachments/assets/8a458607-3c4e-4aad-9947-f1a3d73dac5f)

**Expected outcome (REQUIRED):**
Perhaps a separate space for horizontal scrollbar should be separated from console output?

**Comment by AGulev** [comment] 2024-10-02 19:49
Duplicate of https://github.com/defold/defold/issues/9257

**Closed** 2024-10-07 07:13 UTC
Labels: task

**Comment by AGulev** [comment] 2024-10-07 08:02
Fixed https://github.com/defold/defold/pull/9559
