### ISSUE TITLE
Allow bob to build remote engine asynchronously

### ISSUE THREAD

**Issue by JCash** [defold/defold#6930] opened 2022-09-01 07:59 UTC
We should start the remote build job on a separate thread, and then check for the result at the end of the content build.

A little bit related to:
https://github.com/defold/defold/issues/3953

**Comment by AGulev** [comment] 2022-09-01 08:05
https://github.com/defold/defold/issues/6897

**Comment by britzl** [comment] 2022-12-02 19:31
Duplicate of https://github.com/defold/defold/issues/6897

**Closed by britzl** 2022-12-02 19:31 UTC
Labels: task, bob
