### ISSUE TITLE
Auto-sized gui node is not rendered if size is set to 0 in gui

### ISSUE THREAD

**Issue by britzl** [defold/defold#7232] opened 2022-12-20 08:16 UTC
**Describe the bug (REQUIRED)**
If a gui node is set to auto-size but the size is stored as 0 (or not specified at all) in the gui scene the node will not render. If on the other hand the size is stored as any non-zero area (for example 1x1 pixels), the node will render with the actual size.

This behavior is even seen on gui node types that do not allow the user to specify the size, such as particlefx and spine nodes. Unless `size = [1 1 0 0]` is written to the compiled binaries, the nodes will not render.

**To Reproduce (REQUIRED)**
1. Create a gui
2. Create a node
3. Assign a texture to the node
4. Set size mode to Auto
5. Modify the .gui file in a text editor and set the size to 0

**Expected behavior (REQUIRED)**
The auto size mode should be respected at all times, regardless of what size is set in the .gui file

**Defold version (REQUIRED):**
  - Version 1.4.1

**Platforms (REQUIRED):**
 - Platforms: All

**Comment by Jhonnyg** [comment] 2022-12-29 11:17
I couldn't reproduce this issue, here's my test project:

[issue-7232-auto-size-gui-node.zip](https://github.com/defold/defold/files/10319110/issue-7232-auto-size-gui-node.zip)

Any further info about this? Or if the reporter has a repro already please add it to this ticket!

**Comment by britzl** [comment] 2022-12-29 14:56
> Any further info about this? Or if the reporter has a repro already please add it to this ticket

I think it was @matgis who came across this while testing something else.

**Comment by matgis** [comment] 2022-12-29 16:42
I'm not able to reproduce the issue anymore either. I'm going to close the issue for now.

**Closed by matgis** 2022-12-29 16:42 UTC
Labels: bug, gui

**Comment by matgis** [comment] 2022-12-30 08:00
I was able to reproduce the issue on Spine scenes at least, so I made an issue in `extension-spine` for it: https://github.com/defold/extension-spine/issues/112
