### ISSUE TITLE
I got this error when I changed the version of the game

### ISSUE THREAD

**Issue by hamidrezakhaki** [defold/defold#6565] opened 2022-04-30 09:01 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-04-21T12:53:01.210447</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9df2b26c5a6ce8e23b0294d2fecd671f7326c108</td></tr>
<tr><td>Defold engine sha</td><td>06bc078e490fd7d94ec01e38abac989f6cc351a5</td></tr>
<tr><td>Defold version</td><td>1.3.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"06e911014d7d49f5910c178d32a5368b"'>06e911014d7d49f5910c178d32a5368b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) RX Vega 11 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.14761 Compatibility Profile Context 21.30.14 30.0.13014.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-05-02 06:50
```
clojure.core$_cache_protocol_fn.invokeStatic.class java.lang.IllegalArgumentException: No implementation of method: :produce-value of protocol: #'internal.graph.types/Evaluation found for class: nil
    at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
    at internal.graph.types$fn$G__4173__4187.invoke(types.clj:28)
    at internal.node$node_value.invokeStatic(node.clj:427)
    at internal.system$node_value.invokeStatic(system.clj:355)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:809)
    at dynamo.graph$node_value.invokeStatic(graph.clj:812)
    at editor.cljfx_form_view$create_renderer$fn.invoke(cljfx_form_view.clj:1360)
    at cljfx.event_handler$wrap_co_effects$fn$fn.invoke(event_handler.clj:11)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at cljfx.event_handler$wrap_co_effects$fn.invoke(event_handler.clj:10)
```

**Comment by AGulev** [comment] 2024-09-19 09:10
There is not enough information to fix the issue, and we are unable to reproduce it. 
We are closing the issue for now, as it cannot be resolved without further context.

Feel free to reopen the issue when you can provide additional information along with reproduction steps.

**Closed by AGulev** 2024-09-19 09:10 UTC
Labels: bug, editor
