### ISSUE TITLE
The timer delta time is bigger then expected

### ISSUE THREAD

**Issue by Insality** [defold/defold#8672] opened 2024-03-13 09:55 UTC
**Describe the bug (REQUIRED)**
In `timer.delay` function signature is `function(self, handle_id, delta_time)`, but I can't rely on this delta_time since it often is bigger than expected

**To Reproduce (REQUIRED)**
1. Open the example project

or code from this example:

```lua
function init(self)
	timer.delay(1, false, function()
	        -- Start measuring here
		local time_start = socket.gettime()
	
		local current_time = time_start
		local timer_time_elapsed = 0
		timer.delay(1/60, true, function(_, _, timer_dt)
			local previous_time = current_time
			current_time = socket.gettime()
			local gettime_dt = current_time - previous_time
			
			timer_time_elapsed = timer_time_elapsed + timer_dt
			print("---")
			print("Timer time dt", timer_dt)
			print("Gettime dt", gettime_dt)
			print("Timer time elapsed", timer_time_elapsed)
			print("Socket time elapsed", current_time - time_start)
		end)
	end)
end
```

Output:
```
Timer time dt	0.031622618436813
Gettime dt	0.016885995864868
Timer time elapsed	33.312931153923
Socket time elapsed	20.014883995056
```

Timer delta time from the time callback is bigger and overall time is not stable

**Expected behavior (REQUIRED)**
Timer delta time is correct

**Defold version (REQUIRED):**
Tested on 1.7.0

**Platforms (REQUIRED):**
Tested on MacOS

**Minimal repro case project (OPTIONAL):**
[timer-dt-test.zip](https://github.com/defold/defold/files/14585773/timer-dt-test.zip)

**Logs (OPTIONAL):**
```
DEBUG:SCRIPT: ---
DEBUG:SCRIPT: Timer time dt	0.029549965634942
DEBUG:SCRIPT: Gettime dt	0.016860008239746
DEBUG:SCRIPT: Timer time elapsed	1.1929103396833
DEBUG:SCRIPT: Socket time elapsed	0.67956805229187
DEBUG:SCRIPT: ---
DEBUG:SCRIPT: Timer time dt	0.029515298083425
DEBUG:SCRIPT: Gettime dt	0.016637086868286
DEBUG:SCRIPT: Timer time elapsed	1.2224256377667
DEBUG:SCRIPT: Socket time elapsed	0.69620513916016
DEBUG:SCRIPT: ---
DEBUG:SCRIPT: Timer time dt	0.029732629656792
DEBUG:SCRIPT: Gettime dt	0.016880035400391
DEBUG:SCRIPT: Timer time elapsed	1.2521582674235
DEBUG:SCRIPT: Socket time elapsed	0.71308517456055
```

**Workaround (OPTIONAL):**
Using `socket.gettime` seems returns more accurate values

**Comment by BlackMATov** [comment] 2024-04-11 12:05
In my case, it was significantly less than expected. Especially if I used a delay close to or higher than the actual frame rate.
And yes, the problem is fixed by using "socket.gettime", also I use a delay of 0 to update all of my stuff every frame.

Defold 1.7.0
Windows 11

**Comment by Insality** [comment] 2024-11-26 18:56
but well, if I want to count the time with DT, it should be possible?

Like
```lua
local time = 0
timer.delay(1, true, function(_, _, dt)
  time = time + dt
end)
```

And I expected the sync with the time of this value

**Comment by AGulev** [comment] 2024-11-26 19:04
No, you can't count like this.

I don’t know why you expect it, or why you’re using `dt` as the variable name here. It’s `time_elapsed`, not `dt`: https://defold.com/ref/timer/#timer.delay:delay-repeating-callback
> time_elapsed
number
The elapsed time - on first trigger it is time since timer.delay call, otherwise time since last trigger

**Comment by AGulev** [comment] 2024-11-26 19:29
Let me try to explain it another way:
1. we have timer we run once a second
2. game runs 9 fps = 1/ 9 = 0.11s
3. so callback fires 0.11*10 = 1.1s - this is`time_elapsed`
4. next time it fires after 9 frames because 0.1s left from prev. time + 9 *0.11 = 0.99s  and `time_elapsed` is 0.99 + 0.1 = 1.09s 

ans so on. 
it will be 
1.1
1.09
1.08
1.07
1.06
you can calculate yourself, but you'll never get 10 after 10s. Because it's not `dt` it is `time elampsed`. It can't be used as `dt`

**Comment by AGulev** [comment] 2024-11-26 21:12
> Let me try to explain it another way:
> 
> 1. we have timer we run once a second
> 2. game runs 9 fps = 1/ 9 = 0.11s
> 3. so callback fires 0.11*10 = 1.1s - this is`time_elapsed` (because 9 frame isn't enough - 0.99s)
> 4. next time it fires after 9 frames because 0.1s left from prev. time + 9 *0.11 = 0.99s  and `time_elapsed` is 0.99 + 0.1 = 1.09s
> 
> ans so on. it will be 1.1 1.09 1.08 1.07 1.06

Now I'm reading my own explanation, and it seems like on step 4 time included from prev. time should be taken into account when calculating for callback but subtracted when calculating time_elapsed

**Comment by AGulev** [comment] 2024-11-27 06:48
ok, I explained the code logic so well, that I found where is mistake in the logic 

I think I have a fix for the issue:

>DEBUG:SCRIPT: Timer time elapsed	70.201401965693
DEBUG:SCRIPT: Socket time elapsed	70.200200796127

**Comment by Insality** [comment] 2024-11-27 07:54
amazing!

**Closed** 2024-11-27 14:54 UTC
Labels: bug, engine, dt, timer

**Comment by Insality** [comment] 2024-11-27 18:28
yeah! superb, so now timer tracks the game time with more precision then system time?

**Comment by Insality** [comment] 2024-11-27 18:28
Thanks!

**Comment by AGulev** [comment] 2024-11-27 18:30
> yeah! superb, so now timer tracks the game time with more precision then system time?

It uses `dt` inside. All the calculations are based on `dt`.
