### ISSUE TITLE
Open GL Linux issue

### ISSUE THREAD

**Issue by xxxKfkxxx** [defold/defold#4866] opened 2020-05-31 08:40 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-05-31T07:49:01.074147</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c5b4b2e62b3147e6ddb7c120d38c764374fef741</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"87ac87cbd84543c88984c2390c898a8b"'>87ac87cbd84543c88984c2390c898a8b</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-28-generic</td></tr>
<table>

**Comment by JCash** [comment] 2020-06-01 06:10
Hi!
This error seems to be OpenGL related.
Could you try any of these tips to see if it works you you?
https://defold.com/faq/faq/#linux

**Comment by britzl** [comment] 2020-10-20 06:44
Probably duplicate of #4851

**Closed by britzl** 2020-10-20 06:44 UTC
Labels: editor, linux, more info, opengl
