### ISSUE TITLE
Error builtins/builtins.zip (No such file or directory)

### ISSUE THREAD

**Issue by bookwrym** [defold/defold#8153] opened 2023-10-16 17:09 UTC
### Expected behaviour
create a font file
### Actual behaviour
error message 
### Steps to reproduce
create file name gui. add font to it. error message should apear.
<hr/>

<table>
<tr><td>Build time</td><td>2023-10-11T08:54:09.551782</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7e5c022ee89d625257f3e22797f49b51d60ba2ef</td></tr>
<tr><td>Defold engine sha</td><td>d9e9c49ab946c058f29a8b688c862d70f30e9c43</td></tr>
<tr><td>Defold version</td><td>1.6.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"344bb7e2245e4dee854a680af7b3318f"'>344bb7e2245e4dee854a680af7b3318f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 645</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-18.8.5</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.6</td></tr>
<table>

**Comment by britzl** [comment] 2023-10-18 12:22
```
java.io.FileInputStream.open0.class java.io.FileNotFoundException: /var/folders/yk/l3_3g8nn40j741xysr1cl7mr0000gn/T/defold-unpack-7e5c022ee89d625257f3e22797f49b51d60ba2ef15486219158161687860/builtins/builtins.zip (No such file or directory)
    at java.io.FileInputStream.open0(FileInputStream.java)
    at java.io.FileInputStream.open(FileInputStream.java:216)
    at java.io.FileInputStream.<init>(FileInputStream.java:157)
    at clojure.java.io$fn.invokeStatic(io.clj:229)
    at clojure.java.io$fn.invoke(io.clj:229)
    at clojure.java.io$fn$G__11372__11386.invoke(io.clj:69)
    at clojure.java.io$input_stream.invokeStatic(io.clj:136)
    at clojure.java.io$input_stream.doInvoke(io.clj:121)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at editor.resource$load_zip.invokeStatic(resource.clj:332)
    at editor.resource$load_zip_resources.invokeStatic(resource.clj:352)
    at editor.resource$load_zip_resources.invoke(resource.clj:352)
    at editor.resource$load_zip_resources.invokeStatic(resource.clj:354)
    at editor.resource_watch$make_builtins_snapshot.invokeStatic(resource_watch.clj:93)
    at editor.resource_watch$make_snapshot_info.invokeStatic(resource_watch.clj:184)
    at editor.workspace$make_snapshot_info.invokeStatic(workspace.clj:454)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:662)
    at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:662)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:666)
    at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:662)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:664)
    at editor.asset_browser$fn$fnk106092_positional__106101.invoke(asset_browser.clj:477)
    at editor.asset_browser$fn$fnk106092__106123$fn.invoke(asset_browser.clj:457)
    at editor.asset_browser$fn$fnk106092__106123.invoke(asset_browser.clj:457)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1192)
    at editor.ui$execute_command.invokeStatic(ui.clj:1200)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1231)
    at editor.ui.MenuEventHandler.handle(ui.clj:1273)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3984)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1890)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by britzl** [comment] 2023-10-18 12:23
@bookwrym did you have Defold open for a long time when it happened?

**Comment by AGulev** [comment] 2024-03-09 14:04
more info wasnt' provided 
It seems like duplicate of https://github.com/defold/defold/issues/7709

**Closed by AGulev** 2024-03-09 14:04 UTC
Labels: bug, more info, editor
