### ISSUE TITLE
Collapse and expand function

### ISSUE THREAD

**Issue by ainonovo** [defold/defold#7730] opened 2023-06-10 18:23 UTC
please make it possible to collapse and expand the internal code in function in the editor

I have a lot of lines and it's not very convenient to scroll through

**Comment by AGulev** [comment] 2024-03-09 09:39
duplicate of https://github.com/defold/defold/issues/6207

**Closed by AGulev** 2024-03-09 09:39 UTC
Labels: feature request, editor, text-editor

**Comment by ainonovo** [comment] 2024-03-09 13:58
Так вы сделаете или нет? очень бы хотелось. много строк. неудобно скролить

**Comment by AGulev** [comment] 2024-03-09 14:00
> Так вы сделаете или нет? очень бы хотелось. много строк. неудобно скролить

It's not planned at the moment.
But having a few issues about the same do not help here

**Comment by ainonovo** [comment] 2024-03-09 14:02
very bad (
