### ISSUE TITLE
Need access to atlas / tilesource path

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#8050] opened 2023-09-27 02:02 UTC
In the below snippet, I can retrieve the atlas info with no issue.
```lua
go.property( "path", resource.atlas("/game/level_select/worldmap_sky.atlas"))

local ts_info = resource.get_atlas(path)
local ts_tex_info = resource.get_texture_info(ts_info.texture)
```

What  I would like to do is get access to "path" information by way of gui / go request.
IE: 
```lua
local path = gui.get_texture_path(node)  <-- Would like this to return "/game/level_select/worldmap_sky.atlas" or the correct handle to be used below

local ts_info = resource.get_atlas(path)
local ts_tex_info = resource.get_texture_info(ts_info.texture)
```

**Comment by AGulev** [comment] 2023-09-27 09:10
there is no way to get path but you can get hash(path):

gui_script:
```lua
function init(self)
	self.node = gui.get_node("box")
	local texture = gui.get_texture(self.node)
	msg.post("#script", "get_texture", {name = texture})
end
```

script:
```lua
function on_message(self, message_id, message)
	if message_id == hash("get_texture") then
		local hs = go.get("#gui", "textures", {key = message.name})
		print(hs)
	end
end
```

result:
>DEBUG:SCRIPT: hash: [/main/1.a.texturesetc]

**Comment by Jhonnyg** [comment] 2023-09-27 09:20
With the path hash you can use the functions as intended:
https://defold.com/ref/beta/resource/#resource.get_atlas:path
https://defold.com/ref/beta/resource/#resource.get_texture_info:path

(The texture field in the returned atlas meta data is a hash as well)

**Comment by jcbk101** [comment] 2023-09-27 14:40
Well, I just have to make do with that period LOL. Although the GUI is a little delayed. I can work with it, but the GO function is perfect.


________________________________

**Comment by Jhonnyg** [comment] 2023-09-30 12:12
So we can close this for now then?

**Comment by jcbk101** [comment] 2023-09-30 15:11
Yes, thank you. It all works like a charm.
My last task to have full texture wrapping is understanding the UV data in the structure and converting it to usable data.👍


________________________________

**Closed** 2023-09-30 15:12 UTC
Labels: feature request, engine, gui
