### ISSUE TITLE
dropdown menu autofill in input binding file.

### ISSUE THREAD

**Issue by parsadaj** [defold/defold#8020] opened 2023-09-19 13:39 UTC
**Is it a private platform-specific feature? (i.e. would it break your NDA?)**
No.

**Is your feature request related to a problem? Please describe (REQUIRED):**
When dealing with the input_binding file, there is a dropdown menu where we can choose the button we want to assign to an action (e.g. Space for jump action).
when I open the dropdown, I have to scroll very long to reach my desired input button (e.g. Space).

**Describe the solution you'd like (REQUIRED):**
It would be great if, for example, I hit s on my keyboard when the dropdown is open, it quickly jumps to the first option starting with the letter 's' so I no longer need to scroll down a lot.

**Describe alternatives you've considered (REQUIRED):**
instead of a dropdown, there could be an editable text where we can write our desired input button name, so when we start typing, it suggests only those button names that match the text we have written.

**Additional context (OPTIONAL):**

<img width="681" alt="image" src="https://github.com/defold/defold/assets/53321170/f97bfe57-893f-4add-82ca-25033d9ae71b">

**Comment by AGulev** [comment] 2024-03-09 13:52
closed as duplicate of https://github.com/defold/defold/issues/7737

**Closed by AGulev** 2024-03-09 13:52 UTC
Labels: feature request, editor
