### ISSUE TITLE
a returning error (can't see elements in gui)

### ISSUE THREAD

**Issue by itamarle-ma** [defold/defold#7568] opened 2023-04-13 07:02 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-03-28T10:02:01.837571</td></tr>
<tr><td>Defold channel</td><td>dev</td></tr>
<tr><td>Defold editor sha</td><td>811e07aefa5fb26bb7b10f4ba58bc6b2f7f11c95</td></tr>
<tr><td>Defold engine sha</td><td>811e07aefa5fb26bb7b10f4ba58bc6b2f7f11c95</td></tr>
<tr><td>Defold version</td><td>1.4.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5d4f52c5b89d4e44b3e0fdf8b2a5931c"'>5d4f52c5b89d4e44b3e0fdf8b2a5931c</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.2.1</td></tr>
<table>

**Comment by britzl** [comment] 2023-04-13 07:25
Duplicate of https://github.com/defold/defold/issues/7567

**Closed by britzl** 2023-04-13 07:25 UTC
