### ISSUE TITLE
Empty action name in Gamepad Triggers

### ISSUE THREAD

**Issue by Awasaky** [defold/defold#5225] opened 2020-09-21 19:43 UTC
### Steps to reproduce
Add any action to Input Bindings - Gamepad Triggers.
Don't add any name to action. Just select action name field.
Try to remove trigger, by pressing "-" button.
<hr/>

<table>
<tr><td>Build time</td><td>2020-09-14T07:44:58.278073</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0fc7ca5e7fe9fb66f5d692c4f015b313d875d884</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3b8bb2e4342a4e02a1af27e98b4fc4ab"'>3b8bb2e4342a4e02a1af27e98b4fc4ab</a></td></tr>
<tr><td>GPU</td><td>Radeon (TM) RX 470 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.14736 Compatibility Profile Context 20.9.1 27.20.12029.1000</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Awasaky** [comment] 2020-09-21 19:47
I can't close application after this issue.Only Windows Task Manager and force to close Open JDK Platform binary.

**Comment by britzl** [comment] 2020-12-17 08:00
I'm unable to reproduce this. It would be great to get a log from the editor when this happens: https://defold.com/manuals/editor/#editor-logs

**Comment by britzl** [comment] 2021-06-20 13:19
No new info from user. Closing.

**Closed by britzl** 2021-06-20 13:19 UTC
Labels: bug, editor, more info
