### ISSUE TITLE
Crash on Linux - jogamp.opengl.es1.GLES1Impl

### ISSUE THREAD

**Issue by Danieisacoder** [defold/defold#5780] opened 2021-04-26 23:14 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-04-13T06:40:18.508649</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b004f16e507cef52b6940c6970cbefc0d68722f0</td></tr>
<tr><td>Defold engine sha</td><td>ff5b94e432eb58dabdb8e367bed9acc5e99e129b</td></tr>
<tr><td>Defold version</td><td>1.2.181</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ed87618eab5e4db08102cb252e1e5d9c"'>ed87618eab5e4db08102cb252e1e5d9c</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.0</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.8.0-7642-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-04-27 05:59
```
ClassCastException

gpu | Mesa Intel(R) UHD Graphics (CML GT2)
-- | --
gpu-info | EGLContext [Version 1.1 (ES profile, arb, compat[FP32], hardware) - OpenGL ES-CM 1.1 Mesa 21.0.0 [GL 1.1.0, vendor 21.0.0 (Mesa 21.0.0)], options 0x8009, this 0x128b1b5f, handle 0x7fb2c487ff80, isShared false, jogamp.opengl.es1.GLES1Impl@1894937, 	 quirks: [NoDoubleBufferedPBuffer, NoSetSwapIntervalPostRetarget, GLSharedContextBuggy], 	Drawable: jogamp.opengl.egl.EGLDrawable[realized true, 	factory    jogamp.opengl.egl.EGLDrawableFactory@2fa98c23, 	surface    EGLSurface[ displayHandle 0x7fb27c0014b0 , surfaceHandle 0x7fb2c40c8940 , size 100x100 , UOB[ OWNS_SURFACE ] , EGLGraphicsConfiguration[DefaultGraphicsScreen[EGLGraphicsDevice[type .egl, v1.5.0, connection :1, unitID 0, handle 0x7fb27c0014b0, owner true, ResourceToolkitLock[obj 0x4d390076, isOwner true, <11e0b602, 5aeb95f8>[count 1, qsz 0, owner <JavaFX Application Thread>]]], idx 0], 	eglConfigHandle 0x7fb27c161060, eglConfigID 0x18, 	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/8/0, one, mono  , hw, GLProfile[GLES1/GLES1.hw], offscr[fbo, pbuffer]], 	chosen    GLCaps[egl cfg 0x18, vid 0x21: rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/0, dbl, mono  , hw, GLProfile[GLES1/GLES1.hw], offscr[pbuffer], [0x4d: GL, GLES1, GLES2, GLES3, VG]]] , surfaceLock <39c0c212, 3cff5fec>[count 1, qsz 0, owner <JavaFX Application Thread>] , EGLUpstreamSurfaceHook[ 100x100, jogamp.nativewindow.WrappedSurface: 0x0] , upstreamSurface true ], 	eglSurface 0x7fb2c40c8940, 	eglConfig  EGLGraphicsConfiguration[DefaultGraphicsScreen[EGLGraphicsDevice[type .egl, v1.5.0, connection :1, unitID 0, handle 0x7fb27c0014b0, owner true, ResourceToolkitLock[obj 0x4d390076, isOwner true, <11e0b602, 5aeb95f8>[count 1, qsz 0, owner <JavaFX Application Thread>]]], idx 0], 	eglConfigHandle 0x7fb27c161060, eglConfigID 0x18, 	requested GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/8/0, one, mono  , hw, GLProfile[GLES1/GLES1.hw], offscr[fbo, pbuffer]], 	chosen    GLCaps[egl cfg 0x18, vid 0x21: rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/0, dbl, mono  , hw, GLProfile[GLES1/GLES1.hw], offscr[pbuffer], [0x4d: GL, GLES1, GLES2, GLES3, VG]]], 	requested  GLCaps[rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 16/8/0, one, mono  , hw, GLProfile[GLES1/GLES1.hw], offscr[fbo, pbuffer]], 	chosen     GLCaps[egl cfg 0x18, vid 0x21: rgba 8/8/8/0, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/8/0, dbl, mono  , hw, GLProfile[GLES1/GLES1.hw], offscr[pbuffer], [0x4d: GL, GLES1, GLES2, GLES3, VG]]]]
```

**Comment by britzl** [comment] 2021-04-27 06:00
@Danieisacoder when does this happen? When you open the editor? Or when you open a specific file?

**Comment by consoleaf** [comment] 2021-06-18 09:01
This is probably the same error I'm experiencing:
```
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

It happens whenever I try opening .collection or .atlas files

**Comment by britzl** [comment] 2021-06-18 09:32
@consoleaf please check this FAQ entry: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by consoleaf** [comment] 2021-06-18 09:36
@britzl I just found that switching from hybrid to nvidia profile with optimus-manager resolved the crash. Thank you for your response!

**Comment by britzl** [comment] 2022-05-17 06:14
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:14 UTC
Labels: bug, more info, editor, linux
