### ISSUE TITLE
Color and inherit alpha doesn't work in editor preview

### ISSUE THREAD

**Issue by Jhonnyg** [defold/defold#7745] opened 2023-06-15 12:49 UTC
**Describe the bug (REQUIRED)**

**To Reproduce (REQUIRED)**

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: [e.g. iOS, Android, Windows, macOS, Linux, HTML5]
 - OS: [e.g. iOS8.1, Windows 10, High Sierra]

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
If there is a workaround, please describe it here.

**Screenshots (OPTIONAL):**

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment] 2024-07-19 14:42
I can't reproduce it 
closing for now


https://github.com/user-attachments/assets/baaed7e8-9ad6-475e-8884-dfb986b54abc

**Closed by AGulev** 2024-07-19 14:42 UTC
Labels: bug, editor, gui
