### ISSUE TITLE
GUI err

### ISSUE THREAD

**Issue by KutsDenis** [defold/defold#6426] opened 2022-02-19 16:00 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T08:40:15.071173</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3890e8ff96594366a6a8609b307e9d57"'>3890e8ff96594366a6a8609b307e9d57</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 4400 (HSW GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.3.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.16.8-200.fc35.x86_64</td></tr>
<table>

**Comment by britzl** [comment] 2022-02-21 08:03
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:192)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1501)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1501)
    at editor.app_view$open_resource$fn.invoke(app_view.clj:1731)
    at clojure.lang.AFn.run(AFn.java:22)
```

**Comment by britzl** [comment] 2022-02-21 08:03
Please try this: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:15
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:15 UTC
Labels: editor, linux
