### ISSUE TITLE
java.lang.ClassCastException: class internal.graph.error_values.ErrorValue cannot be cast to class clojure.lang.IFn (internal.graph.error_values.ErrorValue and clojure.lang.IFn are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by gawirable** [defold/defold#7956] opened 2023-09-05 01:45 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-01T18:07:12.838425</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7d70d50c3318fbb27e7bfda80aec37eb3752023d</td></tr>
<tr><td>Defold engine sha</td><td>57b34efdf44a922acc6f21d285b207029b53927d</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"58226044fd7445e6a884252f02d12c1b"'>58226044fd7445e6a884252f02d12c1b</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 528.02</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment] 2023-09-05 10:10
```
clojure.core$comp$fn__5792.invoke.class java.lang.ClassCastException: class internal.graph.error_values.ErrorValue cannot be cast to class clojure.lang.IFn (internal.graph.error_values.ErrorValue and clojure.lang.IFn are in unnamed module of loader 'app')
    at clojure.core$comp$fn.invoke(core.clj:2569)
    at editor.gui$LayoutNode$property$nodes$setter$fn$iter__90329__90335$fn.invoke(gui.clj:1842)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core$concat$cat__5480$fn.invoke(core.clj:734)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:58)
    at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
    at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
    at clojure.lang.RT.next(RT.java:709)
    at clojure.core$next__5371.invokeStatic(core.clj:64)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:811)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$fn.invokeStatic(transaction.clj:374)
    at internal.transaction$fn.invoke(transaction.clj:348)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:814)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:570)
    at internal.transaction$fn.invokeStatic(transaction.clj:623)
    at internal.transaction$fn.invoke(transaction.clj:611)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:814)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:812)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:811)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:811)
    at internal.transaction$apply_tx.invoke(transaction.clj:804)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:811)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:895)
    at dynamo.graph$transact.invokeStatic(graph.clj:164)
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:204)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:555)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:660)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:849)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:741)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:731)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:89)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by vlaaad** [comment] 2023-09-05 10:12
It seems `(g/node-value node-tree :node-ids evaluation-context)` in [gui.clj on line 1832](https://github.com/defold/defold/blob/5dbb1862d7fbd6096317d904651525cf8a938c0e/editor/src/clj/editor/gui.clj#L1831) returns error value

**Comment by Khepu** [comment] 2024-06-03 12:19
Hello! I was thinking of helping out here but I lack a sense of direction. Is the issue that an error value is produced in the first place or that it lacks explicit handling for it? If it's the latter, are there other examples in the codebase that do that?

**Comment by matgis** [comment] 2024-06-03 15:03
To me at least, it looks strange that there would be an error from this output. It would be helpful to know what the error was and how it can occur. Do we have a repro case? Since it happens during loading, I'm not sure we can gracefully handle it at this stage.

Be aware that the Gui code is rather complex and involves hairy concepts such as [Overrides](https://github.com/defold/defold/blob/dev/editor/src/clj/internal/graph.clj#L28). You might not want to start here if you're thinking of helping out. 😅

**Comment by vlaaad** [comment] 2024-06-03 18:05
Yeah, this issue needs a repro case... @Khepu if you are considering contributing to the editor, I'd recommend looking into [editor issues labeled `good first issue?` and `quick win?`](https://github.com/defold/defold/issues?q=is%3Aopen+is%3Aissue+label%3Aeditor+label%3A%22good+first+issue%3F%22%2C%22quick+win%3F%22). Note the question marks on labels... they mean the issues *might* be quick and easy :D

**Comment by vlaaad** [comment] 2024-06-03 18:16
Also, this issue seems to be a duplicate of #8437 (or the other way around), and it has repro steps.

**Comment by AGulev** [comment] 2024-09-19 08:29
fixed in https://github.com/defold/defold/pull/9139

**Closed by AGulev** 2024-09-19 08:29 UTC
Labels: bug, editor
