### ISSUE TITLE
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by Alios5** [defold/defold#6180] opened 2021-11-13 18:34 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-11-11T08:44:01.408445</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>078c2efa0f1b64f13763dd1fcc06d8bc6aeff8ad</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b7b26bb8e6fe4c03aee3c88ca9e5d356"'>b7b26bb8e6fe4c03aee3c88ca9e5d356</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 520 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-90-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-11-14 10:47
Please give this a try: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:14
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:14 UTC
Labels: editor, linux
