### ISSUE TITLE
Creating an atlas file triggers my anti-virus and shuts down my computer.

### ISSUE THREAD

**Issue by OPSPESH** [defold/defold#9035] opened 2024-06-05 13:24 UTC
**Describe the bug (REQUIRED)**
I started working on a game at home then decided to start working on it at my school so i asked if they could install it and they did but when i download the file from github (which is how i got it from my laptop at home to the school computer) it wouldnt let me unpack any of the atlas files from the zip file (it said it needed permissions so i just had to skip it) then when i tryed to create the atlas file in defold it gave me an error which at the end said something about file not found then like i said a popup apears saying a virus has been detected and then it shuts off the computer. 

**To Reproduce (REQUIRED)**
im not sure what to put hear as im not sure what the IT staff has done to the systems but i guess it could be.
1) install sophos anti-virus 
2) create an atlas file
3) see what happens

**Expected behavior (REQUIRED)**
create an atlas file

**Defold version (REQUIRED):**
  - v 1.8.1

**Platforms (REQUIRED):**
 - OS windows 10

**Additional context (OPTIONAL):**
sorry about the lack of useful clues i dont have access to where defold is installed or access to the logs or more info about the computer.

**Comment by britzl** [comment] 2024-06-06 07:35
Thank you for the bug report. I don't really know what we can do to cater to all kinds of strange behaviour caused by anti-virus software. If you can suggest some action we can take to improve the situation then please let us know. Closing this for now.

**Closed by britzl** 2024-06-06 07:35 UTC
Labels: bug

**Comment by OPSPESH** [comment] 2024-06-11 15:03
hi britzl i know youve closed this but ive manged to get the error i just wondered if it would help
clojure.lang.ExceptionInfo: handler ':new-file' in context ':global' failed at ':run' with message '\\curriculum.cvhs\students\Student Home\2020\20OParr\My Documents\Desktop game\assets\guy.atlas (Access is denied)'
java.io.FileNotFoundException: \\curriculum.cvhs\students\Student Home\2020\20OParr\My Documents\Desktop game\assets\guy.atlas (Access is denied)

**Comment by OPSPESH** [comment] 2024-06-12 08:24
I will ask. one of the teachers yesterday suggested getting a stand alone device so ill ask and see what they say.

**Comment by OPSPESH** [comment] 2024-06-12 11:22
ive told my teacher what youve said and they said they will pass it on to the IT people
