### ISSUE TITLE
Default animation for several 2D samplers

### ISSUE THREAD

**Issue by nanaktaev** [defold/defold#9239] opened 2024-07-29 11:06 UTC
![image](https://github.com/user-attachments/assets/67295dde-b068-4639-8fa6-2e0bc5ae7836)

Hi! Currently it's impossible to specify default animation separately for every Sampler2D of the sprite.
It would be nice if it will be possible to set if for every Sampler2D OR at least if the default animation would be 0 or 1 for additional samplers.

I've encountered this limitation during experimentation with render targets.
I render some data to overlay texture target and use this overlay to render my sprites. 

![image](https://github.com/user-attachments/assets/cc6b8ffc-0564-413a-98d3-14965ea193b0)

My current workaround is to set the same texture with same default animation in editor (since overlay texture is anyway overwritten in render script) but this leaves editor preview of the sprite all black.

**Comment by AGulev** [comment] 2024-07-29 11:14
duplicate of https://github.com/defold/defold/issues/8609

**Closed** 2024-08-05 07:10 UTC
Labels: feature request, engine, editor, sprite
