### ISSUE TITLE
Define custom anchor points within an atlas for sprite pairs

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5172] opened 2020-09-07 04:30 UTC
Like with tilemaps, could have some extra data for atlases. One could be custom anchor points for pivoting. This would allow artists to set one or more anchor point of an image directly in an atlas and either have the option of having the anchor point be the default pivot, or as an option in the dropdown or at least able to be set in code.

A use for this is having a large gallery of creatures where you want to swap between them. Without this, you have to either save in code position offsets, or setup premade nodes with the right positions set.

**Comment by zendorx** [comment] 2024-02-12 14:40
Also sprite pivots need for frame animations for sprites with different sizes

**Comment by AGulev** [comment] 2024-05-03 21:21
closed as duplicate of https://github.com/defold/defold/issues/3666

**Closed by AGulev** 2024-05-03 21:21 UTC
Labels: feature request, engine, editor, sprite
