### ISSUE TITLE
Editor window hide unexpectedly

### ISSUE THREAD

**Issue by trinhccao** [defold/defold#9009] opened 2024-05-31 06:18 UTC
**Describe the bug (REQUIRED)**
Use/save a custom color for GUI box will bring the editor window back behind other app unexpected way.

**To Reproduce (REQUIRED)**
1. Open any app that take full screen space
2. Open Defold editor
3. In the properties pane of a GUI box,  click on `Color` field to show the color palette popup
4. Choose "Custom Color..."
5. Choose `Save` or `Use` button
6. The Defold editor will hide behind the previous opened app

**Expected behavior (REQUIRED)**
The editor close the "Custom Colors" popup without hiding editor

**Defold version (REQUIRED):**
  - Version 1.8.1

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 11

**Minimal repro case project (OPTIONAL):**
[Example.zip](https://github.com/user-attachments/files/15508988/Example.zip)

**Logs (OPTIONAL):**

**Workaround (OPTIONAL):**

**Screenshots (OPTIONAL):**
https://github.com/defold/defold/assets/53936904/27f4f02c-05a4-4d48-9899-25555ab13056

**Additional context (OPTIONAL):**

**Comment by britzl** [comment] 2024-05-31 06:51
Duplicate of https://github.com/defold/defold/issues/7554

**Closed by britzl** 2024-05-31 06:51 UTC
Labels: bug
