### ISSUE TITLE
Profiler doesn't show anything if `update_frequency` isn't zero

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7212] opened 2022-12-07 23:49 UTC
**Describe the bug (REQUIRED)**
Profiler doesn't show anything if `display.update_frequency` has some non-zero value.

**To Reproduce (REQUIRED)**
1. Go to `game.project`
2. Click `Display`
3. Set `Update Frequency` to `0`. The value of `Vsync` doesn't matter.
4. Add `profiler.enable_ui(true)` to your main script.
5. Run the game.

**Expected behavior (REQUIRED)**
How the window should look:
![image](https://user-images.githubusercontent.com/193258/206321374-0f07afd8-0c06-43dc-8d63-4834b0001cdc.png)

**Defold version (REQUIRED):**
  - Version: 1.2.140, 1.2.141 BETA

**Platforms (REQUIRED):**
 - OS: Windows 10 x64

**Screenshots (OPTIONAL):**

https://user-images.githubusercontent.com/193258/206321289-23d10baa-5a4a-4ed5-852c-a8d3e3349d4d.mp4

**Comment by AGulev** [comment] 2023-07-12 15:48
Duplicate of https://github.com/defold/defold/issues/7017

**Closed by AGulev** 2023-07-12 15:48 UTC
Labels: bug, profiler
