### ISSUE TITLE
Everytime i resize the window, trigger this error:

### ISSUE THREAD

**Issue by laurofilho96** [defold/defold#6114] opened 2021-10-20 02:39 UTC
### Expected behaviour
Resize Defold Window commonly
### Actual behaviour
triggers this error:

om.jogamp.opengl.GLException: JavaFX Application Thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.hw], current: 3.0 (Compat profile, compat[ES2], FBO, hardware) - 3.0 Mesa 21.0.3
### Steps to reproduce

simply resize the program window
<hr/>

<table>
<tr><td>Build time</td><td>2021-10-18T16:55:06.929094</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>055196fdf29694c06a1000e26217167ac249ba3f</td></tr>
<tr><td>Defold engine sha</td><td>6bfeea3b13d7b8920483ea2cba9c181a8650b84d</td></tr>
<tr><td>Defold version</td><td>1.2.188</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"4ca9a856b5164afba63d54e9816592e3"'>4ca9a856b5164afba63d54e9816592e3</a></td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-37-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-10-20 06:46
Does everything else work, like opening collections, previewing particle effects etc?

**Comment by britzl** [comment] 2022-12-02 19:46
Duplicate of https://github.com/defold/defold/issues/6053

**Closed by britzl** 2022-12-02 19:46 UTC
Labels: more info, editor, linux
