### ISSUE TITLE
NullPointerException while closing a game object open in the editor

### ISSUE THREAD

**Issue by imor** [defold/defold#4994] opened 2020-07-08 14:50 UTC
### Expected behaviour
No NullPointerException

### Actual behaviour
A NullPointerException occurs

### Steps to reproduce
1. With a game object open in the editor, open the _eye menu_ (the one with the Visibility Filters, Collision Shapes options)
2. Click on the close button on the opened game object.

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-29T13:41:32.698594</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>59d19a981dba32421a462d108158f1e33cdfe694</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"48031dae7aad4217a25f7f539cc441e3"'>48031dae7aad4217a25f7f539cc441e3</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.8336</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-07-08 21:24
javafx.scene.control.skin.TabPaneSkin in stopDrag at line 2216

**Comment by britzl** [comment] 2020-07-08 21:25
Duplicate of #4852

**Closed by britzl** 2020-07-08 21:25 UTC
Labels: editor, javafx
