### ISSUE TITLE
sys.load_resource() not working if file has no extension and running from Editor in MacOSX

### ISSUE THREAD

**Issue by piXelicidio** [defold/defold#5067] opened 2020-08-02 02:51 UTC
### Expected behaviour
Load the resource file the same it does on windows or when bundled.
### Actual behaviour
sys.load_resource() Returns nil. Only happens on Mac when running the project from the editor and the file has no extension. It works if file has extension or without extension and bundled for Windows, Mac, iOS and Andriod.

### Steps to reproduce
- Create a folder in project root: 'res'
- Copy any text file there named: 'data'
- Set Custom Resources on Game.project to: '/res'
- On any script call: local s = sys.load_resource('/res/data')
- returned string s is nil if editor is running on Mac.

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-25T06:13:46.107709</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a64a72ca0d10f1583edab5b4317499cdc8c64e5</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 6000</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.7.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.6</td></tr>
<table>

**Comment by piXelicidio** [comment] 2020-08-02 02:55
![image](https://user-images.githubusercontent.com/6601446/89114395-32a06280-d452-11ea-8077-28ff4de45b1d.png)
![image](https://user-images.githubusercontent.com/6601446/89114405-4a77e680-d452-11ea-91c8-1d55ec1ed13e.png)
Minimal Project:
[loadresource.zip](https://github.com/defold/defold/files/5011569/loadresource.zip)

**Comment by piXelicidio** [comment] 2020-08-02 03:11
Just noticed is duplicated of: https://github.com/defold/defold/issues/5040

**Comment by britzl** [comment] 2020-08-02 11:26
Correct, duplicate of #5040. It's planned for 1.2.173.

**Comment by JCash** [comment] 2020-08-14 13:29
This is already fixed and released.

**Closed by JCash** 2020-08-14 13:29 UTC
