### ISSUE TITLE
Add ability to reload resources in more than one dmengine instance (DEFEDIT-682)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4035] opened 2019-05-27 05:39 UTC
Description:
When developing multiplayer games it would be quite handy to be able to reload an asset in multiple device targets. dmengine would have to bind to a dynamic port and in the editor it must be possible to select more than one device target.

Business need:
Indie developers. (LINK REMOVED)

**Comment by AGulev** [comment] 2024-05-26 17:35
closed as duplicate of https://github.com/defold/defold/issues/4075

**Closed by AGulev** 2024-05-26 17:35 UTC
Labels: feature request, editor
