### ISSUE TITLE
Cycle detected on node type editor.game-object/GameObjectNode

### ISSUE THREAD

**Issue by EbmGastroService** [defold/defold#6803] opened 2022-07-16 19:46 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-07-11T09:22:18.167890</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c0ed825ede46b0112d1e4fd744fd50f460073229</td></tr>
<tr><td>Defold engine sha</td><td>80b1b73fd9cdbd4682c2583403fddfbaf0919107</td></tr>
<tr><td>Defold version</td><td>1.3.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c6b835bbd64f41eb9e1ded6d9bacd453"'>c6b835bbd64f41eb9e1ded6d9bacd453</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.5161</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-07-17 06:45
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.game-object/GameObjectNode and output :build-targets
(not (contains? (:in-production evaluation-context) (gt/endpoint node-id label)))
    at internal.node$mark_in_production.invokeStatic(node.clj:1323)
    at editor.game_object$GameObjectNode$behavior$build_targets.invokeStatic(game_object.clj:455)
    at editor.game_object$GameObjectNode$behavior$build_targets.invoke(game_object.clj:455)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1150)
    at editor.factory$FactoryNode$behavior$build_targets$fn.invoke(factory.clj:108)
```

**Comment by britzl** [comment] 2022-07-17 06:47
@EbmGastroService this is a duplicate of https://github.com/defold/defold/issues/6724. You have created a dependency loop where the factory references directly or indirectly itself.

More info here: https://github.com/defold/defold/issues/6724

**Closed by britzl** 2022-07-17 06:47 UTC
Labels: bug, editor
