### ISSUE TITLE
Add ability to intercept or override X / window close

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4836] opened 2020-05-24 21:13 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
In some applications you do not want the program to exit immediately when pressing the X close button on a window, and instead want to present a dialog to the user. This is common with editors but may be useful for situations where the player is hosting a server as well where they do not want to accidentally fully close.

![2020-05-24 14_11_45-Steam](https://user-images.githubusercontent.com/409170/82765089-8ba3a880-9dc8-11ea-97d8-f63df55d250e.png)

**Describe the solution you'd like (REQUIRED):**
Add an ability to create a callback function which if set is called when the X button is pressed to let the application decide when to close.

**Comment by britzl** [comment] 2020-05-24 21:27
I know that we have discussed moving parts of DefOS to main Defold repo, but my gut reaction was, hey, this is something DefOS should support!

**Comment by subsoap** [comment] 2020-05-24 21:51
I think we discussed it with DefOS in the past but because of the way the code works we can't interact with it without breaking things in core Defold. Not 100% on that, may be wrong.

**Comment by britzl** [comment] 2021-06-20 08:57
Duplicate of #5098

**Closed by britzl** 2021-06-20 08:57 UTC
Labels: engine, feature request, linux, macos, task, windows
