### ISSUE TITLE
Drag file to assets folder error

### ISSUE THREAD

**Issue by wangdong20** [defold/defold#6560] opened 2022-04-28 12:38 UTC
### Expected behaviour
File add to assets folder when drag them in.

### Actual behaviour
error happened.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-03-19T08:00:46.134016</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2d5646b4f363ba0c2ad6c1a8e2ba383aecd9bbe</td></tr>
<tr><td>Defold engine sha</td><td>0e77ba11ac957ee01878bbde2e6ac0c9fae6dc01</td></tr>
<tr><td>Defold version</td><td>1.3.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"cf3d725b416340e1830f52888210faac"'>cf3d725b416340e1830f52888210faac</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-18.3.5</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment] 2022-05-02 06:46
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1017)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:276)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1301)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3066)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3135)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by britzl** [comment] 2022-05-04 06:20
Duplicate of https://github.com/defold/defold/issues/5875

**Closed by britzl** 2022-05-04 06:20 UTC
Labels: bug, editor, macos, javafx
