### ISSUE TITLE
Opening atlas in the editor takes too long

### ISSUE THREAD

**Issue by AGulev** [defold/defold#8677] opened 2024-03-15 07:23 UTC
**Describe the bug (REQUIRED)**
The atlas that takes 7.5s (where layout creation is 4.7s) to generate in bob, takes ~21s in the editor (`1.atlas`).
I did expect some overhead, but isn’t it too much?

**To Reproduce (REQUIRED)**
1. Open the `BigAtlases.project`
2. Open `1.atlas` - it takes 20-21s
3. Bundle project with report and take a look how long Atlas building takes, it's about 7.5s
![CleanShot 2024-03-15 at 08 21 19@2x](https://github.com/defold/defold/assets/2209596/df77c2c3-41b5-4329-9a2d-3adbfd1fe846)

**Expected behavior (REQUIRED)**
It shouldn't take 3 times longer than in `bob.jar` taking into account that we use the same code for the layout generation

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Platforms: Mac
 - OS: Mac
 - Device: Macbook Pro M1 Max

**Minimal repro case project (OPTIONAL):**

[BigAtlases.zip](https://github.com/defold/defold/files/14612181/BigAtlases.zip)

**Comment by AGulev** [comment] 2024-03-15 07:29
I think this issue is partially related https://github.com/defold/defold/issues/8463 (it also shouldn’t regenerate layout when user works with animations without doing something that might affect the layout, but it takes strangely long on his video as well)

**Comment by vlaaad** [comment] 2024-04-23 13:43
I cannot reproduce the issue. Opening the view take 5.5 seconds, where most of the time is spent in texture set generation.
<img width="1424" alt="Screenshot 2024-04-23 at 15 42 13" src="https://github.com/defold/defold/assets/732554/e61de3f1-91f2-483a-8031-a1f3e5e97a80">

**Comment by AGulev** [comment] 2024-04-23 13:48
hmm

https://github.com/defold/defold/assets/2209596/dcb7ec16-5c74-4d0e-9c4c-3f0b4b318953

**Comment by AGulev** [comment] 2024-04-23 13:49
![CleanShot 2024-04-23 at 15 49 16@2x](https://github.com/defold/defold/assets/2209596/aecd9bea-4eb5-46aa-af0e-19720eb760cc)

**Comment by vlaaad** [comment] 2024-04-23 13:54
First open for me is longer, can confirm, it also takes around 10 seconds, like for you. I think this is because the code is not JIT-compiled yet. If I remove the editor cache so that it calcs the layout again, subsequent opens are around 5 seconds long. There is also some image IO to calc image sizes on a first open, but it only takes 500ms:

<img width="1287" alt="Screenshot 2024-04-23 at 15 53 20" src="https://github.com/defold/defold/assets/732554/b074174c-0e7b-4c6d-8012-6459376e2b04">

It does not look like there is some bug or perf regression or something like that.

**Comment by AGulev** [comment] 2024-04-23 13:57
this is strange.
Last time I tested (and I tested it like 5 times in a row) it was 20 s +, now it's about 12s which is ~ x2 from bob (but maybe I missed something in bob measurements) but if you don't see anything suspicious - ok

**Comment by vlaaad** [comment] 2024-04-23 14:01
I can't bundle the project due to build errors to compare with bob. Is it possible that, when bundling with bob, some other atlases were built first? In that case, it could trigger JIT compilation of layout generator, making subsequent atlas compilations faster.

**Comment by AGulev** [comment] 2024-04-23 14:03
yes, this project also contains example for https://github.com/defold/defold/issues/8678

**Comment by AGulev** [comment] 2024-04-23 14:44
[Uploading BigAtlases.zip…]()
you can bundle this one

**Comment by vlaaad** [comment] 2024-04-24 08:58
Thanks! I'm trying your latest repro project. Here is bundle time vs editor open tab time (both around 10 seconds):

<img width="1050" alt="Screenshot 2024-04-24 at 10 48 38" src="https://github.com/defold/defold/assets/732554/efb0fa56-f036-4aab-b871-f43fd1309f40">

So far I can't reproduce this issue. I suggest we close it.

**Comment by AGulev** [comment] 2024-04-24 09:00
ok, np

**Closed** 2024-04-24 09:03 UTC
Labels: bug, editor, performance
