### ISSUE TITLE
Having a drop down active such as a Texture selection dropdown of a node open and then clicking to another open tag (such as a gui to a script) causes java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5120] opened 2020-08-24 01:13 UTC
Might already be reported, might just be JavaFX problem

Steps:
* Open a texture atlas dropdown 
* Click anywhere in the menu bar area where open file titles are
* Get java.lang.NullPointerException: Unknown

The fact it only causes an error when clicking in the open file title area makes me think it's probably easily fixable if the error was not so generic.

It happens with other dropdowns too such as Size, Layer, Pivot etc.

Win10
![2020-08-23 18_11_08-About](https://user-images.githubusercontent.com/409170/90994002-0ae17d80-e56c-11ea-92e1-f7ac2fc48c05.png)

**Comment by subsoap** [comment] 2020-08-24 01:46
Also happens in code editor with a dropdown enabled when clicking title bars. Same deal, only title bars cause the error so I wonder if it can be narrowed down...

**Comment by britzl** [comment] 2020-08-24 07:33
Duplicate of https://github.com/defold/defold/issues/4852

**Closed by britzl** 2020-08-24 07:33 UTC
Labels: bug
