### ISSUE TITLE
Loading Example Failure - Arch Linux

### ISSUE THREAD

**Issue by BearHeathen** [defold/defold#5940] opened 2021-07-17 15:31 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:46:43.704162</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1c01304f44074a609eb39dcce7887096"'>1c01304f44074a609eb39dcce7887096</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Iris(R) Plus Graphics (ICL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.1.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.12.15-arch1-1</td></tr>
<table>

**Comment by britzl** [comment] 2021-07-18 22:30
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

Please try this: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:14
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:14 UTC
Labels: bug, more info, editor, linux
