### ISSUE TITLE
Error thrown on creating new object(sprite/collection/atlas...)

### ISSUE THREAD

**Issue by drsdrs** [defold/defold#6010] opened 2021-08-26 04:42 UTC
### Expected behaviour
Create new object(sprite/collection/atlas...)

### Actual behaviour
RightClick on assets folder >> create new object(sprite/collection/atlas...) throws an error
"clojure.lang.ExceptionInfo: handler ':new-file' in context ':global' failed at ':run' with message 'No implementation of method: :resource-type of protocol: #'editor.resource/Resource found for class: nil'
java.lang.IllegalArgumentException: No implementation of method: :resource-type of protocol: #'editor.resource/Resource found for class: nil"

### Steps to reproduce
Right click on assets >> create new object(sprite/collection/atlas...) throws an error

<hr/>

<table>
<tr><td>Build time</td><td>2021-08-24T08:34:30.434218</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1238ae4c78250fac5830b149a6bf3cd4bb42899e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8e068e30da094154b571f0ef13f70f94"'>8e068e30da094154b571f0ef13f70f94</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 710/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.144</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-81-lowlatency</td></tr>
<table>

**Comment by britzl** [comment] 2022-12-02 20:15
Unable to reproduce. No additional information provided. Closing.

**Closed by britzl** 2022-12-02 20:15 UTC
Labels: bug, more info, editor
