### ISSUE TITLE
Different `require` scanning behaviour between bob.jar and Defold Editor

### ISSUE THREAD

**Issue by astrochili** [defold/defold#8022] opened 2023-09-20 09:07 UTC
**Describe the bug (REQUIRED)**
Different `require` scanning behaviour between **bob.jar** and **Defold Editor**.

```lua
-- 🚫 Build with bob.jar is fine but fails with the Defold Editor
-- Error is "module 'debugger.debugger' not found"
require('debugger.debugger').start()

-- ✅ Everything is fine
local debugger = require('debugger.debugger')
debugger.start()
```

**To Reproduce (REQUIRED)**
Create a module and try to require it with different ways described above.

**Expected behavior (REQUIRED)**
Identical behaviour, preferably working both ways.

**Defold version (REQUIRED):**
  - Version 1.5.0

**Platforms (REQUIRED):**
 - Platforms: PC
 - OS: Windows

**Additional context (OPTIONAL):**
The original issue is here - https://github.com/astrochili/vscode-defold/issues/28

**Comment by britzl** [comment] 2023-09-20 09:17
Duplicate of https://github.com/defold/defold/issues/7963

**Closed by britzl** 2023-09-20 09:17 UTC
Labels: bug
