### ISSUE TITLE
Can't without High Dpi

### ISSUE THREAD

**Issue by jixingcn** [defold/defold#9551] opened 2024-10-05 10:33 UTC
**Describe the bug (REQUIRED)**
The option - **High Dpi** doesn't work. Whether checked or not, the game still turns on **High Dpi**.
In version 1.9.1, it is okay.

**To Reproduce (REQUIRED)**
In the editor, open "game.project" and check off the **High Dpi** option on the display page.

**Expected behavior (REQUIRED)**
In the high dpi device, the game runs in low dpi.

**Defold version (REQUIRED):**
  - Version 1.9.2, 1.9.3, dev

**Platforms (REQUIRED):**
 - Platforms: Windows
 - OS: Windows 10

**Screenshots (OPTIONAL):**
(Same size of display in the game.project.)
* For version 1.9.3:
  * ![image](https://github.com/user-attachments/assets/ccb8163f-e67f-4503-af3c-45f1ec362fa1)
* For version 1.9.1: (This is correct.)
  * ![image](https://github.com/user-attachments/assets/0c05f9c9-9c6d-441a-95c1-26904f770d51)

**Comment by AGulev** [comment] 2024-10-05 10:38
duplicate of https://github.com/defold/defold/issues/9311

**Comment by jixingcn** [comment] 2024-10-05 10:42
Close this. My mistake.

**Closed** 2024-10-05 10:41 UTC
Labels: bug
