### ISSUE TITLE
Request support for RTL languages 

### ISSUE THREAD

**Issue by TheUnderName** [defold/defold#6944] opened 2022-09-03 18:16 UTC
**We request support for RTL languages ​​such as persian.**

The RTL problem in engines like Godot is fixed by adding a custom Persian RTL font

**Comment by britzl** [comment] 2022-09-04 12:36
Duplicate of https://github.com/defold/defold/issues/4900

We recently discussed RTL support internally and it is definitely something we'd like to support. Please add your thoughts to the ticket above. What works well with the solution Godot has and what could be improved?

**Closed by britzl** 2022-09-04 12:36 UTC
Labels: bug

**Comment by TheUnderName** [comment] 2022-09-04 12:49
In Godot, in order for RTL to be fixed, we first imported a Persian font like (Vazir.ttf) and copied the desired text using Text Converter sites like (https://www.timecode.ir/font-converter/) We used to do it and paste inside the editor
