### ISSUE TITLE
Engine uses incorrect value for `dt` (affects physics; update; timers; animation)

### ISSUE THREAD

**Issue by j-h-a** [defold/defold#9812] opened 2024-11-21 20:47 UTC
**Describe the bug (REQUIRED)**

When running on Apple silicon (my tests on M1 Pro) the engine sends incorrect values for `dt`.
Depending on combinations of `update_frequency` and `swap_interval`:

1.
When `update_frequency` is `60` then `dt` is often incorrectly set to `0.5` - which causes physics objects, timers, animations, and anything using `dt` passed into `update`, to leap ahead in time of where it should actually be. This can look like a choppy or laggy frame-rate, when the real frame-rate is just fine.

2.
When `update_frequency` is `0` and `swap_interval` is `1` the value of `dt` alternates between a low value (3ms) and a higher value (13ms), giving approximately 120 updates per second when the display refresh rate is actually 60 (`swap_interval` not respected?). This looks ok most of the time because on average everything is updated at the right speed, but periodically the actual screen-update event drifts over the boundary of these alternating frame-rates, and for a short time (0.5s maybe) objects appear to move fast/slow/fast/slow, jittering around from their expected position based on current movement speed. This happens every few minutes.

Note: This is almost certainly caused by or related to #8948 - but I have reported it separately because I think it may be possible to understand and solve this issue of incorrect `dt` values, even if the other issue turns out to be a problem with GLFW that cannot be fixed by Defold team.

**To Reproduce (REQUIRED)**

Use the repro project attached and run it on Apple silicon.
It may also manifest on other hardware but I haven't tested it there.

**Expected behavior (REQUIRED)**

The value of `dt` in all the game systems (physics, timers, etc.) is consistent with the actual frame-rate being achieved.

**Defold version (REQUIRED):**

1.9.5

**Platforms (REQUIRED):**

 - Platforms: macOS
 - OS: Sonoma 14.7.1
 - Device: Macbook Pro M1 Pro chip (arm64)

**Minimal repro case project (OPTIONAL):**

[dt_tests.zip](https://github.com/user-attachments/files/17851793/dt_tests.zip)

I've written a small project (not minimal) that runs a sequence of tests and shows the results in the GUI (also prints to the debug log). Results from a few runs are shown below.

**Additional context (OPTIONAL):**

The program as-is runs 4 tests, with the combinations of `update_frequency` (Freq. in the table) and `swap_interval` (Swap in the table).

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|
|   1|    0|    0|  15 ( 15.00039)| 47759|  -0.005276/0.005269|   0.000215/0.005752|   0.000216/0.005572|
|   2|    0|    1| 120 (120.00126)| 13925|  -0.002990/0.003138|   0.000670/0.020534|   0.000646/0.020579|
|   3|   60|    0| 300 (297.47633)| 17858|  -0.001310/0.499518|   0.016667/0.500000|   0.000482/0.017977|
|   4|   60|    1| 120 (116.45937)|  6993|  -0.000882/0.499210|   0.016667/0.500000|   0.000790/0.022428|

The test runs gathering data until a `timer.delay` triggers a message (to ensure test is stopped at the end of a frame). For example in test 3 above, the Duration field in the table shows the expected/desired duration of 300s, but the actual duration (according to `socket.gettime()`) is only 297.4s - this is because `timer` is incorrectly leaping ahead in time. Looking at Reported dt max (0.5) it appears that on this run this event happened about 5 times in 300s. In test 4 it looks like it happened about 7 times in 120s.

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|
|   1|    0|    0|  15 ( 15.00008)| 47610|  -0.004757/0.004751|   0.000211/0.005302|   0.000208/0.005048|
|   2|    0|    1| 120 (120.01098)| 14167|  -0.003471/0.003492|   0.001222/0.020334|   0.000622/0.020402|
|   3|   60|    0| 180 (176.96882)| 10627|  -0.000277/0.499305|   0.016667/0.500000|   0.000695/0.016943|
|   4|   60|    1| 180 (178.49587)| 10707|  -0.013460/0.499106|   0.016667/0.500000|   0.000894/0.030127|

Again in this run tests 3 and 4 show that the 0.5s time-leap happened 6 times and 3 times respectively. Note also that in all of these tables looking at test 2 shows the 120fps alternating short/long frame times described at the top.

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 14.99996)| 48159|  -0.000349/0.000354|   0.000237/0.002664|   0.000235/0.002709|  0|
|   2|    0|    1|  60 ( 60.00170)|  6938|  -0.004556/0.004729|   0.001140/0.023031|   0.000482/0.025210|  0|
|   3|   60|    0|  60 ( 58.97552)|  3543|  -0.000780/0.499458|   0.016667/0.500000|   0.000542/0.017447|  2|
|   4|   60|    1|  60 ( 58.97144)|  3541|  -0.000376/0.496189|   0.016667/0.500000|   0.003811/0.020894|  2|

I added a counter (eee column, meaning estimated error events) which counts how many frames the reported `dt` is greater than `0.05` - since the actual dt max is always lower than this, and comparing to the actual duration value, it validates the count.

**Comment by selimanac** [comment] 2024-11-22 16:04
This bothers me a lot. I can't even tell if it's my fault or not. I have a lot of dt calculations, and developing like this is incredibly frustrating.
I found a temporary solution by setting the Update Frequency to 60. This gives me a relatively stable dt on macOS, but I have no idea how it will behave on other platforms.
https://github.com/defold/defold/issues/8948#issuecomment-2418809297

**Comment by aglitchman** [comment] 2024-11-22 17:49
Have you tried running from IDE and separately as a debug/release game bundle? No difference in my runs, but who knows. (in case networking with IDE or Remotery or elase affects the engine, but this is just a finger in the air)

I ran a test project on my 2 PCs and the results are as follows:

### (from IDE) Windows 10, Ryzen 7700X + AMD Radeon 6600 XT, 60 hz display

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 14.99941)| 99140|  -0.001068/0.001068|   0.000000/0.005001|   0.000000/0.005001|  0|
|   2|    0|    1|  60 ( 60.00256)|  3601|  -0.001010/0.001011|   0.015421/0.017857|   0.015524/0.018059|  0|
|   3|   60|    0|  60 ( 60.01586)|  3602|  -0.000972/0.000859|   0.016667/0.016667|   0.015808/0.017639|  0|
|   4|   60|    1|  60 ( 60.01734)|  3602|  -0.000952/0.000897|   0.016667/0.016667|   0.015770/0.017618|  0|

### (debug and release builds) WIndows 11, Intel 9700K + GeForce RTX 3090, 144 hz display

Results:
|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 14.99976)| 44783|  -0.001646/0.001644|   0.000000/0.006558|   0.000000/0.006557|  0|
|   2|    0|    1|  60 ( 60.00198)|  8607|  -0.001568/0.001567|   0.000000/0.035325|   0.000000/0.035324|  0|
|   3|   60|    0|  60 ( 60.01679)|  3602|  -0.001077/0.001158|   0.016667/0.016667|   0.015509/0.017744|  0|
|   4|   60|    1|  60 ( 60.01650)|  3602|  -0.001911/0.001543|   0.016667/0.016667|   0.015123/0.018578|  0|

**Comment by selimanac** [comment] 2024-11-22 18:23
**From IDE, 60hz display**

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 15.00102)| 41186|  -0.005534/0.005530|   0.000240/0.005893|   0.000244/0.005828|  0|
|   2|    0|    1|  60 ( 60.01401)|  6899|  -0.003716/0.003703|   0.001122/0.023423|   0.000513/0.023447|  0|
|   3|   60|    0|  60 ( 58.46300)|  3514|  -0.001359/0.499485|   0.016667/0.500000|   0.000515/0.018026|  3|
|   4|   60|    1|  60 ( 58.99091)|  3543|  -0.002548/0.498281|   0.016667/0.500000|   0.001719/0.019665|  2|


**From IDE, 75hz display**

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 15.00003)| 39171|  -0.002256/0.002331|   0.000229/0.006616|   0.000235/0.006621|  0|
|   2|    0|    1|  60 ( 60.01260)|  3601|  -0.000354/0.000320|   0.008035/0.029568|   0.007890/0.029665|  0|
|   3|   60|    0|  60 ( 56.43230)|  3397|  -0.003862/0.499154|   0.016667/0.500000|   0.000844/0.020529|  7|
|   4|   60|    1|  60 ( 59.48078)|  3572|  -0.000088/0.498102|   0.016667/0.500000|   0.001898/0.016755|  1|

**Debug buid,  60hz display**

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 15.00003)| 43482|  -0.004307/0.004305|   0.000217/0.005018|   0.000220/0.005356|  0|
|   2|    0|    1|  60 ( 60.00341)|  6506|  -0.008161/0.008152|   0.001123/0.026503|   0.000779/0.027179|  0|
|   3|   60|    0|  60 ( 58.97280)|  3543|  -0.009351/0.499459|   0.016667/0.500000|   0.000541/0.026018|  2|
|   4|   60|    1|  60 ( 60.01214)|  3602|  -0.002745/0.002701|   0.016667/0.016667|   0.013966/0.019412|  0|

**Debug buid,  75hz display**

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 15.00015)| 44489|  -0.005233/0.005248|   0.000217/0.005613|   0.000213/0.005605|  0|
|   2|    0|    1|  60 ( 60.00085)|  4499|  -0.000705/0.000794|   0.006021/0.019785|   0.005817/0.019905|  0|
|   3|   60|    0|  60 ( 59.51218)|  3573|  -0.000033/0.489771|   0.016667/0.500000|   0.006441/0.016700|  1|
|   4|   60|    1|  60 ( 60.01214)|  3602|  -0.000073/0.000080|   0.016667/0.016667|   0.016587/0.016740|  0|

**Comment by selimanac** [comment] 2024-11-22 18:26
> I ran a test project on my 2 PCs and the results are as follows:

This is most happens on ARM based Macs: https://github.com/defold/defold/issues/8948

**Comment by aglitchman** [comment] 2024-11-22 18:28
> This is most happens on ARM based Macs: #8948

I just wanted to make sure 🙏 Plus, some time ago I didn't manage to help that person with a pretty similar problem https://forum.defold.com/t/unstable-fps-in-vsync-mode/77102

**Comment by aglitchman** [comment] 2024-11-24 14:21
As a temporary solution, just to make development enjoyable until the bug is fixed - change `engine.max_time_step` to 0.033 (30 fps) instead of 0.5.






> When `update_frequency` is `60` then `dt` is often incorrectly set to `0.5`

The engine gets the time in uint64 from this function:
https://github.com/defold/defold/blob/4bd4d8c3ec1ce3dc060b239733cfe17ab4a9e412/engine/dlib/src/dlib/time_posix.cpp#L27

As far as I understand, the OS does not guarantee monotonicity of values, so the new time can sometimes be less than the previous one. 

Delta is calculated using uint64 too:

https://github.com/defold/defold/blob/4bd4d8c3ec1ce3dc060b239733cfe17ab4a9e412/engine/engine/src/engine.cpp#L1875

And on your very fast M1 processors with software frame limitation the new time can be a nanosecond less than the previous one and we'll get an overflow of unsigned value and accordingly some of the frames will get a maximum step of 0.5 seconds.

This is my assumption! But I bet on it.

**Comment by AGulev** [comment] 2024-11-25 13:02
Here is a version of Defold with extra logs that shows raw values from inside the engine : http://d.defold.com/archive/dev/d114674c785f5dae49b1dd5bf6114a924dfdad87/dev/editor2/Defold-arm64-macos.dmg

Maybe it will help to check the theory @aglitchman has 

@j-h-a I can't reproduce this issue on both macs I have. Could you please try this version and share logs you'll get.
This version shows something like this only in cases when it uses `0.5`:
>WARNING:ENGINE: time:1732539656389859 frametime:979696(0.979696) prevTime:1732539656389859

**Comment by AGulev** [comment] 2024-11-25 13:41
I didn't check, but maybe this is related issue: https://github.com/defold/defold/issues/6465

**Comment by AGulev** [comment] 2024-11-25 13:57
Related to https://github.com/defold/defold/issues/3450

**Comment by AGulev** [comment] 2024-11-25 19:17
Frame time indicates that @aglitchman is right!
I'm working on the fix

**Comment by AGulev** [comment] 2024-11-25 21:07
@j-h-a it would be nice if you can take a look this build buildhttp://d.defold.com/archive/dev/7855cb1f311c8a053068051654b401e000ea0323/dev/editor2/Defold-arm64-macos.zip

**Comment by j-h-a** [comment] 2024-11-25 22:30
Results:

|Test|Freq.| Swap|        Duration|Frames|   Deviation min/max| Reported dt min/max|   Actual dt min/max|eee|
|----|-----|-----|----------------|------|--------------------|--------------------|--------------------|---|
|   1|    0|    0|  15 ( 15.00042)| 40261|  -0.004715/0.004712|   0.000258/0.005230|   0.000254/0.005110|  0|
|   2|    0|    1|  60 ( 60.00180)|  4860|  -0.000954/0.000999|   0.001289/0.022718|   0.001212/0.022642|  0|
|   3|   60|    0|  60 ( 60.01235)|  3602|  -0.003443/0.003399|   0.016667/0.016667|   0.013268/0.020110|  0|
|   4|   60|    1|  60 ( 60.01315)|  3599|  -0.000077/0.000068|   0.016667/0.021838|   0.016599/0.021859|  0|

Overall performance seems lower, but no excessively large `dt` values in cases 3 and 4.

* Case 1: Only did 40k frames in this build vs. 48k in original test.
* Case 2: It did 4860 frames on a 60Hz display - so I think there's still something wrong with the frame-sync. And if you look at the min/max actual dt it looks like it's still doing the short/long alternating frame-time thing (described under number 2 in the original report). Compare to @aglitchman results where case 2 consistently renders the expected number of frames to matches the display frequency * duration.
* Case 3: Suspicious reported `dt` - I guess it's fixed in this case
* Case 4: Looks great. Very little deviation between reported and actual.

**Comment by AGulev** [comment] 2024-11-26 06:17
> Case 1: Only did 40k frames in this build vs. 48k in original test.

You mentioned it in prev. build as well where I have no changes except one extra log line. So I ignore it. It's not related to the task or fixes.

> Case 3...
> Case 4...

So, it's fixed?

> Case 2...

Could you pls explain case 2 for me one more time?

**Comment by AGulev** [comment] 2024-11-26 07:38
@selimanac as I understand your results are fine now except 2? (which I didn't touch)

> I have a question. Is this fix going to affect '[dmTime::GetTime()](https://defold.com/ref/stable/dmTime/#dmTime::GetTime:)' from the SDK? I’m using it for dt calculation in native extensions, just like the [engine does](https://github.com/defold/defold/blob/cdaa870389ca00062bfc03bcda8f4fb34e93124a/engine/engine/src/engine.cpp#L1860). I see that [you are using](https://github.com/defold/defold/pull/9834/files#diff-8fb91db7b89760ad678118e90308049ce9737668e56c446df4f7d498e1fbee1fR230) dmTime::GetMonotonicTime() now?

Exactly, if PR will be approved, new function `dmTime::GetMonotonicTime()` will be introduced. This function will be recommended way to measure elapsed time. Old function stay the same.

**Comment by selimanac** [comment] 2024-11-26 07:46
> @selimanac as I understand your results are fine now except 2? (which I didn't touch)

Yes it looks so, thank you very much. I also tested the platformer example mentioned in [#8948 ](https://github.com/defold/defold/issues/8948) for a while, and it works as expected.

> except 2?

Yeah, those things happen :D God knows why! :)



> Exactly, if PR will be approved, new function `dmTime::GetMonotonicTime()` will be introduced. This function will be recommended way to measure elapsed time. Old function stay the same.

Thank you.

**Comment by aglitchman** [comment] 2024-11-26 09:46
> thank you @aglitchman for the idea which was 100% hit the target

Glad to be of help!

**Comment by gianmichelemariani** [comment] 2024-11-26 11:22
Thank you everyone for being a lot more technical than me and provide proper data for the fix to happen.
This was quite a bad one for Mac that at some point I saw disappearing from the list of issues being worked on.

**Closed** 2024-11-26 14:01 UTC
Labels: bug, engine, dt
