### ISSUE TITLE
Updating Defold on Mac doesn't show progress

### ISSUE THREAD

**Issue by totebo** [defold/defold#6263] opened 2021-12-15 08:59 UTC
**Describe the bug (REQUIRED)**
When updating Defold from the editor, the progress bar doesn't show progress, which might lead to users not thinking the update is working. See video below.

**To Reproduce (REQUIRED)**
Click the "Update Available" text link in the editor, then "Download Updated".

**Expected behavior (REQUIRED)**

**Defold version (REQUIRED):**
1.2.185+

**Platforms (REQUIRED):**

macOS Big Sur 11.6.
<img width="698" alt="Screenshot 2021-12-15 at 08 57 44" src="https://user-images.githubusercontent.com/4493302/146155136-fea7c5fd-3288-4919-b53a-cd150cc050bf.png">

**Screenshots (OPTIONAL):**
https://youtu.be/b8rlcsb7-8c

**Comment by AGulev** [comment] 2023-09-26 10:17
duplicate of https://github.com/defold/defold/issues/5408

**Closed by AGulev** 2023-09-26 10:17 UTC
Labels: bug, editor
