### ISSUE TITLE
Cannot create new empty project without internet access

### ISSUE THREAD

**Issue by mxashlynn** [defold/defold#9395] opened 2024-09-08 00:44 UTC
**Describe the bug (REQUIRED)**
Currently, it is not possible the create a new, empty project without connecting to the internet.

**To Reproduce (REQUIRED)**
1. Open Defold.
2. Click on 'Create new project'
3. Note that "Empty project" is selected by default.
4. Click on 'Create New Project'
5. See the error message: "You must be connected to the internet to download project content."

**Expected behavior (REQUIRED)**
A completely empty project is created.

**Defold version (REQUIRED):**
  - Version 1.9.2

**Platforms (REQUIRED):**
 - Platforms: N/A
 - OS: Windows 10
 - Device: IBM PC Compatible

**Minimal repro case project (OPTIONAL):**
No project is created.

**Logs (OPTIONAL):**
No logs are created.

**Workaround (OPTIONAL):**
It is possible to create a project if the internet is available.

**Screenshots (OPTIONAL):**
![You must be connected to the internet to download project content.](https://github.com/user-attachments/assets/f016e01a-1b2e-494a-85d5-b4e6b051c41b)

**Additional context (OPTIONAL):**
This seems like a low priority, but I thought I should report it anyway as one would expect that an *empty* project would require no off-site resources.

**Comment by selimanac** [comment] 2024-09-08 05:47
This is a problem, but just for a quick workaround; you can download the templates once and open them when ever you want:
https://github.com/orgs/defold/repositories?type=all&q=template

**Comment by britzl** [comment] 2024-09-09 07:31
Duplicate of https://github.com/defold/defold/issues/3930

**Closed by britzl** 2024-09-09 07:31 UTC
Labels: bug
