### ISSUE TITLE
Got a "Flush is forbidden from target" error on macOS

### ISSUE THREAD

**Issue by mascap55** [defold/defold#5788] opened 2021-05-01 18:19 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-04-13T06:40:52.350087</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b004f16e507cef52b6940c6970cbefc0d68722f0</td></tr>
<tr><td>Defold engine sha</td><td>ff5b94e432eb58dabdb8e367bed9acc5e99e129b</td></tr>
<tr><td>Defold version</td><td>1.2.181</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5abf2eb673ec4540afd8d4c7264018cb"'>5abf2eb673ec4540afd8d4c7264018cb</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 6000</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-16.1.11</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment] 2021-05-02 11:02
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1022)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:274)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1286)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3043)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3112)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3872)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1851)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2584)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

@mascap55 do you recall what you did when this problem occurred?

**Comment by britzl** [comment] 2021-06-20 12:53
Duplicate of #5875

**Closed by britzl** 2021-06-20 12:53 UTC
Labels: editor, macos, more info
