### ISSUE TITLE
Pressing occurs higher than it should if, after opening the keyboard, open notification bar on the android

### ISSUE THREAD

**Issue by JAlHund** [defold/defold#5267] opened 2020-10-08 19:50 UTC
**Describe the bug**
Pressing occurs higher than it should if, after opening the keyboard, open notification bar on the android

**To Reproduce**
1. Open the keyboard
2. Immediately scroll from top to bottom and open the notification panel.
Once returned, pressing occurs higher than it should. If you open the keyboard and click on the screen or press enter, keyboard will close and this will stop

**Expected behavior**
The click should be processed without offset

**Defold version:**
1.2.174

**Platforms:**
Android

**Minimal repro case project:**
[Mobile game.zip](https://github.com/defold/defold/files/5350996/Mobile.game.zip)

**Video:**
https://drive.google.com/file/d/1Zr3Gqbdy3j5RAHHD6OkRjKkrF8DQPqoT/view?usp=sharing

**Comment by britzl** [comment] 2021-02-10 08:46
I've started investigating this and I'm not able to reproduce the problem yet. Some observations:

* The input events are received and forwarded from GLFW unmodified: https://github.com/defold/defold/blob/dev/engine/glfw/lib/android/android_init.c#L458-L506
* The events are at a later stage processed before forwarding to scripts: https://github.com/defold/defold/blob/dev/engine/engine/src/engine.cpp#L1209-L1266
  *  Note the width_ratio and height_ratio which is applied to m_X and m_Y but not to m_ScreenX and m_ScreenY

I'm thinking that we somehow lose track of the correct window height when the keyboard is shown and the notifications go on top.

@JAlHund would you be able to do another test and check what value you get from `window.get_size()` and what you have in `action.y` as well `action.screen_y`.

I'm going to try on a couple of additional devices and see if I can reproduce the problem there.

**Comment by britzl** [comment] 2021-02-10 09:51
Nope, tested on two more devices and I can't seem to get touch events to register in the wrong place. It's also not super obvious from the video what is wrong.

I'm going to close this issue. @JAlHund  please reopen and provide more information.

**Closed by britzl** 2021-02-10 09:51 UTC
Labels: bug, input, more info

**Comment by JAlHund** [comment] 2021-02-10 10:39
> @JAlHund would you be able to do another test and check what value you get from `window.get_size()` and what you have in `action.y` as well `action.screen_y`.

`window.get_size()` values are the same with bug and without
`action.y` and `action.screen_y` values are almost the same (Example: y: 18.5, screen_y: 19 or y: 61.5, screen_y: 62). In case of a bug, they are shifted by 40-odd pixels up. If without a bug they are 5, then with a bug somewhere around 50 

> It's also not super obvious from the video what is wrong.

`action.y` and `action.screen_y` is shifted 40-50 pixels up. I try to click at the very bottom of the screen in video

This bug disappears after using  `gui.reset_keyboard()`

Currently I know that players had a bug on these devices: Xiaomi Redmi 5A, Honor 10i
I think there are actually more devices, but I am using `gui.reset_keyboard()` to fix it. So I did not receive information from players about this bug and the devices on which it happened for a long time

**Comment by britzl** [comment] 2021-02-10 10:52
> Currently I know that players had a bug on these devices: Xiaomi Redmi 5A, Honor 10i

The problem is very likely device specific (or Android OS specific). I've tested on Motorola, Samsung and a Xiaomi device without being able to get reproduce the problem.
