### ISSUE TITLE
Comparison for URL provided in `go.property` behaves differently between debug and release builds.

### ISSUE THREAD

**Issue by j-h-a** [defold/defold#9804] opened 2024-11-20 11:01 UTC
**Describe the bug (REQUIRED)**

Doing an equality comparison between a URL provided in a `go.property` and one written in code yields different results between debug and release builds.

**To Reproduce (REQUIRED)**

Build the attached project and observe the blob sprite being different colours in debug vs. release builds.

**Expected behavior (REQUIRED)**

The blob should go the same colour in both debug and release builds.

**Defold version (REQUIRED):**
  - Version 1.9.4

**Platforms (REQUIRED):**

 - Platforms: macOS

**Minimal repro case project (OPTIONAL):**

[NullableURL.zip](https://github.com/user-attachments/files/17829449/NullableURL.zip)

@britzl adding script file for convenience:

```lua
go.property("some_url", msg.url("does", "not", "exist"))

function init(self)
	if self.some_url == msg.url("does", "not", "exist") then
		go.set("#sprite", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite", "tint", vmath.vector4(1, 0, 0, 1))
	end
end
```

**Comment by britzl** [comment] 2024-11-20 11:54
@j-h-a what if you compare the three components of the url?

```
go.property("some_url", msg.url("does", "not", "exist"))

function init(self)
	local url = msg.url("does", "not", "exist")
	if self.some_url.socket == url.socket and self.some_url.path == url.path and self.some_url.fragment == url.fragment then
		go.set("#sprite", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite", "tint", vmath.vector4(1, 0, 0, 1))
	end
end
```

**Comment by redoak** [comment] 2024-11-20 12:09
The property url is all different for me when building for HTML5 (as compared to running from editor on Windows):

When running *Project -> Build* on Windows:

![image](https://github.com/user-attachments/assets/3fa0255d-13f5-440e-93b3-3eb0e7647f61)

When running *Project -> Build HTML5* on Windows:

![image](https://github.com/user-attachments/assets/6bea50b1-8ced-4c68-9794-ee152c844c2d)

This is my script:

```lua
go.property("some_url", msg.url("does", "not", "exist"))

local log = ''

local dummy = msg.url("does", "not", "exist")
log  = log .. 'script local var: ' .. tostring(dummy) .. '\n'
log  = log .. 's: ' .. hash_to_hex(dummy.socket) .. '\n'
log  = log .. 'p: ' .. hash_to_hex(dummy.path) .. '\n'
log  = log .. 'f: ' .. hash_to_hex(dummy.fragment) .. '\n'
log  = log .. '\n'

function init(self)
	local prop = self.some_url
	log  = log .. 'property: ' .. tostring(prop) .. '\n'
	log  = log .. 's: ' .. (prop.socket and hash_to_hex(prop.socket) or "na") .. '\n'
	log  = log .. 'p: ' .. (prop.path and hash_to_hex(prop.path) or "na") .. '\n'
	log  = log .. 'f: ' .. (prop.fragment and hash_to_hex(prop.fragment) or "na") .. '\n'
	log  = log .. '\n'
	
	local rhs = msg.url("does", "not", "exist")
	log  = log .. 'local to init: ' .. tostring(rhs) .. '\n'
	log  = log .. 's: ' .. hash_to_hex(rhs.socket) .. '\n'
	log  = log .. 'p: ' .. hash_to_hex(rhs.path) .. '\n'
	log  = log .. 'f: ' .. hash_to_hex(rhs.fragment) .. '\n'
	log  = log .. '\n'

	if self.some_url == rhs then
		go.set("#sprite", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite", "tint", vmath.vector4(1, 0, 0, 1))
	end
end

function update(self, dt)
	local pos = vmath.vector3(500, 500, 0)
	msg.post("@render:", "draw_text", { text = log, position = pos })
end
```

**Comment by j-h-a** [comment] 2024-11-20 13:27
Built on: M1 Mac arm64

Reproduced on:
Release target: macOS Universal - reproduced (on arm64).
Release target: Windows x86_64 - reproduced.
Release target: Linux x84_64 - reproduced.

**Comment by j-h-a** [comment] 2024-11-20 13:51
> @j-h-a what if you compare the three components of the url?

[NullableURL.zip](https://github.com/user-attachments/files/17831554/NullableURL.zip)

I extended the project to include 4 sprite components with this code:
```lua
go.property("some_url", msg.url("does", "not", "exist"))

function init(self)
	if self.some_url == msg.url("does", "not", "exist") then
		go.set("#sprite", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite", "tint", vmath.vector4(1, 0, 0, 1))
	end

	if self.some_url.socket == hash("does") then
		go.set("#sprite_1_socket", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite_1_socket", "tint", vmath.vector4(1, 0, 0, 1))
	end

	if self.some_url.path == hash("not") then
		go.set("#sprite_2_path", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite_2_path", "tint", vmath.vector4(1, 0, 0, 1))
	end

	if self.some_url.fragment == hash("exist") then
		go.set("#sprite_3_fragment", "tint", vmath.vector4(0, 1, 0, 1))
	else
		go.set("#sprite_3_fragment", "tint", vmath.vector4(1, 0, 0, 1))
	end
end
```

And all four sprites go green in debug build, red in release build.

**Comment by j-h-a** [comment] 2024-11-26 21:00
I'm starting to realise that URLs in Defold are just fundamentally broken - at least in how they described, compared to what they really are. We think and talk of them as the name suggests, as a resource *locator* - they have absolute and relative forms, and sub-components like socket, path, and fragment... but they're actually more like runtime object references.

```lua
local some_url = msg.url("relative_obj#component")
function init(self)
    local other_url = msg.url("relative_obj#component")
end
```

Here `some_url` and `other_url` are NOT the same. They change based on the state of things at time you create them. The relative object locator is not a locator at all - you can't pass it to a different socket or a different object in another collection and have it locate an object relative to that one. This is because when you create it, it gets converted to an absolute reference to an exiting object, or if it doesn't exist at the time of creation, then.. I'm not sure - the sub-component hashes are just stored? That last thing is actually how URLs should *always* behave, if it were truly a *locator* - in that case it wouldn't matter when or where you create them, equal URLs would always be equal, even for non-existing objects.

I think this might explain it a bit:

```lua
    local this_is_not_a_url_it_is_an_object_reference = msg.url("this_string:/is_a#url")
    -- Does it mean this?
    local obj_ref = msg.find_resource_at_url("some:/url")
```

I suspect that this confusion is the source of a huge amount of wasted time of both Defold users and the Defold team. It's a routine by now to see users with an issue, and the engine devs get confused by it, commenting that it's strange and should work, urls are in use everywhere and we would know if they are broken... and yet even the engine devs don't spot the problem in the user-code (because they are sane intelligent developers and the code looks intuitively correct), until eventually someone realises and explains what's going on.

Even with this deeper understanding, I still don't know why this causes different behaviour between debug and release builds. I suspect that the `msg.url("does", "not", "exist")` in the `go.property` gets converted to a string for the editor, then the engine tries to convert it back after loading the collection (so any actual referenced objects should exist by now), but in the case it doesn't exist then the URL object itself becomes some invalid thing (because it's not actually a locator, it's trying to reference actual instances), so then creating another invalid one during `init` is not equal (a bit like how NaN != NaN).

Any explanation or correction of my shoddy understanding of all this would be greatly appreciated.

**Comment by JCash** [comment] 2024-11-27 12:19
> Even with this deeper understanding, I still don't know why this causes different behaviour between debug and release

I think it's easy to get up-in-arms when you encounter a bug, and can't easily fix it yourself.
However, I do not think the concept of url's themselves are to blame, but rather some implementation detail somewhere.

In short, urls are not complex as such. They're addresses, you use them every day in a browser, in a file system etc.
Any confusion I see in our forum mostly stems from not knows the address of the current object, or the address of the receiving object.

Also, talking about "resources" doesn't help, as there already exists a distinct concept of a resource (i.e. a resouce on disc).

**Comment by j-h-a** [comment] 2024-11-27 13:05
> In short, urls are not complex as such. They're addresses

This is the problem - they are NOT addresses, they are NOT locators, they are NOT like the URLs we use in a browser. And yet everyone talks of them this way, which is the cause of the confusion.

When I say "they" - referring to URLs - I'm talking about the return value of `msg.url`.
The *string* you pass in is a URL, sure.
But the return value is not an address or a locator, it is a runtime-reference to the located object or component at the string-url that was passed in.

> I think it's easy to get up-in-arms when you encounter a bug, and can't easily fix it yourself.

My point is - this might not even be a bug, but a perfectly expected behaviour, but it's hard to reason about because of expectations. We think of "creating a URL" with `msg.url` as a deterministic thing, a *pure* function if you will. But I think it's not, and probably that's intentional. `msg.url` does not give you a URL, it takes a URL.

> Also, talking about "resources" doesn't help, as there already exists a distinct concept of a resource (i.e. a resouce on disc).

Exactly my point - URL means Uniform Resource Locator. But constructed URLs in Defold do not locate "resources" at all. They reference actual instances of objects/components in a world.

**Comment by JCash** [comment] 2024-11-27 13:59
> But the return value is not an address or a locator, it is a runtime-reference to the located object 

Not sure what you're getting at here. It's completely possible for you to create a url that doesn't address anything.
Sure we have helper functions to tell the developer if there is no such receiver, because we feel that's useful to know
And it isn't a "reference" in the C sense, it is just an address. It's just a struct with 3 hashes, nothing more.

**Comment by JCash** [comment] 2024-11-27 15:01
> But the value of these depends on world state at the time of creation.

Sure, if information is left out in the string mode, it will try to be helpful, by resolving the current values.
I don't see that as a problem to be honest.
I view them as a relative path. ONce resolved, the missing info is filled in, but I can still compare the relative path parts (path + fragment).

You could also be specific: `msg.url(hash("mysocket"), hash("mypath"), hash("myfragment"))`, thus not resolving anything.


> If you construct a URL in any web or mobile framework/library

Again, think of them as relative paths. Once resolved, a relative path on one site won't work on another site either.

> I'm starting to realise that URLs in Defold are just fundamentally broken

I just don't agree this sentiment. Apart from the reported OP issue, I think the URL's work quite well.
Also, not sure what you're suggesting here to be done to be honest.

**Comment by AGulev** [comment] 2024-11-27 15:15
> For example if I create `url1 = msg.url("object#sprite")` in `collection1` the three hashes represent `hash("current_socket"), hash("/collection1/object"), hash("sprite")` and I do the same form `collection2` - well you can see, they're not going to be equal.

Do you mean collection proxies?

**Comment by JCash** [comment] 2024-11-27 15:24
Running the example project now, I get the failing case in both debug and release.
When printing out the `print("self.some_url:", self.some_url.socket, self.some_url.path, self.some_url.fragment)`, I get:
```
self.some_url:	hash: [main]	hash: [<unknown:13344056158176457683>]	nil
```
which is quite odd tbh.

**Comment by j-h-a** [comment] 2024-11-27 15:46
> I just don't agree this sentiment.

You ignored the clarifier: *"at least in how they described, compared to what they really are"*

> Apart from the reported OP issue, I think the URL's work quite well.

Yes, addressing works quite well. Describing how it works to users, not so much. The API tricks users into a common misunderstanding and I'm trying to help you understand how fresh eyes (and even not so fresh eyes) see it. Why it leads to such confusion.

> Also, not sure what you're suggesting here to be done to be honest.

Perhaps deprecate `msg.url` and add `msg.resolve_url` in its place? So it's clear that what you get back is not deterministic, it's not a representation of what you passed in, but it's something that has been resolved at the time you call it.

> which is quite odd tbh.

Yes, it is.

**Comment by JCash** [comment] 2024-11-27 15:56
> So it's clear that what you get back is not deterministic

It certainly is deterministic, just perhaps not what you expected.
We can probably do a better job of documenting it.


Back to the actual issue, it seems to stem from the LuaScanner in our pipeline.
The line:
```
go.property("some_url", msg.url("does", "not", "exist"))
```

Will output this when we build properties:
```
name: some_url  value: 'does'  type: PROPERTY_TYPE_URL  status: OK
```

Knowing this, I tried rewriting it as:
```lua
go.property("some_url", msg.url("does:not#exist"))
```
And it now works for me in both debug and release.

I'll defer to @AGulev for his expertise on how to fix the Lua scanner.

**Comment by AGulev** [comment] 2024-11-27 15:56
1. I think URLs are fine
2. A few issues mixed up in one place again and I would like to keep this ticket for the initial issue
3. We have an issue related to hashes  + the issue from the main post. It's not "URLs in Defold are just fundamentally broken". Just a few issues that needs to be solved. 

I'm working on this one right now.

@j-h-a please answer my question:


> > For example if I create `url1 = msg.url("object#sprite")` in `collection1` the three hashes represent `hash("current_socket"), hash("/collection1/object"), hash("sprite")` and I do the same form `collection2` - well you can see, they're not going to be equal.
> 
> Do you mean collection proxies (worlds)? (this might be actually related to #9374)

**Comment by AGulev** [comment] 2024-11-27 16:04
> @j-h-a please answer my question:
> 
> > > For example if I create `url1 = msg.url("object#sprite")` in `collection1` the three hashes represent `hash("current_socket"), hash("/collection1/object"), hash("sprite")` and I do the same form `collection2` - well you can see, they're not going to be equal.
> > 
> > 
> > Do you mean collection proxies (worlds)? (this might be actually related to #9374)

And if here you are talking about go.property here as well, then it's the same issue Mathias just found. This is an issue in parser.

**Comment by redoak** [comment] 2024-11-27 16:41
Although not about the initial bug report, I would like to add my two cents about how addressing and URLs are described.

> Also, not sure what you're suggesting here to be done to be honest.

After reading this thread and getting a better understanding of how URLs etc. work, the [manual page on addressing](https://defold.com/manuals/addressing/) is easier to understand. I think an issue is that there are multiple important terms/keywords, and it's not obvious when they refer to distinct concepts, when it's the same concept but the value differs per object type, and when the article writer simply used different words for the same thing.

Concepts:

- Address
- Identifier, identity, id, name
- Path
- Fragment
- Socket
- URL
- Naming context, current game object
- Relative and absolute addressing, complete URL

Then there's also what it means to resolve an address, and how these concepts relate to collections, game objects, components, hashes and strings.

**Improvement proposal**

I think it might help if, before making any documentation changes, all the distinct concepts were identified, and a clear and concise terminology agreed upon. E.g. decide which of *identifier*, *identity*, *id*, and *name* should remain. Once that's done, this article and the [reference page for msg](https://defold.com/ref/stable/msg/) (and maybe a few others) were revisited and edited to be precise in the wording used.

Additionally, I believe it would be helpful if in the text the terms were highlighted when used, to draw the reader's attention to them as named concepts. E.g. using italic:

> These *addresses* consist of *identifiers*.

I believe it would also be helpful to add a glossary table to the manual page on addressing, so the reader can refer to it and verify that the terms in their mental model corresponds to reality.

**Comment by AGulev** [comment] 2024-11-27 18:04
Ok. Here is an explanation what the issue is.

In both cases, the issue is related to the `go.property()`.
Both, the editor and bob (used when you bundle) has its own Lua parser to parse `go.properties` (I don't like `go.property()` because we have to parse code for data extraction, but please let's not switch to this topic here).

The difference between two parsers and some bugs in both are the reason for the issues you have.

The parser we have in bob understands only one format of `msg.url()` in `go.property()` with one string in it. 
So,
```lua
--1
go.property("url", msg.url("my:/cool#url") -- works in both

--2
go.property("url", msg.url("my, "cool", "url")) -- doesn't work in Bob. But it works in the Editor.

--3
go.property("url", msg.url(nil, nil, "url")) -- using nil doesn't work in Bob and in the editor even though it's possible to use it this way in the runtime.
```

 I'm fixing №2 because it is obviosly a bug.
 №3 seems like expected behaviour, because using nil in runtime has "helprs" that fill gaps, because in runtime ot knows full path to the object, using nills in `go.property()` doesn't make sense, there is no way to know final path at build time (exept a couple of situations without factories). But empty strings work at build time.

**Closed** 2024-11-29 08:23 UTC
Labels: bug, engine
