### ISSUE TITLE
Read Live Update content from multiple archives

### ISSUE THREAD

**Issue by dapetcu21** [defold/defold#5319] opened 2020-11-06 10:42 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
In Interrogations we use two Live Update archives whenever we update the game: A bigger archive that doesn't change often and a smaller one that we swap out each update. (When making small updates to the game, often times 90% of the resources don't change and their hash filename doesn't change either, so there's no point re-downloading most of the game for a single-line fix in a script, for example).

Another use-case for this would be being able to split the game in multiple DLC packs.

**Describe the solution you'd like (REQUIRED):**
Using the new `resource.store_archive()` mechanism, it would be great if we could specify additional archives to read from (instead of replacing the main one), maybe with a user-specified filename identifier (like the DLC name, for example), so that they're easy to replace with updated versions. An alternative solution would be using `resource.store_archive()` in conjunction with `resource.store_resource()` in a way that the game can load resources from either source.

**Describe alternatives you've considered (REQUIRED):**
Using `resource.store_resource()` for everything (what we do now) or using a single archive and giving up small patch sizes.

**Comment by AGulev** [comment] 2023-07-21 19:35
duplicate of https://github.com/defold/defold/issues/6675 (currently in progress)

**Closed by AGulev** 2023-07-21 19:35 UTC
Labels: feature request, engine, live update
