### ISSUE TITLE
Tilemap brush selection error

### ISSUE THREAD

**Issue by sergeykozlovd** [defold/defold#9397] opened 2024-09-08 21:50 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-30T08:34:52.703441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"e8152a1a8c8d427e8a674dc7370419ab"'>e8152a1a8c8d427e8a674dc7370419ab</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by AGulev** [comment] 2024-09-09 06:17
```
clojure.lang.Numbers.ops.class java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "x" is null
    at clojure.lang.Numbers.ops(Numbers.java:1068)
    at clojure.lang.Numbers.remainder(Numbers.java:200)
    at clojure.core$mod.invokeStatic(core.clj:3571)
    at editor.tile_map$palette_x.invokeStatic(tile_map.clj:154)
    at editor.tile_map$make_brush_from_selection_in_palette.invokeStatic(tile_map.clj:162)
    at editor.tile_map$handle_input_palette.invokeStatic(tile_map.clj:1328)
    at editor.tile_map$handle_input.invokeStatic(tile_map.clj:1340)
    at editor.tile_map$make_input_handler$fn.invoke(tile_map.clj:1347)
    at editor.scene$dispatch_input$fn.invoke(scene.clj:1168)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at editor.scene$dispatch_input.invokeStatic(scene.clj:1165)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1206)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1204)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1183)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:896)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1818)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1818)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1930)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:2004)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by britzl** [comment] 2024-09-09 07:34
Can you reproduce this error? If so, how?

**Comment by sergeykozlovd** [comment] 2024-09-09 08:35
no, sorry, this error happened because i didn't add the image to the tilesource and submitted the report before i noticed it. all is well now!

**Comment by AGulev** [comment] 2024-09-13 15:23
@sergeykozlovd  should we close it then?

**Comment by sergeykozlovd** [comment] 2024-09-15 23:52
Yes sure. Thanks for your job!

**Closed** 2024-09-16 08:21 UTC
Labels: bug, editor, tilemap
