### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iDroid-dev** [defold/defold#8435] opened 2024-01-22 12:02 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2024-01-19T13:51:28.587493</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>def793b2d4d6372d0d81da9788c7ac8bdb5d47f9</td></tr>
<tr><td>Defold engine sha</td><td>37a4a8548850a7243055bb820e45580cfdae5f32</td></tr>
<tr><td>Defold version</td><td>1.6.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"21d0dd7c7d704ee6a448bc98a32335cf"'>21d0dd7c7d704ee6a448bc98a32335cf</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 Compatibility Profile Context 23.11.1.231017</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2024-01-22 12:32
@iDroid-dev thank you for the report. What did you do when it happened? Can you reproduce it?

**Comment by britzl** [comment] 2024-01-22 12:34
Duplicate of https://github.com/defold/defold/issues/6527

@iDroid-dev you probably added a lot of *very* large images. Is this correct?

**Closed** 2024-01-22 18:31 UTC
Labels: bug, more info, editor
