### ISSUE TITLE
Spotter

### ISSUE THREAD

**Issue by ayanokojikaton** [defold/defold#7235] opened 2022-12-21 12:55 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-12-14T07:55:16.202458</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>149e4b460a40e526761026846a04079ea4672433</td></tr>
<tr><td>Defold engine sha</td><td>8f96e450ddfb006a99aa134fdd373cace3760571</td></tr>
<tr><td>Defold version</td><td>1.4.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c934f57dbd0b489bb608bd3576657d1f"'>c934f57dbd0b489bb608bd3576657d1f</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14756 Compatibility Profile Context 20.40.52 27.20.14052.10</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-12-27 22:05
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production evaluation-context) (gt/endpoint node-id label)))
    at internal.node$mark_in_production.invokeStatic(node.clj:1337)
    at editor.collection$CollectionNode$behavior$build_targets.invokeStatic(collection.clj:426)
    at editor.collection$CollectionNode$behavior$build_targets.invoke(collection.clj:426)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:287)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1164)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets$fn.invoke(collection_proxy.clj:89)
    at internal.node$trace_expr$fn.invoke(node.clj:38)
    at internal.node$trace_expr.invokeStatic(node.clj:38)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets.invokeStatic(collection_proxy.clj:89)
    at editor.collection_proxy$CollectionProxyNode$behavior$build_targets.invoke(collection_proxy.clj:89)
    at clojure.lang.Var.invoke(Var.java:393)

```

**Comment by britzl** [comment] 2022-12-27 22:06
@ayanokojikaton this is a duplicate of https://github.com/defold/defold/issues/3919. Please refer to this issue for possible solutions

**Closed by britzl** 2022-12-27 22:06 UTC
