### ISSUE TITLE
Error while adding assets

### ISSUE THREAD

**Issue by kinzua01** [defold/defold#6569] opened 2022-05-03 13:49 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-02T08:45:59.833601</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>563d19f88cdf76ddd11128859aada8c6541c9a97</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f5cff11af2d346a0880fe2459b61c653"'>f5cff11af2d346a0880fe2459b61c653</a></td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 76.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment] 2022-05-04 06:18
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1017)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:276)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1301)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3066)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3135)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1874)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
```

**Comment by britzl** [comment] 2022-05-04 06:20
Duplicate of https://github.com/defold/defold/issues/5875

**Closed by britzl** 2022-05-04 06:20 UTC
