### ISSUE TITLE
I keep getting this error prompt? 

### ISSUE THREAD

**Issue by NoahDavon** [defold/defold#4865] opened 2020-05-30 11:37 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-05-29T09:17:10.261317</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>afe2dda91a889fe7504d154f55b0443ef2e378fd</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a28812725df9466a85d8d958fa5ec1dc"'>a28812725df9466a85d8d958fa5ec1dc</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 5500 (BDW GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-31-generic</td></tr>
<table>

**Comment by britzl** [comment] 2020-05-30 11:51
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

**Comment by britzl** [comment] 2020-06-21 10:14
Duplicate of #4851

**Closed by britzl** 2020-06-21 10:14 UTC
Labels: editor, linux, opengl
