### ISSUE TITLE
java.lang.AssertionError: Assert failed: (rename? resources) - Error when trying to rename .gui_script

### ISSUE THREAD

**Issue by Dolbaeb777K** [defold/defold#9134] opened 2024-06-27 09:57 UTC
The project in the another NTFS drive
Defold from steam (not flathub).
Steam from `zypper in steam`

### Expected behaviour
Rename "Main_menu_menu.gui_script" to the "Main_menu.gui_script"
### Actual behaviour
Error appear: java.lang.AssertionError: Assert failed: (rename? resources)
### Steps to reproduce
1. Right click on "Main_menu_menu.gui_script";
2. Click on **`Rename`** in the popup menu;
3. Remove `_menu` in `New File Name` line in the popup menu "Rename File";
4. Get an error.
<hr/>

<table>
<tr><td>Build time</td><td>2024-06-25T16:24:14.962363</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3642fa5b700b8d6e74e3f0595e75cd50eff54459</td></tr>
<tr><td>Defold engine sha</td><td>d6882f432beca85d460ec42497888157c356d058</td></tr>
<tr><td>Defold version</td><td>1.9.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"fd49a4f56b9d4754beedfba5cdcde0bf"'>fd49a4f56b9d4754beedfba5cdcde0bf</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon RX 580 2048SP (radeonsi, polaris10, LLVM 18.1.6, DRM 3.57, 6.9.6-1-default)</td></tr>
<tr><td>GPU Driver</td><td>4.6 (Compatibility Profile) Mesa 24.1.2</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>6.9.6-1-default</td></tr>
<table>

**Comment by AGulev** [comment] 2024-06-27 09:58
```
editor.asset_browser$rename.invokeStatic.class java.lang.AssertionError: Assert failed: (rename? resources)
    at editor.asset_browser$rename.invokeStatic(asset_browser.clj:390)
    at editor.asset_browser$fn$fnk109031_positional__109035.invoke(asset_browser.clj:441)
    at editor.asset_browser$fn$fnk109031__109051$fn.invoke(asset_browser.clj:430)
    at editor.asset_browser$fn$fnk109031__109051.invoke(asset_browser.clj:430)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$run.invokeStatic(handler.clj:289)
    at editor.ui$execute_handler_ctx.invokeStatic(ui.clj:1192)
    at editor.ui$execute_command.invokeStatic(ui.clj:1200)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1231)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1312)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1415)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1368)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3987)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$10(GtkApplication.java:264)
    at java.lang.Thread.run(Thread.java:833)

**Comment by Dolbaeb777K** [comment] 2024-06-27 10:02
I got it, thanks. 



(It's just a joke)

**Comment by AGulev** [comment] 2024-06-27 10:03
sorry, I didn't mention that his comment isn't for you, it's for us.

**Comment by Dolbaeb777K** [comment] 2024-06-28 05:52
So, I reinstalled the linux fully, Then installed Defold from steam again, opened the project....
My gui_script disappeared and now I can't delete this strange file:
![изображение](https://github.com/defold/defold/assets/126266582/9ba22760-7208-41fa-b2c7-8e031592d434)
How to del this strange file?

**Comment by Dolbaeb777K** [comment] 2024-06-28 05:54
Here it isn't there
![изображение](https://github.com/defold/defold/assets/126266582/ecf66cf2-84ae-4e63-9772-9ad2a14f66cf)

**Comment by AGulev** [comment] 2024-08-01 06:44
What exactly linux are you using?
Defold tested and officially support Ubuntu:  https://defold.com/faq/faq/#platform-questions

**Comment by Dolbaeb777K** [comment] 2024-08-01 06:53
> What exactly linux are you using? Defold tested and officially support Ubuntu: https://defold.com/faq/faq/#platform-questions

I use Linux Mint (Ubuntu-based distro) and mostly use openSUSE (SUSE ; RedHat) Slowroll (openSUSE Tumbleweed-based).

I think this problem appearing because I open my project which is located on the NTFS disk, rightly?
It's strange, but the same problem appeared when I tried to start my project ON the Windows OS.

**Comment by AGulev** [comment] 2024-08-02 06:25
Yes, I think it might be related to NTFS. 
I'm closing it for now

**Comment by britzl** [comment] 2024-08-03 05:54
I asked a few users on Discord to try using NTFS on Linux and it works for them:

https://discord.com/channels/250018174974689280/822548486755057735/1268975019908665464

> "I'm using Mint and I formatted my backup disk in Windows, so the file system is NTFS. I opened a tutorial project on my backup disk in Mint. It works."

> "I'm using Ubuntu 22.04 and have a Windows dual boot.
I tried: load into Win, download Defold example project from github, restart into Ubuntu, open project from NTFS Win drive - all ok."

**Comment by vlaaad** [comment] 2024-08-12 13:46
Hi, please check the editor for update, the issue is most probably resolved. Feel free to reopen if the issue returns :)

**Closed by vlaaad** 2024-08-12 13:47 UTC
Labels: bug, editor, linux
