### ISSUE TITLE
custom_resources and include_dirs settings does not allow absolute paths (DEF-1485)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3278] opened 2019-05-23 10:33 UTC
custom_resources and include_dirs and any future setting where multiple paths can be specified should have a unified syntax. Currently none allow absolute paths, custom_resources is comma separated and include_dirs is space separated.

Proposal:

custom_resources = /main/data/,/main/data/file.txt
include_dirs = /levels/,/assets/

absolute paths, comma separated. Allow paths without initial slash (relative to project root) for legacy, but issue warnings and enforce through editor. Also allow space separation for the same reason. (Commas in paths can be handled with escapes if necessary)

Currently build errors happen with absolute paths.

STR:

1. Add a folder with some data to project.
2. Specify custom resources:

custom_resources = /main/data/

3. Build.

Errors occurred during the build.
Errors running builder 'Content Builder' on project 'Empty template'.
Build failed: /Applications/Defold-macosx/branches/1945/4/work/main/data (Is a directory)
/Applications/Defold-macosx/branches/1945/4/work/main/data (Is a directory)
Build failed: /Applications/Defold-macosx/branches/1945/4/work/main/data (Is a directory)
/Applications/Defold-macosx/branches/1945/4/work/main/data (Is a directory)

Currently the path has to be specified without the initial slash, which is

**Comment by AGulev** [comment] 2022-12-02 21:33
duplicate of the https://github.com/defold/defold/issues/3150 ?

**Comment by britzl** [comment] 2022-12-03 10:12
Not really. Related but not the same. This issue is about specifying custom and bundle resources outside the project root.

**Comment by britzl** [comment] 2022-12-03 10:14
Hmm, I mention absolute paths in the first post, but my example doesn't really look like an absolute path...

It didn't really make sense to use absolute paths though.... Let's close this end keep the other one

**Closed** 2022-12-03 10:16 UTC
Labels: bug, engine
