### ISSUE TITLE
`game_wasm.js` is no longer minified

### ISSUE THREAD

**Issue by AGulev** [defold/defold#8831] opened 2024-04-23 06:17 UTC
**Describe the bug (REQUIRED)**
It seems like game_wasm.js is no longer minified after emscripten update, more info is available on forum: 
https://forum.defold.com/t/defold-1-8-0-beta/76535/78?u=agulev

**Defold version (REQUIRED):**
  - Version 1.8.0

**Comment by ekharkunov** [comment] 2024-05-02 08:13
I researched on test project (simple .c file) and got following results:
* pass only -O3 option to emcc command produce minified result
* if add LEGACY_VM_SUPPORT or MIN_FIREFOX_VERSION=34, MIN_SAFARI_VERSION=90000, etc - result isn't minified.
* pass `--closure=1` doesn't help. Result still non-minified.
When I digging deeper I found that `--closure=1` option doesn't help because `closure-compiler` runs before `babel` compiler https://github.com/emscripten-core/emscripten/blob/3.1.55/tools/link.py#L2146-L2153.
Main problem is running babel compiler when we need to support old browser. Initially babel compiler was introduced in 3.1.51 (https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3151---121323).

There are two workarounds:
1. Modify emscripten code and run closure-compiler after babel compiler. It need to add additional options to waf_dynamo.py and build_input.yml
2. Add `babel-preset-minify` package to emscripten and modify emscripten code in following way:
```
cmd = shared.get_npm_cmd('babel') + [filename, '-o', outfile, '--presets', '@babel/preset-env,babel-preset-minify',  '--config-file', config_file]
```

Issue at emscripten project:
https://github.com/emscripten-core/emscripten/issues/21881

**Comment by ekharkunov** [comment] 2024-05-03 07:45
Fixes were made https://github.com/emscripten-core/emscripten/pull/21882. Waits for official release.

**Comment by aglitchman** [comment] 2024-08-29 14:05
I want to say that I like that _wasm.js is not minified. Because it becomes easier to understand where the problem is in JS code when developing native extensions.

So it would be cool if emscripten's minifier added a .map file to the minified .js file to get nice error reports.

My current workaround is to use `uglifyjs` - it produces a good result, the final size is about 200kb (zipped 50kb). The setup is as follows:
```bash
uglifyjs "NAME_wasm.js" --compress --mangle --webkit --source-map url=NAME_wasm.js.map,includeSources=true --output "NAME_wasm.js"
```

**Comment by ekharkunov** [comment] 2024-09-12 09:26
Fixed by updating Emscripten https://github.com/defold/defold/pull/9413

**Closed by ekharkunov** 2024-09-12 09:26 UTC
Labels: bug, engine, html5

**Comment by ekharkunov** [comment] 2024-09-12 09:27
> I want to say that I like that _wasm.js is not minified. Because it becomes easier to understand where the problem is in JS code when developing native extensions.
> 
> So it would be cool if emscripten's minifier added a .map file to the minified .js file to get nice error reports.
> 
> My current workaround is to use `uglifyjs` - it produces a good result, the final size is about 200kb (zipped 50kb). The setup is as follows:
> 
> ```shell
> uglifyjs "NAME_wasm.js" --compress --mangle --webkit --source-map url=NAME_wasm.js.map,includeSources=true --output "NAME_wasm.js"
> ```

Minification controlled by optimization level flag. By default engine builds with -O3.
