### ISSUE TITLE
First time debug error

### ISSUE THREAD

**Issue by ufgo** [defold/defold#5503] opened 2021-01-26 03:45 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-21T11:58:21.335092</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6a2045f58d54c0cad54994021954856dd1425178</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3bda606e15924ee99b19e1edc2b65652"'>3bda606e15924ee99b19e1edc2b65652</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 442.59</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2021-01-28 07:04
```
java.net.PlainSocketImpl.waitForConnect.class java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.waitForConnect(PlainSocketImpl.java)
    at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:591)
    at editor.debugging.mobdebug$try_connect_BANG_.invokeStatic(mobdebug.clj:328)
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:333)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by JCash** [comment] 2021-02-19 13:29
Duplicate of #5471

**Closed** 2021-02-19 14:21 UTC
Labels: debugger, editor
