### ISSUE TITLE
Can't create APK file

### ISSUE THREAD

**Issue by zozzy123** [defold/defold#5272] opened 2020-10-13 13:19 UTC
When I try to bundle for APK file, it creates an AAB one. 
Like it doesn't mater I choose APK or AAB..

<hr/>

<table>
<tr><td>Build time</td><td>2020-10-07T09:43:17.766716</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18e7da2c4eea5d37a154d3bde088e161fc49186e</td></tr>
<tr><td>Defold engine sha</td><td>8f3e864464062e1b35c207521dc65dfd77899cdf</td></tr>
<tr><td>Defold version</td><td>1.2.174</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 22.20.16.4836</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-10-13 14:18
I'm not able to reproduce this. You're sure you are setting the bundle format to APK?

**Comment by zozzy123** [comment] 2020-10-14 06:19
Yeah I'm pretty sure. I'm adding caps.

![bundle1](https://user-images.githubusercontent.com/55736765/95950956-395a3700-0dfe-11eb-9984-d55a52fc94e1.jpg)

![bundle no keystore](https://user-images.githubusercontent.com/55736765/95950948-36f7dd00-0dfe-11eb-89f7-8402c18993d5.jpg)

![bundle2](https://user-images.githubusercontent.com/55736765/95950955-395a3700-0dfe-11eb-911d-7de9f34bce21.jpg)

![bundle3](https://user-images.githubusercontent.com/55736765/95950954-38c1a080-0dfe-11eb-963a-44450be42cba.jpg)

![bundle4](https://user-images.githubusercontent.com/55736765/95950952-38290a00-0dfe-11eb-98e9-a051cbff099e.jpg)

**Comment by britzl** [comment] 2020-10-14 09:43
The bundle process will always generate an AAB file and from the AAB file it will generate an APK. I wonder if something goes wrong in that last step? You get no error in the console?

Could you please try to start the Defold editor from a windows terminal/command prompt and check if there's something in the command prompt which could indicate a problem when bundling?

Also, if you feel up to it you could try to bundle from the command line. It requires JDK 11 installed on your machine and that you run our command line tool bob (https://defold.com/manuals/bob/). This minimal command line should generate an APK in the `projectroot/build/default/` folder:

```
java -jar bob.jar -v --archive --platform=armv7-android --bundle-format=apk build bundle
```

**Comment by zozzy123** [comment] 2020-10-14 15:54
No error msg.. Can't find bob.jar in download page either. Any direct link to bob.jar?

**Comment by britzl** [comment] 2020-10-14 21:47
> Any direct link to bob.jar?

Yes, you can download bob.jar from http://d.defold.com/stable/

**Comment by britzl** [comment] 2020-10-20 06:40
How did it go @zozzy123 ?

**Comment by britzl** [comment] 2020-12-17 21:53
I'm still unable to reproduce and no one else has reported this problem. Closing.

**Closed by britzl** 2020-12-17 21:53 UTC
Labels: android, bug, editor, more info
