### ISSUE TITLE
Add bundle ios in windows.

### ISSUE THREAD

**Issue by d954mas** [defold/defold#5619] opened 2021-03-04 20:26 UTC
Bob can build ios in windows.

But no such menu in editor.

https://forum.defold.com/t/vote-on-your-favourite-issues-for-2021/66978/10

**Comment by d954mas** [comment] 2021-03-04 20:56
Not sure, that it is realy worked on windows) 
https://forum.defold.com/t/bob-build-ios-on-windows/67709

**Comment by AGulev** [comment] 2022-08-22 11:26
related https://github.com/defold/defold/issues/3735

**Comment by AGulev** [comment] 2023-04-20 09:38
related https://github.com/defold/defold/issues/3331

**Comment by AGulev** [comment] 2024-05-03 21:07
closed as duplicate of https://github.com/defold/defold/issues/3331 (better explained there)

**Closed by AGulev** 2024-05-03 21:07 UTC
Labels: feature request, editor, bob, ios
