### ISSUE TITLE
Linux jogamp exception

### ISSUE THREAD

**Issue by xxxKfkxxx** [defold/defold#4846] opened 2020-05-26 13:45 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-05-26T07:18:13.818208</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>2770594b5f0415dcd08dd1a83d9f3bfdf1f8a5cc</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a42743e94b0446d2bcda60df916121cd"'>a42743e94b0446d2bcda60df916121cd</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-28-generic</td></tr>
<table>

**Comment by britzl** [comment] 2020-05-26 21:28
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')

**Comment by britzl** [comment] 2020-06-21 10:15
Duplicate of #4851

**Closed by britzl** 2020-06-21 10:15 UTC
Labels: bug, editor, linux
