### ISSUE TITLE
Change mass of collision object at runtime (DEF-3930)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3149] opened 2019-05-23 10:30 UTC
Requested on the forum:

https://forum.defold.com/t/how-to-change-mass-of-collision-object-def-3930/51340

**Comment by AGulev** [comment] 2024-01-27 14:50
Investigating this question a little bit more, I found that this issue isn't a duplicate of another one

**Closed** 2024-01-29 07:37 UTC
Labels: task, engine, physics
