### ISSUE TITLE
Defold Error

### ISSUE THREAD

**Issue by itamarle-ma** [defold/defold#7592] opened 2023-04-19 11:32 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-03-31T16:41:03.171182</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>36f9bd22f8a5d442728986d23a96794004ed0640</td></tr>
<tr><td>Defold engine sha</td><td>f5e114aaebe25c5242db5f0066af2f5189c09f99</td></tr>
<tr><td>Defold version</td><td>1.4.4</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"62c21d609db14e6a81506d65aa2d2fda"'>62c21d609db14e6a81506d65aa2d2fda</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.2.1</td></tr>
<table>

**Comment by britzl** [comment] 2023-04-19 14:16
Duplicate of https://github.com/defold/defold/issues/7567

**Closed by britzl** 2023-04-19 14:16 UTC
