### ISSUE TITLE
Editor tabs sporadically become unclickable when switching tabs

### ISSUE THREAD

**Issue by rcarag** [defold/defold#5456] opened 2021-01-08 03:21 UTC
**Describe the bug (REQUIRED)**
When 2 or more editor tabs are open, switching between tabs by clicking on the tab headers sometimes causes tabs to become unclickable.

**To Reproduce (REQUIRED)**
1. Create a new project from the "Side scroller tutorial" template.
2. Observe the README.md tab is open in the editor by default.
3. Open the `/spaceship/spaceship.script` file. Observe the spaceship.script tab is now open in the editor. Beside it is the inactive README.md tab.
4. Keep switching between the README.md tab and the spaceship.script tab by clicking on their tab headers. (This may take less than 10 tab switches, sometimes more, or sometimes it won't happen at all). Eventually one of the tabs will become unresponsive and unclickable. The only way to activate the unresponsive tab is by opening it via the Assets pane or using the `File > Open Assets...` command. From there, the tab can be closed using the `File > Close` command.
5. Repeat the process by opening another file, then keep switching tabs again by clicking on the tab headers. One of the tabs will eventually become unresponsive and unclickable again.

**Expected behavior (REQUIRED)**
The expected behavior is to be able to freely switch between any open editor tabs, without them becoming unresponsive.

**Defold version (REQUIRED):**
  - Version 1.2.177

**Platforms (REQUIRED):**
 - Platforms: macOS
 - OS: macOS Big Sur 11.1
 - Device: MacBook Pro 2017 13"

**Minimal repro case project (OPTIONAL):**
N/A

**Logs (OPTIONAL):**
N/A

**Workaround (OPTIONAL):**
Switch tabs using the ctrl+tab/ctrl+shift+tab keyboard shortcuts, or use the `File > Open Assets...` command (cmd+p).

**Screenshots (OPTIONAL):**
N/A

**Additional context (OPTIONAL):**
I'm new to Defold and I encountered the bug while I was following the Side scroller tutorial. I also created a project using the "Mobile game" template and encountered the same issue.

**Comment by ufgo** [comment] 2022-09-12 08:33
mac os 12.5.1 - same problem 😒

**Comment by britzl** [comment] 2022-09-12 09:48
> mac os 12.5.1 - same problem 😒

Does the editor log provide any information when this happens?

https://defold.com/manuals/editor/#editor-logs

**Comment by Jerakin** [comment] 2022-11-22 11:14
Happens _very_ frequently for me. Usually only takes ~10 tab switches for me for it to happen.

Checked the logs and the behaviour doesn't cause additional logging to happen.
____ 
macOS 11.6.7
Defold 1.4.0

**Comment by AGulev** [comment] 2024-04-29 08:52
I can't reproduce it lately (1.7.0, 1.8.0), can you?

**Comment by AGulev** [comment] 2024-04-29 08:52
info from https://github.com/defold/defold/issues/6030

>Description
Often tab doesn't respond to clicks on it.
I can't tell how to reproduce it with 100% chance. I experience this bug every 20-30 minutes during my work.
I suspect that problem is only on macOS

>How does it look: tab doesn't respond to clicks. I can't close it, can't select it, can't move it.
This bug reproduces on every Defold Editor version (on each 1.2.179 -- 1.2.186, for example)

>Workaround
No matter what type of file opened in this tab. It could happen with any type - script, go, collection.
I deal with this bug by selecting this tab from "open assets" (command+P) window and then closing this tab by "close" (command+W). Then I can open this file again - and everything will work fine until this bug occurs again.  

>I recorded a [video](https://www.youtube.com/watch?v=9vu9TQqJEEk) to represent how does it look
Description what's going on on the video:
0:00 - 0:10 Tab with keyboardController.script doesn't respond on any clicks. I can't select neither close it. Other tabs work fine
0:10 - 0:13 I can select this tab by "open assets" window
0:14 - 0:17 Ok, I can select it, but tab is still frozen - if I go to another tab I can't select my frozen tab again
0:18 - 0:27 Only after selecting by "open assets" and close by "close" menu - I can open this file again and deal with this bug

**Comment by DestyNova** [comment] 2024-04-29 16:55
> I can't reproduce it lately (1.7.0, 1.8.0), can you?

I also can't reproduce it in 1.7.0. Haven't updated to 1.8.0 but I'd imagine it is solved.

**Comment by AGulev** [comment] 2024-05-02 11:27
I think this issue was solved with one of JavaFX updates
feel free to reopen it if you get it again in new defold fersion

**Closed by AGulev** 2024-05-02 11:27 UTC
Labels: bug, editor, javafx
