### ISSUE TITLE
Inexplicable java error that turns out to be a circular dependency problem - need better error message

### ISSUE THREAD

**Issue by rgrams** [defold/defold#5909] opened 2021-06-29 15:02 UTC
### Expected behaviour
The error message actually tells you what's wrong, and ideally how to fix it.

Also I'm not sure if the error should trigger the java error popup. Probably it should be printed in the console like other user errors.

### Actual behaviour
The error message is completely inexplicable.

### Steps to reproduce
Add two lua modules that require each other.

The same or a similar error may be caused by a factory that reproduces itself? https://forum.defold.com/t/cycle-detected-error-after-adding-new-objects-to-map-solved/66249

<hr/>

<table>
<tr><td>Build time</td><td>2021-06-20T14:04:19.855683</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>db55f3faa6347a66d60715dddd9663687d54ceed</td></tr>
<tr><td>Defold engine sha</td><td>f77b7f655a0ba68462f6c33604bed7000018735f</td></tr>
<tr><td>Defold version</td><td>1.2.183</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"db8a6b73a0814a21bf82f60e5e0f2e83"'>db8a6b73a0814a21bf82f60e5e0f2e83</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) UHD Graphics 630 (CFL GT2)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 20.2.6</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-77-generic</td></tr>
<table>

**Comment by rgrams** [comment] 2021-06-29 15:15
It turns out it's just a circular lua require problem. The error in the editor should specify what the error actually is, and what files are causing it.

**Comment by britzl** [comment] 2022-03-22 07:32
Duplicate of https://github.com/defold/defold/issues/4893. Closing.

**Closed by britzl** 2022-03-22 07:32 UTC
Labels: bug, editor
