### ISSUE TITLE
go.property crash the editor when I use vscode

### ISSUE THREAD

**Issue by Lambipapp** [defold/defold#6043] opened 2021-09-12 18:33 UTC
### Expected behaviour
I expect that I can tab freely between the editor and VSCODE when using it as my IDE.

### Actual behaviour
It seems like the editor breaks when I add go.property() to some scripts. (`blink_on_move` ) is my property
The error is: _clojure.lang.ExceptionInfo: Duplicate node key `blink_on_move` from :editor.code.script/ScriptPropertyNode_

This has happened in multiple projects with different scripts for me the last few days

### Steps to reproduce
I have not identified the exact cause, but it seems to be related to the properties.

<hr/>

<table>
<tr><td>Build time</td><td>2021-09-09T20:27:01.070836</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>71d178069a8fa37a4a52d3b44b98bd7596197e4e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"686416c2d46e4a11aa458d51af4915db"'>686416c2d46e4a11aa458d51af4915db</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 471.96</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Lambipapp** [comment] 2021-09-12 18:46
correction:

It does not crash the entire editor. A popup with the error appears and some of the tabs in the inspector are un-responsive.

**Comment by britzl** [comment] 2021-09-12 19:57
```
dynamo.graph$collect_overridden_properties$fn__7290.invoke.class clojure.lang.ExceptionInfo: Duplicate node key `blink_on_move` from :editor.code.script/ScriptPropertyNode
    at dynamo.graph$collect_overridden_properties$fn.invoke(graph.clj:1262)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at dynamo.graph$collect_overridden_properties.invokeStatic(graph.clj:1276)
    at editor.defold_project$perform_resource_change_plan$fn.invoke(defold_project.clj:439)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:442)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:540)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:709)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:442)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:431)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:84)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment] 2021-09-12 19:58
I haven't experienced this issue myself. If you do find a clear set of steps to reproduce then please share them here!

**Comment by britzl** [comment] 2022-12-02 20:17
Unable to reproduce. No additional information provided. Closing.

**Closed by britzl** 2022-12-02 20:17 UTC
Labels: bug, more info, editor
