### ISSUE TITLE
The arabian font is wrong shape

### ISSUE THREAD

**Issue by ufgo** [defold/defold#7475] opened 2023-03-16 11:26 UTC
I’ve tried different fonts, letter spacing and line spacing, but the result is the same.
Left-Defold, right - google font site:
![46f825761c661008eb7545e97837012715c2bab7](https://user-images.githubusercontent.com/21050233/225602885-a5a5d710-34da-4a67-9dc5-f830d4029e17.png)

**Comment by AGulev** [comment] 2024-03-19 16:28
Closed as duplicate of https://github.com/defold/defold/issues/4900

**Closed by AGulev** 2024-03-19 16:28 UTC
Labels: bug, font

**Comment by nightblade9** [comment] 2024-10-04 04:09
Not really a duplicate. Right-to-left is just one part of what Arabic needs. There's also letter shaping, diacritical marks, etc.
