### ISSUE TITLE
Request for full-screen support in the editor.

### ISSUE THREAD

**Issue by StarkyFan** [defold/defold#4878] opened 2020-06-04 18:02 UTC
This is a simple request, but it' s important for me. I' d like Defold to have a full-screen mode in the editor. Like pressing f11. Thanks.

**Comment by britzl** [comment] 2020-06-05 06:42
This is for Windows right?

**Comment by StarkyFan** [comment] 2020-06-05 09:59
Yes, for Windows

**Comment by AGulev** [comment] 2023-09-30 14:32
duplicate of https://github.com/defold/defold/issues/4834

**Closed by AGulev** 2023-09-30 14:32 UTC
Labels: feature request, editor, windows
