### ISSUE TITLE
Was typing some code, and it threw this error

### ISSUE THREAD

**Issue by alexander-e-andrews** [defold/defold#5115] opened 2020-08-20 02:20 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-19T08:50:25.937762</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4b6b1d22762865cf848564903cce9b80f761807a</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"b6094ad5ade142be81493690f891761c"'>b6094ad5ade142be81493690f891761c</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon (TM) R9 390 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context 20.1.4 26.20.15017.1005</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-08-20 06:16
class java.lang.NullPointerException
javafx.scene.control.skin.TabPaneSkin in perfromDrag at line 2096
javafx.scene.control.skin.TabPaneSkin in handleHeaderDragged at line 2051

Duplicate of https://github.com/defold/defold/issues/4852

**Closed by britzl** 2020-08-20 06:16 UTC
Labels: bug, editor, javafx
