### ISSUE TITLE
Editor crash when setting GUI template node to self

### ISSUE THREAD

**Issue by GriffinSego** [defold/defold#9273] opened 2024-08-08 00:00 UTC
### Expected behaviour

The current GUI should not be shown in the list of valid GUI templates.

### Actual behaviour

The current GUI is shown in the list, which is opened when clicking on new node, template. Selecting the current node causes an infinite loop which crashes/bricks the editor unleashing the beach ball of doom on macOS.

### Steps to reproduce

Make a new GUI element
Make a new Node of type Template inside of it
Select the new GUI element

<hr/>

<table>
<tr><td>Build time</td><td>2024-07-30T08:33:00.879171</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>075b790f01b4b3d2074a7fd9dcf04b20af309eb0</td></tr>
<tr><td>Defold engine sha</td><td>691478c02875b80e76da65d2f5756394e7a906b1</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>GPU</td><td>Apple M1</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 86</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.0</td></tr>
<table>

**Comment by AGulev** [comment] 2024-08-08 06:30
duplicate of https://github.com/defold/defold/issues/6568

**Closed** 2024-08-12 07:08 UTC
Labels: bug, editor
