### ISSUE TITLE
com.jogamp.opengl.GLException: JavaFX Application Thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.hw], current: 3.0 (Compat profile, compat[ES2], FBO, hardware) - 3.0 Mesa 20.0.8

### ISSUE THREAD

**Issue by Lucho431** [defold/defold#5444] opened 2021-01-02 19:00 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-08-27T04:43:39.910109</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96c820fb9fb9c3d6ddec975e5e1dde4762b0228d</td></tr>
<tr><td>Defold engine sha</td><td>dedf1ed10d96c92df6e361f5494531c79af4c1cf</td></tr>
<tr><td>Defold version</td><td>1.2.172</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"326678c7a9d7462f96ef56dda3747026"'>326678c7a9d7462f96ef56dda3747026</a></td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-58-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-01-03 00:12
Please give this a try: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by britzl** [comment] 2022-12-02 19:42
Duplicate of https://github.com/defold/defold/issues/6053

**Closed by britzl** 2022-12-02 19:42 UTC
Labels: bug, editor
