### ISSUE TITLE
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.game-object/GameObjectNode and output :build-targets (not (contains? (:in-production evaluation-context) [node-id label]))

### ISSUE THREAD

**Issue by Maybehollow** [defold/defold#6953] opened 2022-09-05 14:48 UTC
### Expected behaviour
playtesting the game
### Actual behaviour
report popup
### Steps to reproduce
I just uploaded my code to github for the first time after replicating my deleted enemy scripts but it ran fine before
<hr/>

<table>
<tr><td>Build time</td><td>2022-06-07T07:41:48.766215</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c2ab1630e34f1311d8340d81494cf5317d25fe16</td></tr>
<tr><td>Defold engine sha</td><td>c2ab1630e34f1311d8340d81494cf5317d25fe16</td></tr>
<tr><td>Defold version</td><td>1.3.3</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"efacfd5c06b6472a8866ec3f9cdd6486"'>efacfd5c06b6472a8866ec3f9cdd6486</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) R4 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.14830 Compatibility Profile Context 21.4.1 27.20.21002.112</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-09-05 17:52
Duplicate of https://github.com/defold/defold/issues/6724

**Closed by britzl** 2022-09-05 17:52 UTC
