### ISSUE TITLE
failure to copy files

### ISSUE THREAD

**Issue by rob-miskimmin** [defold/defold#8952] opened 2024-05-19 11:18 UTC
### Expected behaviour
Copy Image files to project
### Actual behaviour
Alert appeared on screen
### Steps to reproduce
Try to drag Image folder containing image files into project
<hr/>

<table>
<tr><td>Build time</td><td>2024-05-15T15:14:00.109381</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c99258874cf2e19c04a1025974a403df8c3f4dfc</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2b02ec76e0664087aeb4f7611ef94740"'>2b02ec76e0664087aeb4f7611ef94740</a></td></tr>
<tr><td>GPU</td><td>Apple M2</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.4.1</td></tr>
<table>

**Comment by AGulev** [comment] 2024-05-19 11:59
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1017)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:275)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1326)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3171)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3240)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:4003)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1893)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2711)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:430)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
    ```

**Comment by AGulev** [comment] 2024-05-19 12:00
duplicate of https://github.com/defold/defold/issues/5875

**Closed** 2024-05-20 07:26 UTC
