### ISSUE TITLE
Problem while creating atlas

### ISSUE THREAD

**Issue by juliovivian** [defold/defold#6612] opened 2022-05-16 22:46 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-12T08:33:53.754556</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ff88055bcb5b23c950ff2877c10e7adb9843a427</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"805e2f8067054f65a725aff38981a576"'>805e2f8067054f65a725aff38981a576</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 400 (BSW)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 22.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.38-1-MANJARO</td></tr>
<table>

**Comment by britzl** [comment] 2022-05-17 06:12
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:194)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1160)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1157)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1128)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:843)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1507)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1507)
    at editor.app_view$open_resource$fn.invoke(app_view.clj:1737)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment] 2022-05-17 06:15
Please see Linux FAQ https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:15 UTC
Labels: bug, editor, javafx
