### ISSUE TITLE
Editor GL: ClassCastException jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2

### ISSUE THREAD

**Issue by hevrard** [defold/defold#5475] opened 2021-01-16 14:40 UTC
### Expected behaviour

Once side-scroller tuto project is loaded, visit `File->Open Assets...` menu, then interact with the new dialog window.

### Actual behaviour

Java (Clojure) exception:

```
2021-01-16 14:27:57.856 ERROR default    editor.error-reporting - {:line 110}
java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
	at editor.gl$gl_clear.invokeStatic(gl.clj:191)
	at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
	at editor.scene$fn__42304.invokeStatic(scene.clj:1327)
	at editor.scene$fn__42304.invoke(scene.clj:1325)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:384)
	at editor.scene$PreviewView$behavior$frame$fn__42377.invoke(scene.clj:1334)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.scene$PreviewView$behavior$frame.invokeStatic(scene.clj:1334)
	at editor.scene$PreviewView$behavior$frame.invoke(scene.clj:1334)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at editor.scene$PreviewView$behavior$image$fn__42507.invoke(scene.clj:1334)
	at internal.node$trace_expr.invokeStatic(node.clj:41)
	at editor.scene$PreviewView$behavior$image.invokeStatic(scene.clj:1334)
	at editor.scene$PreviewView$behavior$image.invoke(scene.clj:1334)
	at clojure.lang.Var.invoke(Var.java:393)
	at internal.node.NodeImpl.produce_value(node.clj:283)
	at internal.node$node_value.invokeStatic(node.clj:425)
	at internal.system$node_value.invokeStatic(system.clj:353)
	at dynamo.graph$do_node_value.invokeStatic(graph.clj:807)
	at dynamo.graph$node_value.invokeStatic(graph.clj:810)
	at editor.app_view$gen_tooltip$reify__48214.handle(app_view.clj:1813)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
... etc ...
```

### Steps to reproduce

Visit `File->Open Assets` menu (?)

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-16T10:46:43.704162</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3d2d4932d02dabc7e57fd25fac275b0a6dc59158</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2c4a7003db78421ab79da24752723df4"'>2c4a7003db78421ab79da24752723df4</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.1.9</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>an up-to-date Debian-based distro</td></tr>
<table>

**Comment by britzl** [comment] 2021-01-16 15:06
Please give this a try:

https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by britzl** [comment] 2021-02-08 22:35
Closing as duplicate of https://github.com/defold/defold/issues/4851

**Closed by britzl** 2021-02-08 22:35 UTC
Labels: editor, linux
