### ISSUE TITLE
Tilemap viewport culling

### ISSUE THREAD

**Issue by Domarius** [defold/defold#8744] opened 2024-04-01 00:38 UTC
For tilemaps that represent large levels like in Mario or Sonic, some sort of system that makes sure only the tiles on or near the screen are being rendered by the video card, rather than every tile in the level.

It's a fairly common situation that could possibly have a generic solution.

Although I will say that it's likely a developer will have to make something a bit more involved anyway which involves having nearby objects loaded / activated as the player approach, since this culling would also involve other entity behaviours in the game.  I would think a "chunking" approach would be appropriate, where the level is broken up into broadly chunked "scenes" which are loaded / unloaded around the player as they move through the level, that solve all of the above, including rendering performance.  An engine level implementation of this kind of higher level solution is possible, though even more work of course. I think the [LDtk](https://ldtk.io/) editor lets you develop levels in this way.

**Comment by AGulev** [comment] 2024-04-02 07:58
duplicate of https://github.com/defold/defold/issues/6938

**Closed** 2024-06-06 09:45 UTC
Labels: feature request, engine
