### ISSUE TITLE
Setting parent to a child object using another object as its parent breaks child object's position.

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#9111] opened 2024-06-20 22:19 UTC
**Describe the bug (REQUIRED)**
Setting parent to a child object using another object as its parent breaks child object's position.
With a collision between child and parent, if child sets object #2 as its parent, a position bug occurs where
child goes into outer space.

**To Reproduce (REQUIRED)**
In the test project, walk or jump on the bee

**Expected behavior (REQUIRED)**
Object one should become object's child and move as object two moves.

**Defold version (REQUIRED):**
  - Version 1.9.0 Alpha

**Platforms (REQUIRED):**
 - Windows
 - Windows 10 Pro
 - Emulated / defold window

**Minimal repro case project (OPTIONAL):**
[SetParentBug.zip](https://github.com/user-attachments/files/15920700/SetParentBug.zip)

**Update** Anything that gets `set_parent()` placed on it, and it is the child object, it jumps far away and the x value will continue to increase with no force applied. Verified thru debug.

**Comment by JustAPotota** [comment] 2024-06-20 22:40
This is intended behavior. You have the `keep_world_transform` parameter of [`go.set_parent()`](https://defold.com/ref/stable/go/#go.set_parent:[id]-[parent_id]-[keep_world_transform]) set to `false`, so the object won't be at the same spot in world space. For example, if the player is at (100,100) and the bee is at (50,50), then the player will be moved to (100,100) _relative to the bee_, which would be (150,150) relative to the world. This is why the player seems to teleport into outer space.

Setting `keep_world_transform` to `true` would compensate for that and keep the player at (100,100) relative to the world by setting its position to (50,50) relative to the bee.

**Comment by jcbk101** [comment] 2024-06-20 22:44
> This is intended behavior. You have the `keep_world_transform` parameter of [`go.set_parent()`](https://defold.com/ref/stable/go/#go.set_parent:%5Bid%5D-%5Bparent_id%5D-%5Bkeep_world_transform%5D) set to `false`, so the object won't be at the same spot in world space. For example, if the player is at (100,100) and the bee is at (50,50), then the player will be moved to (100,100) _relative to the bee_, which would be (150,150) relative to the world. This is why the player seems to teleport into outer space.
> 
> Setting `keep_world_transform` to `true` would compensate for that and keep the player at (100,100) relative to the world by setting its position to (50,50) relative to the bee.

That is interesting because My game has been working with "true" since I created it. When I went to 1.9.0 (tilemap fixed version) it began to jump. This happens with both `false` and `true` for world position. 1.8.0 still works correctly.

It must be the version of 1.9.0 I am using.

**Comment by JustAPotota** [comment] 2024-06-20 22:46
> When I went to 1.9.0 (tilemap fixed version) it began to jump.

What do you mean?

**Comment by jcbk101** [comment] 2024-06-20 22:53
> > When I went to 1.9.0 (tilemap fixed version) it began to jump.
> 
> What do you mean?

I caused a lot of confusion with a tilemap bug, but the team figured it out. I was sent a version of 1.9.0 to test. So I have been using that version. In this version is where set parent is broken. Not sure if the live test version has this bug.
I can only assume it does.

**Comment by AGulev** [comment] 2024-06-24 08:26
Physics works in world coordinate space, so it’s impossible to use hierarchies of game objects with collision objects on them because the physics engine will set world coordinates, replacing your local coordinates.

By creating such a hierarchy, you generate conflicting position changes through `go.animate()` and the physics forces of the player object. This results in unpredictable behavior and teleportation because world coordinates from the physics object are applied to the local coordinates of the player.

**Comment by jcbk101** [comment] 2024-06-24 15:05
> Physics works in world coordinate space, so it’s impossible to use hierarchies of game objects with collision objects on them because the physics engine will set world coordinates, replacing your local coordinates.
> 
> By creating such a hierarchy, you generate conflicting position changes through `go.animate()` and the physics forces of the player object. This results in unpredictable behavior and teleportation because world coordinates from the physics object are applied to the local coordinates of the player.

Thanks for the comment. If you wish to test this issue, you can use either the zip file in this thread or the one I posted in [this thread](https://github.com/defold/defold/issues/9089#issuecomment-2174687474).
In the latter, jump on or fall onto the moving platform and watch what happens. Example uses `go.set_parent("/player", go_get_id(), true)`, and has been doing so since I first implemented moving platforms. This code works in 1.8.0, but not in 1.9.0

If you'd like a video, one can be provided.

@britzl What other information do you require. I will be happy to provide that information. 

Thank you all for doing such a wonderful job.

**Comment by AGulev** [comment] 2024-06-24 15:11
@jcbk101 this exact issue happens in all Defold versions, again that's how physics engine works. All your objects with collisionobject on it should be in the collection root

https://github.com/defold/defold/assets/2209596/75f4b227-3aae-4cef-961b-ac0d0eb1eeec

**Comment by jcbk101** [comment] 2024-06-24 15:18
> @jcbk101 this exact issue happens in all Defold versions, again that's how physics engine works. All your objects with collisionobject on it should be in the collection root
> 
>  CleanShot.2024-06-24.at.17.09.49.mp4

I see. In this video, is world space set to true or false? 
I will look again as its strange that my unchanged project now is broken with 1.9.0 and all previous versions I used work. I feel like I am not helping the cause. I will digress and figure somthing out. Thanks, and keep up the great work

**Comment by AGulev** [comment] 2024-06-24 15:37
1.8.0 false:

https://github.com/defold/defold/assets/2209596/b70770a6-1789-4e3b-b36e-512cae066515

1.8.0 true:

https://github.com/defold/defold/assets/2209596/d0d8aa18-6385-4a37-ba1e-cd6d7a868e15

1.9.0 false:

https://github.com/defold/defold/assets/2209596/057fffcf-884d-4836-8893-77f5afe4704f

1.9.0 true:


https://github.com/defold/defold/assets/2209596/cacf56c9-a9ef-4f20-812c-5b978cd840cb

**Comment by jcbk101** [comment] 2024-06-24 19:32
Okay, I just made it home to test, and I immediately noticed that you are running build 6-14-2024. I was running build 6-20-2024. I have even provided a 6-24-2024 build for you to view.

Build 6-14-2024, 1.9.0 true:
https://github.com/defold/defold/assets/75145117/41e2fd13-a69c-4c24-8bf0-e748ee34c470

Build 6-20-2024,1.9.0 true:
https://github.com/defold/defold/assets/75145117/ca4347ea-f459-4623-b944-882bf36e04d9

Build 6-24-2024,1.9.0 true:
https://github.com/defold/defold/assets/75145117/717ccd40-53e3-42d4-be24-351b9e8c7a1d

**Comment by AGulev** [comment] 2024-06-24 19:51
Maybe it's related to the fix @britzl did https://github.com/defold/defold/commits/dev/

But anyway, it is not something will work. Even on your first video I see that if you run a bit you just fell down through the floor. Again, you can't use hierarchies of object with collisionibjects

**Comment by jcbk101** [comment] 2024-06-24 19:55
> Maybe it's related to the fix @britzl did [95af99c](https://github.com/defold/defold/commit/95af99c5d8777367b1be5884ff6be5e764d061e1)
> 
> But anyway, it is not something will work. Even on your first video I see that if you run a bit you just fell down through the floor. Again, you can't use hierarchies of object with collisionibjects

Only feature that uses parenting are my moving platforms. I tend to find other ways of handling these things. Since I already implemented a FS Machine, I can create a platform state. Thanks, and hope the next release drops soon. Tilemap culling might be my answer to my RPG maps. 👍

**Comment by AGulev** [comment] 2024-06-24 19:56
you can test it if you want

Before fix
d.defold.com/archive/alpha/0bd2acac336f9061726ce4695e21d41d050a6814/alpha/editor2/Defold-x86_64-win32.zip

With fix
d.defold.com/archive/alpha/95af99c5d8777367b1be5884ff6be5e764d061e1/alpha/editor2/Defold-x86_64-win32.zip

**Comment by jcbk101** [comment] 2024-06-24 20:05
> d.defold.com/archive/alpha/0bd2acac336f9061726ce4695e21d41d050a6814/alpha/editor2/Defold-x86_64-win32.zip

That may very well be it. Before works properly, fix is broken.

**Comment by jcbk101** [comment] 2024-07-06 03:28
> you can test it if you want
> 
> Before fix d.defold.com/archive/alpha/0bd2acac336f9061726ce4695e21d41d050a6814/alpha/editor2/Defold-x86_64-win32.zip
> 
> With fix d.defold.com/archive/alpha/95af99c5d8777367b1be5884ff6be5e764d061e1/alpha/editor2/Defold-x86_64-win32.zip

Hello,

I was just wondering if this newly introduced bug will be resolved? This way I know if I should redesign the way moving platforms work in my game. Thank you and have a great day.

**Comment by AGulev** [comment] 2024-07-06 05:59
I think it's not a big at all as I mentioned before:

> Physics works in world coordinate space, so it’s impossible to use hierarchies of game objects with collision objects on them because the physics engine will set world coordinates, replacing your local coordinates.
> 
> By creating such a hierarchy, you generate conflicting position changes through go.animate() and the physics forces of the player object. This results in unpredictable behavior and teleportation because world coordinates from the physics object are applied to the local coordinates of the player.


What do you think @britzl

**Comment by jcbk101** [comment] 2024-07-06 11:46
> I think it's not a big at all as I mentioned before:
> 
> > Physics works in world coordinate space, so it’s impossible to use hierarchies of game objects with collision objects on them because the physics engine will set world coordinates, replacing your local coordinates.
> > By creating such a hierarchy, you generate conflicting position changes through go.animate() and the physics forces of the player object. This results in unpredictable behavior and teleportation because world coordinates from the physics object are applied to the local coordinates of the player.
> 
> What do you think @britzl

Okay. I think it's best I rethink my logic. In some cases, I did have the character bounce when going down and touching a wall at times. That was before the change happened. I will just have find a better way to handle moving platforms. Thanks for your help.

**Comment by britzl** [comment] 2024-07-07 15:00
> I think it's not a big at all as I mentioned before:
> 
> > Physics works in world coordinate space, so it’s impossible to use hierarchies of game objects with collision objects on them because the physics engine will set world coordinates, replacing your local coordinates.
> > By creating such a hierarchy, you generate conflicting position changes through go.animate() and the physics forces of the player object. This results in unpredictable behavior and teleportation because world coordinates from the physics object are applied to the local coordinates of the player.
> 
> What do you think @britzl

I agree. Hierarchies of objects with collision shapes should not be used.

**Comment by AGulev** [comment] 2024-07-07 15:01
I'm closing this ticket then

**Closed by AGulev** 2024-07-07 15:01 UTC
Labels: bug, more info, engine

**Comment by AGulev** [comment] 2024-07-09 09:45
The change that broke your game was reverted in the latest beta
