### ISSUE TITLE
Error when attempting to start debugging due to (probably) cyclic import

### ISSUE THREAD

**Issue by Wistpotion** [defold/defold#7060] opened 2022-10-13 17:26 UTC
### Expected behaviour
The debugger starting. 

### Actual behaviour
An error popping up.

### Steps to reproduce
Currently this happens whenever I attempt to start to debug this game: [unwrapped_ping.zip](https://github.com/defold/defold/files/9779081/unwrapped_ping.zip).
Restarting the editor doesn't make any difference. The error does not happen when I started up a different project, however when (once again) opening the unwrapped_ping project and attempting to start a debugging session the error happens. This time I didn't open any files. I managed to track it down to one line of code:
`local system_function = require "main.computer.system_commands"` second line of file `main/computer/commands/install.lua`.
What the script is doing is that it's importing another script which imports itself. My guess is that Defold does not appreciate that. 

<hr/>

<table>
<tr><td>Build time</td><td>2022-10-03T14:09:22.908840</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>18bcb391eb01d8d4f627df7a53c4cb0302acf403</td></tr>
<tr><td>Defold engine sha</td><td>65e2f79be3b8c99f1999a976399a17eb31a79ff2</td></tr>
<tr><td>Defold version</td><td>1.3.6</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"33bcc98aa8b44506ba08e0ae30a37fbf"'>33bcc98aa8b44506ba08e0ae30a37fbf</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 - Build 26.20.100.7463</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Wistpotion** [comment] 2022-10-13 17:31
I should add that I managed to work around this by structuring my code better and not creating a cyclic import.

**Comment by britzl** [comment] 2022-10-14 06:50
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) (gt/endpoint node-id label)))
    at internal.node$mark_in_production.invokeStatic(node.clj:1323)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:522)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:522)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.code.script$ScriptNode$behavior$build_targets$fn.invoke(script.clj:522)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:522)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:522)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.code.script$ScriptNode$behavior$build_targets$fn.invoke(script.clj:522)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:522)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:522)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.code.script$ScriptNode$behavior$build_targets$fn.invoke(script.clj:522)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:522)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:522)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1622)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1150)
    at editor.game_object$ReferencedComponent$behavior$build_resource$fn.invoke(game_object.clj:288)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.game_object$ReferencedComponent$behavior$build_resource.invokeStatic(game_object.clj:288)
    at editor.game_object$ReferencedComponent$behavior$build_resource.invoke(game_object.clj:288)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at editor.game_object$ReferencedComponent$behavior$build_targets$fn.invoke(game_object.clj:288)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.game_object$ReferencedComponent$behavior$build_targets.invokeStatic(game_object.clj:288)
    at editor.game_object$ReferencedComponent$behavior$build_targets.invoke(game_object.clj:288)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.game_object$GameObjectNode$behavior$build_targets$fn.invoke(game_object.clj:493)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.game_object$GameObjectNode$behavior$build_targets.invokeStatic(game_object.clj:493)
    at editor.game_object$GameObjectNode$behavior$build_targets.invoke(game_object.clj:493)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1150)
    at editor.collection$EmbeddedGOInstanceNode$behavior$build_targets$fn.invoke(collection.clj:242)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.collection$EmbeddedGOInstanceNode$behavior$build_targets.invokeStatic(collection.clj:242)
    at editor.collection$EmbeddedGOInstanceNode$behavior$build_targets.invoke(collection.clj:242)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.collection$CollectionNode$behavior$build_targets$fn.invoke(collection.clj:474)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.collection$CollectionNode$behavior$build_targets.invokeStatic(collection.clj:474)
    at editor.collection$CollectionNode$behavior$build_targets.invoke(collection.clj:474)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_input_values$fn.invoke(node.clj:1166)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1167)
    at editor.game_project$GameProjectNode$behavior$build_targets$fn.invoke(game_project.clj:167)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.game_project$GameProjectNode$behavior$build_targets.invokeStatic(game_project.clj:167)
    at editor.game_project$GameProjectNode$behavior$build_targets.invoke(game_project.clj:167)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$node_value.invokeStatic(node.clj:432)
    at internal.system$node_value.invokeStatic(system.clj:354)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:812)
    at dynamo.graph$node_value.invokeStatic(graph.clj:815)
    at editor.build$build_project_BANG_.invokeStatic(build.clj:43)
    at editor.app_view$build_project_BANG_.invokeStatic(app_view.clj:767)
    at editor.app_view$async_build_BANG_$phase_3_build_project_BANG___47717$run_project_build_on_background_thread_BANG___47718.invoke(app_view.clj:889)
    at editor.app_view$async_build_BANG_$run_on_background_thread_BANG___47697$fn.invoke(app_view.clj:816)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by britzl** [comment] 2022-10-14 06:50
Duplicate of https://github.com/defold/defold/issues/4893

**Closed by britzl** 2022-10-14 06:50 UTC
Labels: bug, editor
