### ISSUE TITLE
I Try to resize a node of GUI

### ISSUE THREAD

**Issue by gdducnguyen** [defold/defold#8460] opened 2024-01-29 04:59 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2023-12-14T13:29:14.859896</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>acef72c1b65ebf1d91d22ec52e055e262d0e1888</td></tr>
<tr><td>Defold engine sha</td><td>4e156b7cf37a380122aada30dacbf2b590ead76b</td></tr>
<tr><td>Defold version</td><td>1.6.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ee76ce57c4154016a5431c7c50f73037"'>ee76ce57c4154016a5431c7c50f73037</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 546.17</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2024-01-30 11:47
```
clojure.lang.RT.uncheckedDoubleCast.class java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "x" is null
    at clojure.lang.RT.uncheckedDoubleCast(RT.java:1559)
    at editor.slice9$vertex_data.invokeStatic(slice9.clj:220)
    at editor.gui$fn.invokeStatic(gui.clj:1012)
    at editor.gui$fn.invoke(gui.clj:1012)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene_renderable_user_data.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at editor.gui$BoxNode$behavior$scene_outline_renderable$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene_outline_renderable.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene_outline_renderable.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at editor.gui$BoxNode$behavior$scene$fn.invoke(gui.clj:998)
    at internal.node$trace_expr.invokeStatic(node.clj:44)
    at editor.gui$BoxNode$behavior$scene.invokeStatic(gui.clj:998)
    at editor.gui$BoxNode$behavior$scene.invoke(gui.clj:998)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1710)
    at internal.node$pull_input_values$fn.invoke(node.clj:1208)
```

**Comment by britzl** [comment] 2024-01-30 11:53
@gdducnguyen can you reproduce the crash?

**Comment by gdducnguyen** [comment] 2024-01-30 17:23
no i can't, i remember that time, i select layout from Default to Portrait and resize a node of GUI, this error spawn

**Comment by AGulev** [comment] 2024-03-09 14:40
It makes it hard to catch since issue can't be reproduced (I can't reproduce it too)
I close it for now, feels free to reopen or open a new one when you have repro case

**Closed by AGulev** 2024-03-09 14:40 UTC
Labels: bug, more info, editor
