### ISSUE TITLE
Tilemap -> add new layer cause error

### ISSUE THREAD

**Issue by selimanac** [defold/defold#9135] opened 2024-06-27 10:25 UTC
### Steps to reproduce
New tilemap -> +Add 2. new layers.

<hr/>

<table>
<tr><td>Build time</td><td>2024-06-26T13:52:59.421023</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>53fa85eb35f32bdb8f96fe3018acba2def54e138</td></tr>
<tr><td>Defold engine sha</td><td>53fa85eb35f32bdb8f96fe3018acba2def54e138</td></tr>
<tr><td>Defold version</td><td>1.9.1</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ff41c50572f54cbf95c5cb1321481bb0"'>ff41c50572f54cbf95c5cb1321481bb0</a></td></tr>
<tr><td>GPU</td><td>Apple M2 Pro</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 88.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>aarch64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>14.5</td></tr>
<table>

**Comment by AGulev** [comment] 2024-06-27 10:27
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':hide-toggle-selected' in context ':workbench' failed at ':enabled?' with message 'Cannot invoke "java.lang.Number.doubleValue()" because "x" is null'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1337)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1353)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1351)
    at editor.ui$make_menu_items.invoke(ui.clj:1351)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1329)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1353)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1351)
    at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1571)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1844)
    at editor.ui$refresh.invokeStatic(ui.clj:1865)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1806)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1930)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
clojure.lang.RT.doubleCast.class java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "x" is null
    at clojure.lang.RT.doubleCast(RT.java:1351)
    at editor.tile_map$fn.invokeStatic(tile_map.clj:442)
    at editor.tile_map$fn.invoke(tile_map.clj:439)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.tile_map$LayerNode$behavior$scene$fn.invoke(tile_map.clj:495)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.tile_map$LayerNode$behavior$scene.invokeStatic(tile_map.clj:495)
    at editor.tile_map$LayerNode$behavior$scene.invoke(tile_map.clj:495)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_input_values$fn.invoke(node.clj:1240)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1241)
    at editor.tile_map$TileMapNode$behavior$scene$fn.invoke(tile_map.clj:633)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.tile_map$TileMapNode$behavior$scene.invokeStatic(tile_map.clj:633)
    at editor.tile_map$TileMapNode$behavior$scene.invoke(tile_map.clj:633)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.app_view$AppView$behavior$active_scene$fn.invoke(app_view.clj:331)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.app_view$AppView$behavior$active_scene.invokeStatic(app_view.clj:331)
    at editor.app_view$AppView$behavior$active_scene.invoke(app_view.clj:331)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1224)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$outline_name_paths_by_selection_state.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_outline_name_paths.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths$fn.invoke(scene_visibility.clj:117)
    at internal.node$trace_expr.invokeStatic(node.clj:46)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths.invokeStatic(scene_visibility.clj:117)
    at editor.scene_visibility$SceneVisibilityNode$behavior$selected_hideable_outline_name_paths.invoke(scene_visibility.clj:117)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:313)
    at internal.node$node_value.invokeStatic(node.clj:474)
    at internal.system$node_value.invokeStatic(system.clj:388)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:889)
    at dynamo.graph$node_value.invokeStatic(graph.clj:892)
    at editor.scene_visibility$fn$fnk58094_positional__58098.invoke(scene_visibility.clj:243)
    at editor.scene_visibility$fn$fnk58094__58110$fn.invoke(scene_visibility.clj:243)
    at editor.scene_visibility$fn$fnk58094__58110.invoke(scene_visibility.clj:243)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
    at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1337)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1353)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1351)
    at editor.ui$make_menu_items.invoke(ui.clj:1351)
    at editor.ui$make_menu_item.invokeStatic(ui.clj:1329)
    at editor.ui$make_menu_items$fn.invoke(ui.clj:1353)
    at clojure.core$keep$fn$fn.invoke(core.clj:7325)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.ui$make_menu_items.invokeStatic(ui.clj:1351)
    at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1571)
    at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1844)
    at editor.ui$refresh.invokeStatic(ui.clj:1865)
    at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1806)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1930)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1968)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by selimanac** [comment] 2024-06-27 11:11
This is a newly created tilemap. 

https://github.com/defold/defold/assets/1324635/e757937d-edc3-486b-9df9-9540438bfb3e

**Comment by AGulev** [comment] 2024-06-27 11:15
Can you reproduce after restarting the editor? Is it possible that you had an error before that and now you are getting this one? 
Because I can't repro this one on my machine 

https://github.com/defold/defold/assets/2209596/bec80841-4d4a-4328-8a3c-af8fca95c159

(I use defold 1.9.0, but I noticed you are talking about 1.9.1, let me check)

**Comment by AGulev** [comment] 2024-06-27 11:17
yes, I can reproduce it now in 1.9.1, thank you!

**Comment by matgis** [comment] 2024-06-27 16:53
A fix has been pushed. Thanks for reporting! ❤️

**Closed by matgis** 2024-06-27 16:53 UTC
Labels: bug, editor
