### ISSUE TITLE
Drag and Drop Error 

### ISSUE THREAD

**Issue by bar1tech** [defold/defold#8039] opened 2023-09-24 16:31 UTC
### Expected behaviour
Expected to drag a png file from the desktop to the Project Assets pane of the editor.

### Actual behaviour
When dragging into the editor from the desktop an error was thrown occurred.  Please see attached screen shot.

### Steps to reproduce
I was working in the Empty Project template and created a folder in the Project Assets pane.  I dragged a png file into the folder and the file did not appear right away. The folder did not have a chevron to allow me to view the file.  I dragged the png again and a Defold pop-up alert box appeared indicating that the file was present.  I dismissed the alert box and saw the chevron appear and viewed the file in the Project Assets pane.

I did not close Defold but focused my work on a separate app to edit a second png file.  When I dragged this second png file into Defold this error was thrown.  Now, I don't remember if I placed the focus on Defold and dragged the second file from the desktop into Defold or if I just dragged directly from the desktop without placing the focus first (if this even matters).  

See the attached screen shot for the error box and my most recent log file from the macOS Application Support > Defold folder.

<img width="611" alt="Screenshot 2023-09-24 at 12 10 31 PM" src="https://github.com/defold/defold/assets/52499915/a54b66ed-3fa1-431b-891e-5d6cf0c439b0">

Attached is my most recent log:
[editor2.2023-09-24.log](https://github.com/defold/defold/files/12709111/editor2.2023-09-24.log)

<hr/>

<table>
<tr><td>Build time</td><td>2023-09-19T14:40:07.484103</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bb52dfb7281ef2b03c3462e9a4205abd69fb11b1</td></tr>
<tr><td>Defold engine sha</td><td>00352cc02f24c12e6081245c0d5fb2e0b263d05e</td></tr>
<tr><td>Defold version</td><td>1.5.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d48e83069d734ecf8ea2f64fa7651582"'>d48e83069d734ecf8ea2f64fa7651582</a></td></tr>
<tr><td>GPU</td><td>Apple M1 Max</td></tr>
<tr><td>GPU Driver</td><td>2.1 Metal - 83.1</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>13.6</td></tr>
<table>

**Comment by bar1tech** [comment] 2023-09-24 16:37
Quick Update:  The error persisted when I again tried to drag the png into Defold.  I closed Defold and reopened it and found that the second png file was already present in the Project Assets pane folder.  I have reattached the log just in case there is any change.
[editor2.2023-09-24.log](https://github.com/defold/defold/files/12709139/editor2.2023-09-24.log)

**Comment by britzl** [comment] 2023-09-25 12:53
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1017)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:275)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1320)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3168)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3237)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:4000)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1890)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2708)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.security.AccessController.doPrivileged(AccessController.java:399)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```

**Comment by britzl** [comment] 2023-09-25 12:54
Duplicate of https://github.com/defold/defold/issues/5875

**Closed by britzl** 2023-09-25 12:54 UTC
Labels: bug, editor
