### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dr00x** [defold/defold#6243] opened 2021-12-07 02:28 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-11-18T07:28:04.826271</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>229b4dbc78495615871b3a7679e79d75d018c27a</td></tr>
<tr><td>Defold engine sha</td><td>8894457f85514465165401c664f5ba79a7730804</td></tr>
<tr><td>Defold version</td><td>1.2.189</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"cb1de5e2425144469141cd808b01c7f1"'>cb1de5e2425144469141cd808b01c7f1</a></td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-22-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-12-07 07:11
```
jogamp.opengl.x11.glx.X11GLXContext.createImpl.class com.jogamp.opengl.GLException: JavaFX Application Thread: createImpl ARB n/a but required, profile > GL2 requested (OpenGL >= 3.1). Requested: GLProfile[GL3bc/GL3bc.hw], current: 3.0 (Compat profile, compat[ES2], FBO, hardware) - 3.0 Mesa 21.2.2
    at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:440)
    at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
    at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1279)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:47
```

**Comment by britzl** [comment] 2021-12-07 07:12
Can you please check that your graphics drivers are up to date?

**Comment by ainonovo** [comment] 2021-12-08 18:34
please help me https://github.com/defold/defold/issues/6231

**Comment by britzl** [comment] 2022-12-02 19:42
Duplicate of https://github.com/defold/defold/issues/6053

**Closed by britzl** 2022-12-02 19:42 UTC
Labels: more info, editor, linux, javafx
