### ISSUE TITLE
Setting alpha only on GUI nodes

### ISSUE THREAD

**Issue by gianmichelemariani** [defold/defold#5429] opened 2020-12-23 10:31 UTC
Doing quite a lot of GUI these days, with a lot of animation that require an initial state of the alpha channel on the nodes.
Right now for all the nodes I have to first read the full color information and then change the alpha channel to retain the original color.

It would be useful to simply be able to do:

gui.set_alpha(node, alpha)

**Comment by subsoap** [comment] 2020-12-23 14:47
You could add this function yourself if you use it commonly. We have a globals.lua import with functions like these.

Instead of monkey patching we use like the below gui_set_alpha instead of gui.set_alpha in part to make it clear it's one of our functions and because it plays better with auto complete. For these kinds of things we also generally use string name of nodes directly too and do the get node inside.

```
function gui_set_alpha(node, alpha)
	local node = gui.get_node(node)
	local color = gui.get_color(node)
	color.w = alpha
	gui.set_color(node, color)
end

function init(self)
	gui_set_alpha("box", 0.1)
end
```

Besides this we also alias a lot of functions and simplify them so they are faster / more convenient to work with.

**Comment by gianmichelemariani** [comment] 2020-12-23 15:04
Yes, I do something similar already, but monkey patching (not a fan of it I have to say).
Since it is something I understand a lot of people do, hence the request :P

**Comment by britzl** [comment] 2021-06-20 09:13
Duplicate of #5090 (which argues for a gui.set(node, "color.w") function)

**Comment by britzl** [comment] 2021-07-20 08:46
#5090 will come later. It makes sense to have a specific gui.set_alpha() since it is a fairly common operation.

**Closed** 2021-11-29 07:40 UTC
Labels: feature request, gui
