### ISSUE TITLE
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2

### ISSUE THREAD

**Issue by botmenoff** [defold/defold#6365] opened 2022-01-31 21:04 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-01-10T12:20:44.142957</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold engine sha</td><td>d393bae6a361f86cf2263ab312c9b3cea45253ab</td></tr>
<tr><td>Defold version</td><td>1.2.191</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9a95f4ff4f5b44a184612f7ebac35718"'>9a95f4ff4f5b44a184612f7ebac35718</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics (CML GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.2.2</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.13.0-27-generic</td></tr>
<table>

**Comment by britzl** [comment] 2022-02-01 07:45
Please try overriding `MESA_GL_VERSION_OVERRIDE` as described here:

https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl


```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:192)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1501)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1501)
    at editor.app_view$open_resource$fn.invoke(app_view.clj:1731)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
```

**Comment by britzl** [comment] 2022-05-17 06:15
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:15 UTC
Labels: bug, more info, editor, linux
