### ISSUE TITLE
gui.property (DEFEDIT-334)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4068] opened 2019-05-27 05:40 UTC
I think it would be useful to be able to declare properties "outside" of a script in the same manner as you can with go.property - Adding the same functionality to gui-scenes would be awesome.

**Comment by AGulev** [comment] 2023-04-19 07:24
Duplicate of https://github.com/defold/defold/issues/3258

**Comment by j-h-a** [comment] 2024-03-06 01:03
For anyone finding this linked from the forums or discord, here's how to work-around it prior to it being implemented.

1. Create a normal game-object script to hold the properties you want to inject, that looks like this `inject.script`:
```lua
go.property("gui_component", msg.url())
-- your custom props
go.property("my_prop_one", hash(""))
go.property("my_prop_two", msg.url())
go.property("my_prop_three", 0)

function init(self)
    msg.post(self.gui_component, "inject", {
        my_prop_one = self.my_prop_one,
        my_prop_two = self.my_prop_two,
        my_prop_three = self.my_prop_three,
    })
end
```

2. In your `.gui_script` add a handler in `on_message`:
```lua
    if message_id == hash("inject") then
        self.my_prop_one = message.my_prop_one
        self.my_prop_two = message.my_prop_two
        self.my_prop_three = message.my_prop_three
    end
```

3. In the editor, open your collection or gameobject file, select "Add component file" and add the `inject.script` to the gameobject which has your GUI on it.

4. In the script component's properties, set the `Gui Component` property to `#id_of_the_gui_component` and set all of your custom properties to whatever values you want.

Note: The values injected this way will not be immediately available in your `gui_script` (for example in `init`) so if you need to do any further setup once they are injected, create a function and call that at the end of your message handler. And remember to check for `nil` in other places where they are used if those places might be called before the `inject` message gets handled.

**Comment by AGulev** [comment] 2024-03-08 18:57
This feature isn't planned

**Closed by AGulev** 2024-03-08 18:57 UTC
Labels: feature request, engine, editor
