### ISSUE TITLE
Cycle detected on node type editor.game-object/GameObjectNode

### ISSUE THREAD

**Issue by Killeracrrot1021** [defold/defold#6724] opened 2022-06-19 13:44 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-05-19T08:43:47.250124</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92bfcab05e2b9b5713df4f25eda838f5a7114a5d</td></tr>
<tr><td>Defold engine sha</td><td>287c945fab310c324493e08b191ee1b1538ef973</td></tr>
<tr><td>Defold version</td><td>1.3.2</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c03a8b1c853c436fbd77bf1f007e015b"'>c03a8b1c853c436fbd77bf1f007e015b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5300</td></tr>
<tr><td>GPU Driver</td><td>4.5.13587 Compatibility Profile Context FireGL 19.50.32.02 26.20.15032.2015</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

The code I was using is this:`function on_input(self, action_id, action)
	if action.x and action.y then
		local pos = vmath.vector3(action.x, action.y, 1)
		go.set_position(vmath.vector3(action.x, action.y, 1))
		house_id = factory.create("#housefactory", pos)
	end
end`

**Comment by britzl** [comment] 2022-06-20 05:10
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.game-object/GameObjectNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1318)
    at editor.game_object$GameObjectNode$behavior$build_targets.invokeStatic(game_object.clj:455)
    at editor.game_object$GameObjectNode$behavior$build_targets.invoke(game_object.clj:455)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:285)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1145)
    at editor.factory$FactoryNode$behavior$build_targets$fn.invoke(factory.clj:108)
    at internal.node$trace_expr$fn.invoke(node.clj:37)
    at internal.node$trace_expr.invokeStatic(node.clj:37)
    at editor.factory$FactoryNode$behavior$build_targets.invokeStatic(factory.clj:108)
    at editor.factory$FactoryNode$behavior$build_targets.invoke(factory.clj:108)
    at clojure.lang.Var.invoke(Var.java:393)
```
 
This error is not related to the code you use but the fact that you've created a cyclic dependency. 

This issue can for instance happen when a game object A.go contains a factory that creates an instance of A.go. It can also be a more complicated chain of dependencies such as A.go having a factory that creates B.go which has a factory that creates A.go.

A similar issue can happen when Lua module A requires Lua module B and vice versa or when you have a collection A with a collection proxy or collection factory referencing collection B. And in collection B you have a reference back to collection A.

**Comment by Killeracrrot1021** [comment] 2022-06-20 11:31
I think I know what you mean, it's sort of a feedback loop of .go's because I selected the game object in the factory that the factory is in the object like this
![City bit builder - Defold Editor 2 0 6_20_2022 6_26_35 AM](https://user-images.githubusercontent.com/107220424/174592284-6704d203-a5e1-4ae2-9442-6307a6a2602f.png)
![City bit builder - Defold Editor 2 0 6_20_2022 6_27_15 AM](https://user-images.githubusercontent.com/107220424/174592286-403112f1-7a61-4238-8288-6c0490a71b7c.png)
:
also, click the screenshots it makes them easier to read.

**Comment by AGulev** [comment] 2022-08-22 11:50
close as duplicate of https://github.com/defold/defold/issues/3919

**Comment by britzl** [comment] 2023-01-11 07:14
Closed via https://github.com/defold/defold/pull/7262

**Closed by britzl** 2023-01-11 07:14 UTC
Labels: bug, editor
