### ISSUE TITLE
Working on GUI and this happened

### ISSUE THREAD

**Issue by schlista** [defold/defold#8985] opened 2024-05-26 16:40 UTC
### Expected behaviour
Do not crash with error.
### Actual behaviour
Crashed with error.
### Steps to reproduce
Not sure.  I was just working on the GUI and changes the color of the GUI node via the property.
<hr/>

<table>
<tr><td>Build time</td><td>2024-05-24T10:50:33.105437</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8dfb2825db0d62dfc910fdcf8c271a005d5edb99</td></tr>
<tr><td>Defold engine sha</td><td>9141d9d3605e3f5d51c71293116d769da2613d39</td></tr>
<tr><td>Defold version</td><td>1.8.0</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8c70632d675c43b2854acc9e64e5f923"'>8c70632d675c43b2854acc9e64e5f923</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 552.22</td></tr>
<tr><td>Java version</td><td>17.0.5+8</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 11</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment] 2024-05-26 16:48
```
editor.debugging.mobdebug$connect_BANG_$fn__61085.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on 127.0.0.1:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:159)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.lang.Thread.run(Thread.java:833)

**Comment by britzl** [comment] 2024-05-27 09:22
Duplicate of https://github.com/defold/defold/issues/8885

**Closed by britzl** 2024-05-27 09:22 UTC
Labels: bug, editor
