### ISSUE TITLE
Navigation away while auto complete is open causes error

### ISSUE THREAD

**Issue by Jerakin** [defold/defold#5084] opened 2020-08-06 18:47 UTC
### Expected behaviour
Nothing should happen

### Actual behaviour
Error happens

### Steps to reproduce
Open two script tabs

In one of them start writing something e.g. `go` and let the auto complete window open. While the window is open navigate to the second tab.

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-25T06:13:26.934742</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7a64a72ca0d10f1583edab5b4317499cdc8c64e5</td></tr>
<tr><td>Defold engine sha</td><td>29b8e598b0bce19b274327c5d9711f78b3bd0c22</td></tr>
<tr><td>Defold version</td><td>1.2.171</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d7b5d83137e24f46a1268fd96e83684d"'>d7b5d83137e24f46a1268fd96e83684d</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 432.00</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-08-23 22:16
class java.lang.NullPointerException
javafx.scene.control.skin.TabPaneSkin in stopDrag at line 2216
javafx.scene.control.skin.TabPaneSkin in handleHeaderMouseReleased at line 2044

**Comment by britzl** [comment] 2020-08-23 22:16
Duplicate of https://github.com/defold/defold/issues/4852

**Closed by britzl** 2020-08-23 22:16 UTC
