### ISSUE TITLE
Allow project folders and dependency folders to be hidden into a special folder

### ISSUE THREAD

**Issue by subsoap** [defold/defold#4979] opened 2020-06-30 04:07 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
Big projects can have many dependencies and other folders within the root assets view that clutter the view and are not necessary to directly see all of the time.

**Describe the solution you'd like (REQUIRED):**
* A hidden.project file would be created in the project folder, this file itself would not be directly editable but be hidden to the editor asset view, this file would have a line separated list of root folder names that are to be hidden
* Right clicking on one or more selected folders and clicking "hide" would move those folders / dependencies into a "hidden" folder at the top next to the builtins
* The folders within the hidden folder would still behave as normally, they can be set to not be hidden when selected in the root hidden folder
* This would enable devs to clean up the assets view of project folders / dependency folders that are not commonly used while developing and keep this states saved between sessions but still be able to quickly see them and restore their visibility

**Comment by AGulev** [comment] 2023-09-30 14:40
duplicate of https://github.com/defold/defold/issues/4156

**Closed by AGulev** 2023-09-30 14:40 UTC
Labels: feature request, editor
