### ISSUE TITLE
Particle effect settings (DEF-1719)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3274] opened 2019-05-23 10:33 UTC
*What:*
Currently there is no way to set image/texture/animation for a particle effect from code. The ability to change these from code would be very appreciated as right now the developers need to have multiple particle systems with different flipbook-anims to toggle between.

It is possible to change flipbook on sprites, so maybe a similar interface, but fine grained to include emitter.
2016-04-13 11:00:25 (ingela.garneij)
DoD: Be able to switch an animation and texture as done with sprites but on emitters

**Comment by AGulev** [comment] 2023-09-26 11:30
duplicate of https://github.com/defold/defold/issues/3417

**Closed by AGulev** 2023-09-26 11:30 UTC
Labels: feature request, engine, particlefx
