### ISSUE TITLE
Failed to connect to debugger on localhost:8172

### ISSUE THREAD

**Issue by leamak** [defold/defold#6961] opened 2022-09-07 23:02 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2022-09-07T14:07:16.060634</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>dd9acd54fb060fdc63c2c73e53268665fbec9efd</td></tr>
<tr><td>Defold engine sha</td><td>c1c0592986a4421f33490422c2af532e533aeca5</td></tr>
<tr><td>Defold version</td><td>1.3.5</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"176f5af7b7a24a87aef6904bc34be3cb"'>176f5af7b7a24a87aef6904bc34be3cb</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3050/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 515.65.01</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.15.0-47-generic</td></tr>
<table>

**Comment by britzl** [comment] 2022-09-08 06:32
```
editor.debugging.mobdebug$connect_BANG_$fn__44725.invoke.class clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:341)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:829)
```

**Comment by vlaaad** [comment] 2022-09-08 06:48
Duplicate of #6775 / #6876?

**Comment by britzl** [comment] 2022-09-08 06:57
> Duplicate of #6775 / #6876?

Indeed. Closing.

**Closed by britzl** 2022-09-08 06:57 UTC
Labels: bug, editor, debugger
