### ISSUE TITLE
Reporting a problem

### ISSUE THREAD

**Issue by drgn-pixel** [defold/defold#5926] opened 2021-07-09 18:33 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-07-07T08:23:30.403800</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>92b6b2823b819707ddfa075f1fc5a8774a011f1a</td></tr>
<tr><td>Defold engine sha</td><td>1f5712609c345f870b691a85d611d4825d22a718</td></tr>
<tr><td>Defold version</td><td>1.2.184</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"751a90794ccc407ea7ff6f955d54d4dd"'>751a90794ccc407ea7ff6f955d54d4dd</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 471.11</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2021-07-10 08:11
Duplicate of https://github.com/defold/defold/issues/5927

**Closed by britzl** 2021-07-10 08:11 UTC
