### ISSUE TITLE
Setting a tile source at runtime does not apply new tile source's collision data

### ISSUE THREAD

**Issue by jcbk101** [defold/defold#7695] opened 2023-05-29 22:53 UTC
**Describe the bug (REQUIRED)**
When setting a tile source at runtime to be used with a tile map being built dynamically, does not apply the collision data from
the tile source editor. The tile source attached in the designer / editor is the collision data used.

**To Reproduce (REQUIRED)**
Create a project, set a tile source to a simple tile map. Create a tile source file to use with `go.set("#tilemap", "tile_source", has(tile.source))`, but it must have different collision tile data than what is preloaded in the editor. 
In a script file, use `go.set(mapUrl, "tile_source", tile.source )`, then use `tilemap.set_tile()' to set the newly loaded tile data.

**Expected behavior (REQUIRED)**
The tiles should display from the new tile set. The collision settings for the tile set should work with a kinematic / dynamic character.
If the physics debugger is enabled, you will see that only the tiles aligned with the tile source that was replaced, will have collision
data.

**Defold version (REQUIRED):**
  - Version 1.4.6

**Platforms (REQUIRED):**
Windows

**Minimal repro case project (OPTIONAL):**
Please attach a minimal project where the bug is reproduced. This will greatly help the person trying to investigate and fix the bug.

**Logs (OPTIONAL):**
Please provide relevant logs from engine, editor or build server. Learn where the logs are stored [here](https://defold.com/manuals/getting-help/#log-files).

**Workaround (OPTIONAL):**
No workaround. See photo with player inside of the green pipe and blocks with no collision data.

**Screenshots (OPTIONAL):**
![image](https://github.com/defold/defold/assets/75145117/7a57ebc9-c4b4-436a-842a-78dd20a0603a)

**Additional context (OPTIONAL):**

**Comment by AGulev** [comment] 2024-03-09 09:36
duplicate of https://github.com/defold/defold/issues/4829

**Closed by AGulev** 2024-03-09 09:36 UTC
Labels: bug, physics

**Comment by jcbk101** [comment] 2024-03-09 11:49
Thank YOU!!!!!!!! 🙏


________________________________

**Comment by AGulev** [comment] 2024-03-13 07:43
hi @jcbk101 
I can't reproduce this issue.
if you can create a minimal repro case I 'll take a look

**Comment by jcbk101** [comment] 2024-03-13 10:34
Hello,

I'm not sue why this is showing active. Lol. I responded with "Thank you" and I guess  it caused some confusion. I am not having any troubles with this, thanks.


________________________________
