### ISSUE TITLE
jogamp.opengl.es1.GLES1Impl crash on Linux

### ISSUE THREAD

**Issue by OG-surajchand** [defold/defold#6023] opened 2021-09-01 14:13 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-08-24T08:34:30.434218</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1238ae4c78250fac5830b149a6bf3cd4bb42899e</td></tr>
<tr><td>Defold engine sha</td><td>1f748d5b0a84e8b5c58bf747e4c48d153ef77a52</td></tr>
<tr><td>Defold version</td><td>1.2.186</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"60dac8b9d3ef411693af9a8b507929cb"'>60dac8b9d3ef411693af9a8b507929cb</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-27-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-09-03 12:10
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:191)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1370)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:1370)
    at editor.app_view$make_app_view$fn.invoke(app_view.clj:1482)
    at editor.ui$__GT_timer$fn$fn.invoke(ui.clj:1923)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by britzl** [comment] 2021-09-03 12:10
@OG-surajchand please check this solution: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:14
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:14 UTC
Labels: bug, more info, editor, linux
