### ISSUE TITLE
Building with bob.jar fails on Mac with M1 chip.

### ISSUE THREAD

**Issue by astrochili** [defold/defold#5949] opened 2021-07-20 17:12 UTC
Bob launch with build command

```shell
$ java -jar bob.jar --variant debug build
```

fails with the error

```
The build failed for the following reasons:
ERROR misc/kawaii.render_script:0 /libexec/x86-darwin/luajit-32 could not be found locally, create an application manifest to build the engine remotely.
```

**To Reproduce (REQUIRED)**
Try to build with bob.jar on Mac with M1 chip.

 - Defold Version 1.2.184
 - OS: macOS Big Sur 11.2.3
 - Device: Macbook Air M1

**Workaround:**
Build with the Editor. The Editor works fine.

**Comment by astrochili** [comment] 2021-07-20 17:33
[Topic](https://forum.defold.com/t/apple-m1-and-the-new-machines-defold/66791/10?u=astrochili) on the forum.

**Comment by JCash** [comment] 2021-09-09 07:10
Duplicate of #5931

**Closed by JCash** 2021-09-09 07:10 UTC
Labels: bug
