### ISSUE TITLE
Add inverse world matrix shader constants  (DEF-2518)

### ISSUE THREAD

**Issue by britzl** [defold/defold#3656] opened 2019-05-23 10:46 UTC
Description:

Materials have access to world matrices in shaders but not to inverse world.

Use case:

Doing vertex deformation in model space requires that you apply the inverse world matrix since all vertices are world transformed.

Business need:

More $$$ to Defold!

**Comment by AGulev** [comment] 2023-10-21 07:42
duplicate of https://github.com/defold/defold/issues/3789

**Closed by AGulev** 2023-10-21 07:42 UTC
Labels: feature request, engine, render
