### ISSUE TITLE
Multi-material GLB model Renders with Incorrect Textures

### ISSUE THREAD

**Issue by busovikov** [defold/defold#9074] opened 2024-06-13 17:22 UTC
The GLB model has several materials, all set to the built-in model.material with different textures.
However, at runtime and in the editor, it renders using the texture set for the first material.

To reproduce just run the project 
The example project with glb and blend files is attached [gltf_texture_issue.zip](https://github.com/user-attachments/files/15826205/gltf_texture_issue.zip)

  - Version [1.8.1]

**Platforms (REQUIRED):**
 - Platforms:  Windows
 - OS: Windows 11

![image](https://github.com/defold/defold/assets/86739514/dcc88688-c354-4739-adb9-94733fd19e73)

Here is the setup for the model 
![image](https://github.com/defold/defold/assets/86739514/da7423e3-efce-4883-a074-e70ec6111d96)

**It crashes for** 
  - Version [1.9.0] BETA
  
LOGS: 
```
INFO:DLIB: Log server started on port 53260
INFO:ENGINE: Target listening with name: Busovikov - fe80::2f84:bcca:1766:3e4f - Windows
INFO:ENGINE: Engine service started on port 53261
INFO:GRAPHICS: Installed graphics device 'ADAPTER_FAMILY_OPENGL'
INFO:ENGINE: Defold Engine 1.9.0 (d337da5)
INFO:DLIB: Initialized Remotery (ws://127.0.0.1:17815/rmt)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\pavel\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF77D1DBF40 dmCrash::GenerateCallstack D:\a\defold\defold\engine\crash\src\backtrace_win32.cpp:144
ERROR:CRASH:  1 0x7FF77D2D4AFC _seh_filter_exe minkernel\crts\ucrt\src\appcrt\misc\exception_filter.cpp:219
ERROR:CRASH:  2 0x7FF77D319A74 `__scrt_common_main_seh'::`1'::filt$0 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304
ERROR:CRASH:  3 0x7FF77D255D5C __C_specific_handler D:\a\_work\1\s\src\vctools\crt\vcruntime\src\eh\riscchandler.cpp:389
ERROR:CRASH:  4 0x7FF9BA6F4F20 __chkstk <unknown>:0
ERROR:CRASH:  5 0x7FF9BA66DDD0 RtlFindCharInUnicodeString <unknown>:0
ERROR:CRASH:  6 0x7FF9BA6F4010 KiUserExceptionDispatcher <unknown>:0
ERROR:CRASH:  7 0x7FF77D0EB830 dmRig::GenerateNormalData D:\a\defold\defold\engine\rig\src\rig.cpp:828
ERROR:CRASH:  8 0x7FF77D0ED560 dmRig::GenerateVertexData D:\a\defold\defold\engine\rig\src\rig.cpp:1249
ERROR:CRASH:  9 0x7FF77CEF41F0 dmGameSystem::RenderBatchWorldVS D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_model.cpp:965
ERROR:CRASH: 10 0x7FF77CEF53D0 dmGameSystem::RenderListDispatch D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_model.cpp:1169
ERROR:CRASH: 11 0x7FF77CFDE760 dmRender::DrawRenderList D:\a\defold\defold\engine\render\src\render\render.cpp:932
ERROR:CRASH: 12 0x7FF77D001390 dmRender::ParseCommands D:\a\defold\defold\engine\render\src\render\render_command.cpp:183
ERROR:CRASH: 13 0x7FF77CFEBD10 dmRender::UpdateRenderScriptInstance D:\a\defold\defold\engine\render\src\render\render_script.cpp:3812
ERROR:CRASH: 14 0x7FF77CE20350 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1716
ERROR:CRASH: 15 0x7FF77CE210A0 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2218
ERROR:CRASH: 16 0x7FF77CE212D0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
ERROR:CRASH: 17 0x7FF77CE19430 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
ERROR:CRASH: 18 0x7FF77D24A164 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 19 0x7FF9B9C52560 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 20 0x7FF9BA6AAF00 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

INFO:CRASH: Successfully wrote Crashdump to file: C:\Users\pavel\AppData\Roaming\Defold/_crash
ERROR:CRASH: CALL STACK:

ERROR:CRASH:  0 0x7FF77D0EB830 dmRig::GenerateNormalData D:\a\defold\defold\engine\rig\src\rig.cpp:828
ERROR:CRASH:  1 0x7FF77D0ED560 dmRig::GenerateVertexData D:\a\defold\defold\engine\rig\src\rig.cpp:1249
ERROR:CRASH:  2 0x7FF77CEF41F0 dmGameSystem::RenderBatchWorldVS D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_model.cpp:965
ERROR:CRASH:  3 0x7FF77CEF53D0 dmGameSystem::RenderListDispatch D:\a\defold\defold\engine\gamesys\src\gamesys\components\comp_model.cpp:1169
ERROR:CRASH:  4 0x7FF77CFDE760 dmRender::DrawRenderList D:\a\defold\defold\engine\render\src\render\render.cpp:932
ERROR:CRASH:  5 0x7FF77D001390 dmRender::ParseCommands D:\a\defold\defold\engine\render\src\render\render_command.cpp:183
ERROR:CRASH:  6 0x7FF77CFEBD10 dmRender::UpdateRenderScriptInstance D:\a\defold\defold\engine\render\src\render\render_script.cpp:3812
ERROR:CRASH:  7 0x7FF77CE20350 dmEngine::StepFrame D:\a\defold\defold\engine\engine\src\engine.cpp:1716
ERROR:CRASH:  8 0x7FF77CE210A0 dmEngineUpdate D:\a\defold\defold\engine\engine\src\engine.cpp:2218
ERROR:CRASH:  9 0x7FF77CE212D0 dmEngine::RunLoop D:\a\defold\defold\engine\engine\src\engine_loop.cpp:83
ERROR:CRASH: 10 0x7FF77CE19430 engine_main D:\a\defold\defold\engine\engine\src\engine_main.cpp:152
ERROR:CRASH: 11 0x7FF77D24A164 __scrt_common_main_seh D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
ERROR:CRASH: 12 0x7FF9B9C52560 BaseThreadInitThunk <unknown>:0
ERROR:CRASH: 13 0x7FF9BA6AAF00 RtlUserThreadStart <unknown>:0
ERROR:CRASH: 

INFO:CRASH: Successfully wrote MiniDump to file: C:\Users\pavel\AppData\Roaming\Defold/_crash.dmp
```
[_crash.dmp](https://github.com/user-attachments/files/15826198/_crash.dmp)

**Comment by Jhonnyg** [comment] 2024-06-13 18:00
Thanks! I've pushed a fix to dev just now, which fixes the crash. And I'm about to verify if the instance branch successfully fixes the incorrect render state.

**Comment by Jhonnyg** [comment] 2024-06-13 18:59
No, it's not fixed there, but I think it's this TODO that needs to be resolved:
https://github.com/defold/defold/blob/0bd2acac336f9061726ce4695e21d41d050a6814/engine/gamesys/src/gamesys/components/comp_model.cpp#L1255

Which is _sort of_ implemented in the instancing branch, so we need to get that in first I think 🤔

**Comment by rgrams** [comment] 2024-09-15 14:04
Possibly some more information on this issue: It is somehow related to the Vertex Space setting of the material. If you remove the skeleton and animations from the model so it doesn't crash immediately with a Local space material, then set the material's Vertex Space to Local, then you can see multiple textures. Switch it back to World and you only get one. 
(Tested with version 1.9.1.)

https://github.com/user-attachments/assets/adc52184-441d-4df4-9ae3-dc7dc18dd769

**Comment by jixingcn** [comment] 2024-10-04 09:53
> Possibly some more information on this issue: It is somehow related to the Vertex Space setting of the material. If you remove the skeleton and animations from the model so it doesn't crash immediately with a Local space material, then set the material's Vertex Space to Local, then you can see multiple textures. Switch it back to World and you only get one. (Tested with version 1.9.1.)
> 
>  recording-2024-09-15_09.59.41.mp4

Yes, I also get this issue. And I found this [https://defold.com/manuals/material/#instancing](https://defold.com/manuals/material/#instancing), and I think the instance material supports multi-materials. The instance material requires the 'VERTEX_SPACE_LOCAL' option.
You also can find this - "Material vertex space option VERTEX_SPACE_LOCAL does not support skinning." in source codes. So the skinning model doesn't support multi-materials for now.

**Comment by Jhonnyg** [comment] 2024-10-06 12:24
The issue is still related to hashing of render items, see this PR:
https://github.com/defold/defold/pull/9558

**Closed** 2024-12-19 05:18 UTC
Labels: bug, engine, model
