### ISSUE TITLE
Editor font size can only be decreased

### ISSUE THREAD

**Issue by Jackie365** [defold/defold#6432] opened 2022-02-23 06:38 UTC
### Expected behavior
In the code editor, pressing ctrl+'-' and ctrl+'+' will decrease and increase the editor's font respectively
### Actual behavior
ctrl+'-' works fine, but ctrl+'+' will not work at all
At the moment, the font size of my Defold code editor is extremely small, I'm unable to continue my work.
<hr/>

<table>
<tr><td>Build time</td><td>2022-02-16T09:52:30.949050</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>12cd9306bcb9d37dcc5c97674e395266321a9d22</td></tr>
<tr><td>Defold engine sha</td><td>84a9c89dfd5a2c3818c01e7c6777169272d9390b</td></tr>
<tr><td>Defold version</td><td>1.2.192</td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 500 (APL 2)</td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-91-generic</td></tr>
<table>

**Comment by britzl** [comment] 2022-02-23 10:44
Duplicate of https://github.com/defold/defold/issues/5589

**Closed by britzl** 2022-02-23 10:44 UTC
