### ISSUE TITLE
Folder node for no draw GUI organization nodes

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5403] opened 2020-12-14 04:00 UTC
Using GUI nodes purely for folder / pivot orientation is a common pattern, but instead of needing to set 1px transparent textures on them so they don't break batching there should be a checkbox to say "this is an organization node, don't draw it, but that doesn't mean don't draw its children"

**Comment by britzl** [comment] 2020-12-14 22:09
> there should be a checkbox to say "this is an organization node, don't draw it"

Or maybe it's a new node type?

**Comment by subsoap** [comment] 2020-12-15 04:19
New node type would be even better!

**Comment by subsoap** [comment] 2020-12-15 04:41
Maybe call it a **Folder** node since that's part of the common pattern in other programs. **Group** is used elsewhere in Defold so might just increase chance for confusion but it's what's used in programs like Photoshop. More modern art apps like Clip Studio Paint use Folder instead of Group. Another option is **Set** which is a term for organization in some other kinds of apps, but it's not the easiest to communicate what is meant.

It would still need some of the behavior of normal nodes such as deleting and children / disabling and children / setting position / animating / most any feature that's not something seen. It would probably still be convenient for it to still have an alpha value which its children can inherit since that is part of the current organization node pattern use.

**Comment by britzl** [comment] 2020-12-15 09:46
Yeah, it should for all intents and purposes act as any other node, but lack a visual representation.

**Comment by gianmichelemariani** [comment] 2020-12-15 11:44
+10000
Maybe just call it a Transform node?

**Comment by piXelicidio** [comment] 2021-01-04 19:39
I need this a lot!
  
Let's seize the opportunity and add also a custom table field to this node. Or at least a text field. So we can put there some custom data to retrieve from code, like a class name or initial values.

**Comment by subsoap** [comment] 2021-01-04 20:09
@piXelicidio That sounds useful for nodes in general.

**Comment by piXelicidio** [comment] 2021-01-04 20:35
> @piXelicidio That sounds useful for nodes in general.

I have dreams of a component that can be added to Game Objects or GUI nodes with no more than a Lua table.

**Comment by britzl** [comment] 2021-06-20 09:10
Duplicate of #5816

**Comment by britzl** [comment] 2021-07-20 08:59
Solution in #5816.

**Closed by britzl** 2021-07-20 08:59 UTC
Labels: feature request, gui
