### ISSUE TITLE
Meshes not drawing in web build(WebGL warning: drawArraysInstanced)

### ISSUE THREAD

**Issue by d954mas** [defold/defold#6430] opened 2022-02-22 10:17 UTC
**Describe the bug (REQUIRED)**
In web build meshes sometimes not draw.
In console i see warning
```
WebGL warning: drawArraysInstanced: Vertex fetch requires 1395, but attribs only supply 4.
```
Looks like
-meshes with custom tag worked
-meshes with "tile" tag not worked.

https://forum.defold.com/t/webgl-attribs-only-supply-1320/70406/8

**To Reproduce (REQUIRED)**
1)Use repro case project.
2)Run or bundle web version.

**Expected behavior (REQUIRED)**
Draw meshes in web build.

**Defold version (REQUIRED):**
  - Version [e.g. 1.2.155]

**Platforms (REQUIRED):**
 - Platforms: HTML5
 - OS: [Windows 10]

**Minimal repro case project (OPTIONAL):**
[mouse-rob-bug.zip](https://github.com/defold/defold/files/8115704/mouse-rob-bug.zip)

**Screenshots (OPTIONAL):**

https://user-images.githubusercontent.com/2655263/155111186-c0231f81-375a-4c26-b03e-ec292ef1b111.mp4

https://user-images.githubusercontent.com/2655263/155111177-05cd99a8-f940-4336-b498-ed80fc84e016.mp4

**Comment by JCash** [comment] 2022-03-29 10:17
I can (sort of) reproduce your (visual) issue when running the demo in WebGL1.
When running in WebGL2 it works as expected.

Which WebGL version are you using?

(Using WebGL 1 (Safari 14.1.2))
<img width="1114" alt="Screenshot 2022-03-29 at 12 07 01" src="https://user-images.githubusercontent.com/1349334/160588736-440b0520-765b-4aab-a9aa-a070b6e053b8.png">



> drawArraysInstanced

I couldn't reproduce any error with `drawArraysInstanced`.
Note that `drawArraysInstanced` is a function of WebGL2, so I'm not exactly sure how it's invoked?
(It isn't part of  our engine, nor the extensions that you use 🤔 )

> Vertex fetch requires 1395, but attribs only supply 4.

It suggests there's somehow a mismatch when using the internal vertex buffers.
I'm not quite sure what it could be, and it's extra hard to find if not being able to reproduce :/

I think the repro case is quite large and very difficult to reason about.
If you could minimize it to a single light/sprite that behaves in the erroneous way, it should help a lot.

**Comment by d954mas** [comment] 2022-03-29 10:50
Thanks.
1)About webgl. It reproduced only in pc build. My browser support webgl2. Windows(firefox,chrome)
2)Something wrong with vertex space. 
-If i use local all worked.
-If i use world i get that error.
3)Also if i have sprites in scene.
I get bigger number in error. "WebGL warning: drawArraysInstanced: Vertex fetch requires 1395, but attribs only supply 1320."
"WebGL warning: drawArraysInstanced: Vertex fetch requires 1395, but attribs only supply 4."
4)I use same tag for sprites and meshes. "Tile"
5)Meshes that use different tag, worked good.

Looks like something wrong when mixed meshes and sprites in same tag.(in same draw call)

"I think the repro case is quite large and very difficult to reason about."
I agree with you, but i am not sure how to reproduce it in smaller repro case. I make it as smaller as i can.

**Comment by britzl** [comment] 2022-05-14 08:52
> Looks like something wrong when mixed meshes and sprites in same tag.(in same draw call)

But it doesn't happen if you have one sprite and one mesh? It has to be more? Are the sprites created using a factory or placed in the collection? And it never happens when you only have meshes?

> It reproduced only in pc build

What do you mean by "only in pc build"? Does it work if you run it in a browser on Linux or macOS you mean? Or on mobile?

**Comment by d954mas** [comment] 2022-05-14 08:58
What do you mean by "only in pc build"?

When I play on pc(window) browser(Firefox, Chrome)  I get that error. 
When I play on mobile browser no errors

**Comment by d954mas** [comment] 2022-05-14 08:59
But it doesn't happen if you have one sprite and one mesh? It has to be more?

I don't know. In my game I have a lot of meshes and sprites when error happened

**Comment by d954mas** [comment] 2022-05-14 09:00
Sprites and meshes created by factory

**Comment by d954mas** [comment] 2022-05-14 09:01
In my game I fixed it by set local space for mesh material

**Comment by d954mas** [comment] 2022-05-14 09:04
And it never happens when you only have meshes?

I think yes.  Some of meshes draw after tile, with another predicate(only meshes) ,they worked correct.

**Comment by d954mas** [comment] 2022-05-14 11:35
I try to make smaller repro case. With different meshes and world/local tile/model, but i smaller project everything work ok.
I have no idea why it can happened.

**Comment by d954mas** [comment] 2022-05-14 11:39
Try 1.3.0 and 1.3.2 versions.

In 1.3.0 meshes not draw.
In 1.3.2 meshes draw.

Looks like it was fixed :)

**Comment by d954mas** [comment] 2022-05-14 11:40
In 1.3.2 i also get warning WebGL warning: drawArraysInstanced: Vertex fetch requires 267, but attribs only supply 4.

But meshes are drawing

**Comment by britzl** [comment] 2022-05-14 15:34
> In 1.3.0 meshes not draw. In 1.3.2 meshes draw.
> 
> Looks like it was fixed

Ok, so it was very likely that this was solved via this PR:

https://github.com/defold/defold/pull/6505

> In 1.3.2 i also get warning WebGL warning: drawArraysInstanced: Vertex fetch requires 267, but attribs only supply 4

Not sure about this to be honest.

**Comment by d954mas** [comment] 2022-05-14 16:09
> Not sure about this to be honest. It could be mesh related. How are you creating your mesh data?
It happened when i change buffer in runtime.(change number of verticies)

In that project mesh is changing in runtime.
example.collection -> /go#mesh
If initial buffer is /assets/quad.buffer i get:
"WebGL warning: drawArraysInstanced: Vertex fetch requires 3600, but attribs only supply 6."
If initial buffer is /assets/meshes/box.buffer i get:
"WebGL warning: drawArraysInstanced: Vertex fetch requires 3600, but attribs only supply 36."
[3d-tilemap.zip](https://github.com/defold/defold/files/8693487/3d-tilemap.zip)

**Comment by Jhonnyg** [comment] 2023-04-28 08:20
This seems to be fixed, closing for now!

**Closed by Jhonnyg** 2023-04-28 08:20 UTC
Labels: bug, more info, mesh
