### ISSUE TITLE
Error when create new Lua module

### ISSUE THREAD

**Issue by ekharkunov-ms** [defold/defold#7136] opened 2022-11-07 12:35 UTC
### Steps to reproduce

1.  Open New File dialog (Cmd+N)
2. Select Lua module
3. Fill form with name and location
4. Press Create Lua Module
 

<hr/>

<table>
<tr><td>Build time</td><td>2022-10-27T14:51:20.923228</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>51c94c3c0b635671a0559b6ad68226cae66d6185</td></tr>
<tr><td>Defold engine sha</td><td>f0ad06a2f1fbf0e9cbddbf96162a75bc006d84bb</td></tr>
<tr><td>Defold version</td><td>1.3.7</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ecf59242d45945519d31e2e2f4c63c0a"'>ecf59242d45945519d31e2e2f4c63c0a</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 5500M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.8.101</td></tr>
<tr><td>Java version</td><td>11.0.15+10-LTS</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>12.5.1</td></tr>
<table>

**Comment by britzl** [comment] 2022-11-07 12:59
```
editor.code.view$repaint_canvas_BANG_.invokeStatic.class java.lang.NullPointerException: null
    at editor.code.view$repaint_canvas_BANG_.invokeStatic(view.clj:784)
    at editor.code.view$repaint_view_BANG_.invokeStatic(view.clj:2227)
    at editor.code.view$make_view_BANG_$fn.invoke(view.clj:2563)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by britzl** [comment] 2022-11-07 13:00
@ekharkunov-ms does this happen repeatedly or only one time?

**Comment by ekharkunov-ms** [comment] 2022-11-07 13:12
@britzl I faced it only once because I don't create new Lua modules so often.

**Comment by ekharkunov-ms** [comment] 2022-11-07 13:26
Also I saw following errors in editor's log
```
2022-11-07 14:33:48.304 ERROR default    editor.error-reporting - {:line 112}
clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
	at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1297)
	at editor.ui$make_menu_items$fn__15787.invoke(ui.clj:1313)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1311)
	at editor.ui$make_menu_items.invoke(ui.clj:1311)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1289)
	at editor.ui$make_menu_items$fn__15787.invoke(ui.clj:1313)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1311)
	at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1514)
	at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1778)
	at editor.ui$refresh.invokeStatic(ui.clj:1799)
	at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1509)
	at editor.app_view$make_app_view$fn__48936.invoke(app_view.clj:1633)
	at editor.ui$__GT_timer$fn__16168$fn__16169.invoke(ui.clj:1933)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')
	at editor.code.data$cursor_range_empty_QMARK_.invokeStatic(data.clj:194)
	at editor.code.data$cursor_range_empty_QMARK_.invoke(data.clj:193)
	at clojure.core$every_QMARK_.invokeStatic(core.clj:2681)
	at clojure.core$every_QMARK_.invoke(core.clj:2672)
	at clojure.core$comp$fn__5792.invoke(core.clj:2570)
	at editor.code.view$has_selection_QMARK_.invokeStatic(view.clj:1548)
	at editor.code.view$fn__33545$fnk33542_positional__33546.invoke(view.clj:1654)
	at editor.code.view$fn__33545$fnk33542__33557$fn__33558.invoke(view.clj:1654)
	at editor.code.view$fn__33545$fnk33542__33557.invoke(view.clj:1654)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
	... 27 common frames omitted
2022-11-07 14:33:48.306 ERROR default    editor.error-reporting - {:line 112}
clojure.lang.ExceptionInfo: handler ':sort-lines' in context ':code-view' failed at ':enabled?' with message 'class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')'
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:262)
	at editor.handler$enabled_QMARK_.invokeStatic(handler.clj:296)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1297)
	at editor.ui$make_menu_items$fn__15787.invoke(ui.clj:1313)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1311)
	at editor.ui$make_menu_items.invoke(ui.clj:1311)
	at editor.ui$make_menu_item.invokeStatic(ui.clj:1289)
	at editor.ui$make_menu_items$fn__15787.invoke(ui.clj:1313)
	at clojure.core$keep$fn__8540$fn__8541.invoke(core.clj:7325)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$transduce.invokeStatic(core.clj:6883)
	at clojure.core$into.invokeStatic(core.clj:6899)
	at editor.ui$make_menu_items.invokeStatic(ui.clj:1311)
	at editor.ui$refresh_menubar_BANG_.invokeStatic(ui.clj:1514)
	at editor.ui$refresh_menus_BANG_.invokeStatic(ui.clj:1778)
	at editor.ui$refresh.invokeStatic(ui.clj:1799)
	at editor.app_view$refresh_menus_and_toolbars_BANG_.invokeStatic(app_view.clj:1509)
	at editor.app_view$make_app_view$fn__48936.invoke(app_view.clj:1633)
	at editor.ui$__GT_timer$fn__16168$fn__16169.invoke(ui.clj:1933)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Caused by: java.lang.ClassCastException: class clojure.lang.MapEntry cannot be cast to class editor.code.data.CursorRange (clojure.lang.MapEntry and editor.code.data.CursorRange are in unnamed module of loader 'app')
	at editor.code.data$cursor_range_multi_line_QMARK_.invokeStatic(data.clj:197)
	at editor.code.data$cursor_range_multi_line_QMARK_.invoke(data.clj:196)
	at clojure.core$some.invokeStatic(core.clj:2701)
	at editor.code.view$can_sort_lines_QMARK_.invokeStatic(view.clj:1736)
	at editor.code.view$fn__34156$fnk34153_positional__34157.invoke(view.clj:1746)
	at editor.code.view$fn__34156$fnk34153__34168$fn__34169.invoke(view.clj:1746)
	at editor.code.view$fn__34156$fnk34153__34168.invoke(view.clj:1746)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:256)
	... 27 common frames omitted
```

**Comment by britzl** [comment] 2023-09-26 13:13
Unable to reproduce. Closing.

**Closed by britzl** 2023-09-26 13:13 UTC
Labels: bug, more info, editor
