### ISSUE TITLE
Bob shouldn't build all files in the project

### ISSUE THREAD

**Issue by aglitchman** [defold/defold#7671] opened 2023-05-22 12:39 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
It looks like Bob builds all the project files before determining what to include in the bundle. I would like Bob to do it the other way around, i.e. first figure out what will be in the bundle and then build these files.

I included the demo project:
[issue_donotbuild_everything.zip](https://github.com/defold/defold/files/11531101/issue_donotbuild_everything.zip)

Run `./test.sh` to build it.

What were built:
![image](https://github.com/defold/defold/assets/193258/35ffd03d-fe34-4512-82bf-f652bacde07b)

What were included:
![image](https://github.com/defold/defold/assets/193258/f9e5cac6-755e-47ec-9c48-a64c7100b9e4)

**Describe the solution you'd like (REQUIRED):**
Bob should build only the required files.

**Describe alternatives you've considered (REQUIRED):**
I revise project files and remove unused textures, fonts etc.

**Comment by AGulev** [comment] 2023-05-22 12:40
вгздшсфеу ща https://github.com/defold/defold/issues/6293

**Comment by AGulev** [comment] 2024-03-09 09:29
close as duplicate of https://github.com/defold/defold/issues/6293

**Closed by AGulev** 2024-03-09 09:29 UTC
Labels: feature request, bob
