### ISSUE TITLE
An error popped out. Everything seems fine.

### ISSUE THREAD

**Issue by viniciushedler** [defold/defold#5020] opened 2020-07-16 19:31 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-07-14T14:37:46.344716</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3061bed6e880b423d87a33bcf55d6e920c3afa74</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"8d9d3e8b66aa48398fa0c5f5ade4c486"'>8d9d3e8b66aa48398fa0c5f5ade4c486</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 24.20.100.6286</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2020-07-17 12:18
javafx.scene.control.skin.TabPaneSkin in stopDrag at line 2216

Duplicate of #4852

**Closed by britzl** 2020-07-17 12:18 UTC
