### ISSUE TITLE
Changing projects without having to reopen Defold

### ISSUE THREAD

**Issue by Caue-Aron** [defold/defold#7417] opened 2023-02-24 13:58 UTC
Pretty straight forward, having the option to change what project ur working in without having to close the entire engine. It's not a must have, but would be a great quality of life improvement.

**Comment by britzl** [comment] 2023-02-24 14:36
Duplicate of https://github.com/defold/defold/issues/5689

**Closed by britzl** 2023-02-24 14:36 UTC
Labels: feature request
