### ISSUE TITLE
Cannot create new gameobject in defold

### ISSUE THREAD

**Issue by ManavSarkar** [defold/defold#5436] opened 2020-12-28 16:41 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-12-15T21:47:59.938610</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>43a7278e5b8d48ca2d801ec223ad25b36680f191</td></tr>
<tr><td>Defold engine sha</td><td>f7778a8f59ef2a8dda5d445f471368e8bd1cb1ac</td></tr>
<tr><td>Defold version</td><td>1.2.177</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"a887fb422d164419a7fc854539179b3d"'>a887fb422d164419a7fc854539179b3d</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 510 (SKL GT1)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-58-generic</td></tr>
<table>

**Comment by subsoap** [comment] 2020-12-28 17:34
Can you explain more what you are trying to do with steps to reproduce?

If you are trying to create a GO within another GO that won't work, you need to use collections.

**Comment by britzl** [comment] 2020-12-29 09:27
```
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

@ManavSarkar please try this: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by britzl** [comment] 2021-01-17 14:09
@ManavSarkar did it solve the problem for you?

**Comment by britzl** [comment] 2021-02-08 22:34
Closing as duplicate of https://github.com/defold/defold/issues/4851

**Closed by britzl** 2021-02-08 22:34 UTC
Labels: editor, linux, more info
