### ISSUE TITLE
Main window resizes when another window opens

### ISSUE THREAD

**Issue by fodss** [defold/defold#8811] opened 2024-04-17 11:16 UTC
**Describe the bug (REQUIRED)**
If Defold is maximized, the main window is automatically resized whenever I open a different window (like "Open Assets..." or "Preferences")
It's necessary to press the "Maximize" button twice in order to maximize the window again.

**To Reproduce (REQUIRED)**
1. Open a project
2. Maximize the Defold main window
3. Go to "File" and press "Open Assets..."

**Expected behavior (REQUIRED)**
The window size should remain unchanged

**Defold version (REQUIRED):**
  - Version 1.7.0

**Platforms (REQUIRED):**
 - Platform: Linux
 - OS: Arch Linux/KDE Plasma

**Screenshots (OPTIONAL):**
![Maximized window](https://github.com/defold/defold/assets/114185396/9fbecf0d-681f-49a2-87c3-cef3b247ac87)
![Window after pressing "Open Assets..."](https://github.com/defold/defold/assets/114185396/63a0ddd9-10d9-4fae-b141-e5b7bc77b514)

**Comment by vlaaad** [comment] 2024-04-22 11:07
Duplicate of #7814.
There is a workaround: manually resize the window to fill the whole screen.

**Closed by vlaaad** 2024-04-22 11:07 UTC
Labels: bug, editor, linux

**Comment by Domarius** [comment] 2025-07-01 02:01
Not a high priority, but this isn't completed, this still happens on 1.10.2
