### ISSUE TITLE
jogamp.opengl.es1.GLES1Impl  bug

### ISSUE THREAD

**Issue by cjuniordev** [defold/defold#5258] opened 2020-10-05 01:10 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-09-22T09:43:52.235096</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>79f8292650bce98503a70bcf901c221d04d6d26d</td></tr>
<tr><td>Defold engine sha</td><td>fe2b689302e79b7cf8c0bc7d934f23587b268c8a</td></tr>
<tr><td>Defold version</td><td>1.2.173</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"5c28b2bc29244db784e80065af55a501"'>5c28b2bc29244db784e80065af55a501</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) UHD Graphics 620 (KBL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-48-generic</td></tr>
<table>

**Comment by britzl** [comment] 2020-10-05 09:25
```
class java.lang.ClassCastException
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
```

@cjuniordev  could you pleas try: https://defold.com/manuals/linux/#q-why-does-the-defold-editor-crash-when-i-try-to-create-a-new-project-or-open-an-existing-one

**Comment by britzl** [comment] 2020-10-05 11:34
Duplicate of https://github.com/defold/defold/issues/4851

**Closed by britzl** 2020-10-05 11:34 UTC
Labels: editor
