### ISSUE TITLE
Cycle detected in build

### ISSUE THREAD

**Issue by greay** [defold/defold#5750] opened 2021-04-16 20:21 UTC
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))

<hr/>
<table>
<tr><td>Build time</td><td>2021-04-13T06:40:52.350087</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b004f16e507cef52b6940c6970cbefc0d68722f0</td></tr>
<tr><td>Defold engine sha</td><td>ff5b94e432eb58dabdb8e367bed9acc5e99e129b</td></tr>
<tr><td>Defold version</td><td>1.2.181</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"0236e9dd2dcd4a13a5e504e043c6e272"'>0236e9dd2dcd4a13a5e504e043c6e272</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 575X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-4.2.15</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.16</td></tr>
<table>

**Comment by britzl** [comment] 2021-04-17 07:15
@greay this is a duplicate of https://github.com/defold/defold/issues/4893

Please check the issue for more info and a solution!

**Closed by britzl** 2021-04-17 07:15 UTC
