### ISSUE TITLE
Debugger fails to launch with a SocketTimeoutException error

### ISSUE THREAD

**Issue by lurkshark** [defold/defold#5471] opened 2021-01-16 08:21 UTC
### Expected behaviour

Defold starts the game and attaches the debugger.

### Actual behaviour

The `dmengine.exe` goes unresponsive and a `SocketTimeoutException` error occurs.

### Steps to reproduce

1. Open the `Linker sample game` project.
2. Go to Debug > Start / Attach.
3. A blank `dmengine.exe` window flashes before the "An Error Occurred"  dialog pops-up showing `java.net.SocketTimeoutException: connect timed out`. The `dmengine.exe` is unresponsive.
4. Repeated attempts consistently reproduces the error; regular builds however do seem to work just fine.

**Notes:** Firewall is opened for `dmengine.exe` as well as the Defold OpenJDK binary. I tried launching Defold as Administrator and the same thing happens. I got it to work once, one of the first times I ran it, but every subsequent attempt has failed. I ensured there were no lingering instances running (rebooted my computer and double-checked Task Manager). I'm going to try downgrading to see if it helps.

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-15T17:32:44.177461</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>15c3fb12f092d565bb8d549a961e91ff78f97528</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ac11c29f35d946deab86c4e1a6ce68e6"'>ac11c29f35d946deab86c4e1a6ce68e6</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 27.20.100.8935</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by lurkshark** [comment] 2021-01-17 00:57
Potentially the same issue as https://forum.defold.com/t/java-error-socket-timeout-exception/67274

**Comment by lurkshark** [comment] 2021-01-17 01:04
I didn't downgrade, but I did nuke my installation and reinstall a fresh current version (and updated the editor). I saw the same behavior where it worked the first time but consistently failed on follow-ups. The logger in the editor gave me the following output and I noted where the output ends on the failed follow-up attempts.

```
INFO:ENGINE: Defold Engine 1.2.178 (af6a29c)
INFO:ENGINE: Loading data from: build/default
INFO:ENGINE: Initialised sound device 'default'
DEBUG:SCRIPT: Listening for debugger on 0.0.0.0
-- The lines below are not present on the failed attempts
DEBUG:SCRIPT: Debugger connected from 127.0.0.1
WARNING:DLIB: Profiler Engine.Init took 2.049 seconds
INFO:DLIB: SSDP: Started on address 172.18.224.1
INFO:DLIB: SSDP: Started on address 172.29.128.1
INFO:DLIB: SSDP: Started on address 192.168.0.5
INFO:DLIB: SSDP: Done on address 172.18.224.1
INFO:DLIB: SSDP: Done on address 172.29.128.1
INFO:DLIB: SSDP: Done on address 192.168.0.5
```

**Comment by lurkshark** [comment] 2021-01-17 01:37
I don't see any recent changes to `mobdebug` related components in the codebase, but it's very possible I'm not looking at the right things.

**Comment by britzl** [comment] 2021-01-17 11:42
We have done changes to our socket implementation recently and this could perhaps result in the problem you are having.

@JCash any ideas?

**Comment by lurkshark** [comment] 2021-01-17 19:22
I found another weird data point today. I created a new project with the "Mobile game" template and launched the `F5` debugger. It consistently worked perfectly. I thought "oh weird maybe the 'Linker sample game' template will work fine now too" so I went and tried it. Still got the same worked-once-but-then-consistently-failed behavior described earlier.

**Comment by lurkshark** [comment] 2021-01-27 02:19
After trying to repro with the newest update, the `Linker sample game` that was problematic before now gives a
```
This project cannot be used with the debugger
It is configured to disable shared script state.
````
I'm assuming the shared script state was what was messing things up before, and the message above is helpful for tracking that down. I'm closing this issue; thanks for all the work you do!

**Comment by britzl** [comment] 2021-01-27 15:01
Hmm, strange, are you sure you didn't disable shared script state yourself? It's enabled in the project on GitHub:

https://github.com/defold/sample-linker/blob/master/game.project#L20

**Comment by lurkshark** [comment] 2021-01-27 17:27
@britzl You're right, I just opened up the project to check its configuration and shared script state is enabled. Then I tried launching the debugger and got the socket issues again. I don't have any good guesses as to what caused it to think the shared script state was the issue or why it suddenly stopped thinking that.

**Comment by JCash** [comment] 2021-02-19 09:06
I tried the linker example but couldn't reproduce the issue I'm afraid.

**Comment by JCash** [comment] 2021-02-19 09:31
The actual callstack:

```
java.net.PlainSocketImpl.waitForConnect.class java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.waitForConnect(PlainSocketImpl.java)
    at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:591)
    at editor.debugging.mobdebug$try_connect_BANG_.invokeStatic(mobdebug.clj:328)
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:333)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
    ```

**Comment by JCash** [comment] 2021-02-19 09:44
It might be that we don't handle the timeout exception correctly in our retry-loop.
Adding the check for that type of exception is easy, but it's not a guarantee that it will work anyways.

Does it work if you try again after a longer while? (e.g 5, 10, 30 minutes later)
(I recall issues with port reuse and cooldown from another project)

**Comment by JCash** [comment] 2021-02-19 13:17
@lurkshark We've added a fix for the exception causing trouble, and it's live in the next editor build (~10minutes)
Please try it out and let us know if it solves your issue of not being able to connect.

**Comment by britzl** [comment] 2021-02-22 08:48
I'm closing this issue. @lurkshark please reopen if the fix didn't solve your problem.

**Closed by britzl** 2021-02-22 08:48 UTC
Labels: debugger, editor, engine

**Comment by lurkshark** [comment] 2021-02-26 05:28
Yep it's all looking good now, thanks!

**Comment by britzl** [comment] 2021-02-26 05:49
Great! Thanks for letting us know!
