### ISSUE TITLE
issue while opening mian.collection

### ISSUE THREAD

**Issue by LovelyA72** [defold/defold#6240] opened 2021-12-06 05:35 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-11-18T07:28:04.826271</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>229b4dbc78495615871b3a7679e79d75d018c27a</td></tr>
<tr><td>Defold engine sha</td><td>8894457f85514465165401c664f5ba79a7730804</td></tr>
<tr><td>Defold version</td><td>1.2.189</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3bda78c0c2fc473aaf3042cf85424c89"'>3bda78c0c2fc473aaf3042cf85424c89</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) Xe Graphics (TGL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 21.0.3</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.11.0-41-generic</td></tr>
<table>

**Comment by britzl** [comment] 2021-12-06 09:12
```
editor.gl$gl_clear.invokeStatic.class java.lang.ClassCastException: class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2 (jogamp.opengl.es1.GLES1Impl and com.jogamp.opengl.GL2ES2 are in unnamed module of loader 'app')
    at editor.gl$gl_clear.invokeStatic(gl.clj:192)
    at editor.scene$render_BANG_.invokeStatic(scene.clj:273)
    at editor.scene$update_image_view_BANG_$fn.invoke(scene.clj:1158)
    at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:1155)
    at editor.scene$update_image_view_BANG_.invoke(scene.clj:1127)
    at editor.scene$refresh_scene_view_BANG_.invokeStatic(scene.clj:842)
    at editor.app_view$refresh_scene_views_BANG_$fn.invoke(app_view.clj:1370)
    at editor.app_view$refresh_scene_views_BANG_.invokeStatic(app_view.clj:137
```

@LovelyA72 please try: https://defold.com/manuals/linux/#q-the-defold-editor-crashes-when-opening-a-collection-or-game-object-and-the-crash-refers-to-comjogampopengl

**Comment by britzl** [comment] 2022-05-17 06:15
Duplicate of https://github.com/defold/defold/issues/6050

**Closed by britzl** 2022-05-17 06:15 UTC
Labels: more info, editor, linux
