### ISSUE TITLE
bob should check that it can get dependencies before it starts build process

### ISSUE THREAD

**Issue by subsoap** [defold/defold#5179] opened 2020-09-08 03:36 UTC
**Is your feature request related to a problem? Please describe (REQUIRED):**
Sometimes a firewall blocks bob when it's updated and it's annoying that it only attempts to connect to the net after texture compression.

**Describe the solution you'd like (REQUIRED):**
Let bob attempt to connect earlier so it can be cleared sooner. That is if it has external dependencies it knows it is going to need to get / it knows it's going to need to build native extensions externally.

**Describe alternatives you've considered (REQUIRED):**
I should probably whitelist the folder bob is in.

**Comment by JCash** [comment] 2020-09-08 08:42
A workaround is perhaps to run the "resolve" command before building, since that should need it to access the net in order to determine if the libraries have been updated?

**Comment by subsoap** [comment] 2020-09-08 08:55
Do you mean run resolve on its own first?

The first step we do is

```
build() {
	platform=$1
	shift 1
	rm -rf build
	bob --archive clean resolve build --build-report-html "build-report-${platform}.html" --texture-compression true --variant "release"  --platform "${platform}" -e a@a.com -u fake_token --with-symbols
}
```

**Comment by britzl** [comment] 2020-09-08 09:24
Yeah, resolving should happen first anyway since you can't build unless you've resolved dependencies. But you're saying that something takes a long time before the resolve step? Can you determine from the log output what is taking so long? (use --verbose)

**Comment by subsoap** [comment] 2020-09-08 18:39
I think the problem is that there are multiple unique tools connected to unique addresses that multiple firewall steps (deps happens first and then NEs happen after textures?) happen at one build/bundle process.

**Comment by britzl** [comment] 2020-09-08 20:33
Ok, so the problem is that texture compression is done first and it takes a long time and then we build the engine via build.defold.com? And the connection to build.defold.com gets blocked by Windows firewall or something?

And it gets blocked because you updated bob.jar which isn't whitelisted by the firewall?

While I do understand that this is annoying I also feel that it is something that could be avoided, perhaps by smarter or better firewall configurations. And bob.jar doesn't get updated all the time right so it's not an issue that you run into on a daily basis?

**Comment by subsoap** [comment] 2020-09-09 01:53
Yes, it's not an urgent problem at all just documenting an annoyance. Most people probably don't use as restrictive firewalls anyway.

**Comment by britzl** [comment] 2020-09-10 05:52
I'm going to close this one. It is highly unlikely that we will have time to fix this.

**Closed by britzl** 2020-09-10 05:52 UTC
Labels: bob, feature request
