### ISSUE TITLE
Font bug: “Cache Width” and “Cache Height” are not set automatically when set to 0.

### ISSUE THREAD

**Issue by ufgo** [defold/defold#9631] opened 2024-10-22 18:59 UTC
**Steps to reproduce the behavior:**
1. Add the SFProText-Regular font, with Cache Width, Cache Height set to 0 and ‘All Chars’ ticked. 
2. Add the font to the GUI and create a text node. 
3. In the text node, set the text from the ‘Characters’ field in the font settings. 
4. Run the project and you will see an error that the cache size is insufficient.

`WARNING:RENDER: Entire font glyph cache (1024 x 2048) is filled in a single frame 806 (‘v’ 118). Consider increasing the cache for /assets/fonts/SFPro_regular.fontc
`

**Defold version (REQUIRED):**
  - Version 1.9.4

**Platforms (REQUIRED):**
 - any

**Min repro here:**
[font_bug.zip](https://github.com/user-attachments/files/17480938/font_bug.zip)

**Comment by JCash** [comment] 2024-10-23 08:15
It behaves the same way in 1.9.3 and it's not a regression.
I believe it's a misconception of how the automatic cache size is calculated.
It's basically just a "good guess", as we don't want to create a bigger texture than needed.
So, if it's insufficient, it's perfectly valid to set the size manually.

Closing as "working as intended" for now.

**Closed by JCash** 2024-10-23 08:15 UTC
Labels: bug

**Comment by AGulev** [comment] 2024-10-23 08:19
+1 to @JCash 
I removed symbol by symbol until it worked in 1.9.3. Then run the same project in a.9.4 - it works as well. I don't see an issue here, probably after the engine update you started to use more different glyphs at the same time in one of your levels. Looks like coincidence - not regression.


My example that I made work in 1.9.3 (and it works in 1.9.4 as well)
[font_bug.zip](https://github.com/user-attachments/files/17487489/font_bug.zip)

Let us know if you'll have repro that works fine in 1.9.3 and doesn't work in 1.9.4

**Comment by ufgo** [comment] 2024-10-23 16:53
It does on 1.9.3 works fine, and on 1.9.4 this is easily reproducible (in my game project).

**Comment by AGulev** [comment] 2024-10-23 18:04
We can't.
We need a way to debug it to understand what the problem is.

**Comment by britzl** [comment] 2024-10-24 08:30
> it is easily reproducible in my game project

If you are able, you can invite one of us in the Defold team as temporary collaborators, so that we can take a look.

**Comment by 8bitskull** [comment] 2024-11-11 15:34
I'm not 100% sure this is exactly the same issue, however I have managed to create a small repro.

[glyph_repro.zip](https://github.com/user-attachments/files/17704437/glyph_repro.zip)

If you build the project in editor, it should display fine. However, if you create a bundle you will notice flickering due to some sort of failure in the cache size. My machine is running Microsoft Windows 10 Pro.
