### ISSUE TITLE
Protobuf optional fields always saved (collectionproxy - exclude) (DEFEDIT-791)

### ISSUE THREAD

**Issue by britzl** [defold/defold#4091] opened 2019-05-27 05:40 UTC
Optional fields in protobuf files are always saved. For instance exclude in collectionproxy is always saved as false (default).

**Comment by AGulev** [comment] 2023-05-03 15:38
duplicate of https://github.com/defold/defold/issues/6410

**Closed by AGulev** 2023-05-03 15:38 UTC
Labels: bug, editor
