### ISSUE TITLE
Chinese localization of the editor interface

### ISSUE THREAD

**Issue by txj-mssl** [defold/defold#4915] opened 2020-06-15 02:21 UTC
I'm interested in defold.
My English is not good, but I want to try to localize the editor interface in Chinese. What should I do? Is there a simple way to do it?
Can my get some help?

**Comment by txj-mssl** [comment] 2020-06-15 02:22
Translate the editor interface into Chinese

**Comment by britzl** [comment] 2020-06-16 05:14
The editor is not set up for easy localization yet I'm afraid.

**Comment by txj-mssl** [comment] 2020-06-17 00:25
Godot 4.0 has Po files that can be easily translated into Chinese

**Comment by dougen** [comment] 2020-12-09 08:32
Most of the manuals have been translated into Chinese, and I think translate the API into Chinese is more useful than the editor interface. 
我觉得编辑器界面的中文化远远没有中文文档那么重要。

**Comment by britzl** [comment] 2020-12-11 17:39
We would like to offer translations of both the editor and the API documentation. I'll spend some time investigating how to make this happen.

**Comment by CocosGames** [comment] 2021-02-07 09:27
The Editor doesn't speak much. The manuals are on me. The API... I'll think about it.

**Comment by CocosGames** [comment] 2021-02-14 08:37
![image](https://user-images.githubusercontent.com/42052366/107872124-db8c4780-6ee2-11eb-925a-08a3279b66fd.png)

How about this.

**Comment by txj-mssl** [comment] 2021-06-02 04:58
Engine developer, what's the latest news on this issue? You've been studying for a long time.

**Comment by txj-mssl** [comment] 2021-06-02 04:59
@britzl

**Comment by txj-mssl** [comment] 2021-06-02 05:02
I think you forgot about it.

**Comment by CocosGames** [comment] 2021-06-02 06:06
> I think you forgot about it.

API's here: https://github.com/CocosGames/DefoldAPI_zh_CN
It's half-finished, I don't have time to finish it, fork it and continue if you like.

**Comment by subsoap** [comment] 2021-06-03 03:45
Defold editor still has a lot of localization strings baked in the source. These all need to be externalized to a single file. Anyone could work on this to make it happen. Then translations of the editor can relatively easily be contributed.

**Comment by britzl** [comment] 2024-01-18 19:39
Duplicate of https://github.com/defold/defold/issues/5453

**Closed by britzl** 2024-01-18 19:39 UTC
Labels: feature request, editor
