### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by Meranolean** [defold/defold#6484] opened 2022-03-21 16:38 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2021-11-18T07:28:25.014481</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>229b4dbc78495615871b3a7679e79d75d018c27a</td></tr>
<tr><td>Defold engine sha</td><td>8894457f85514465165401c664f5ba79a7730804</td></tr>
<tr><td>Defold version</td><td>1.2.189</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ce4c54c9f2a645e8ad26553a8e44c872"'>ce4c54c9f2a645e8ad26553a8e44c872</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce RTX 3060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 511.79</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment] 2022-03-22 07:30
```
internal.node$mark_in_production.invokeStatic.class java.lang.AssertionError: Assert failed: Cycle detected on node type editor.code.script/ScriptNode and output :build-targets
(not (contains? (:in-production evaluation-context) [node-id label]))
    at internal.node$mark_in_production.invokeStatic(node.clj:1320)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:528)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:528)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:283)
    at internal.node$pull_input_values$fn.invoke(node.clj:1160)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1161)
    at editor.code.script$ScriptNode$behavior$build_targets$fn.invoke(script.clj:528)
    at internal.node$trace_expr$fn.invoke(node.clj:35)
    at internal.node$trace_expr.invokeStatic(node.clj:35)
    at editor.code.script$ScriptNode$behavior$build_targets.invokeStatic(script.clj:528)
    at editor.code.script$ScriptNode$behavior$build_targets.invoke(script.clj:528)
```

**Comment by britzl** [comment] 2022-03-22 07:31
I believe this is a duplicate of https://github.com/defold/defold/issues/4893

@Meranolean please take a look at the linked issue for a solution/workaround.

**Closed by britzl** 2022-03-22 07:31 UTC
Labels: bug, editor
