### ISSUE TITLE
Can't attach to ios

### ISSUE THREAD

**Issue by szilardhuber** [defold/defold#4879] opened 2020-06-05 11:36 UTC
### Actual behaviour

I created a bundle for ios (tried with both phone and simulator). I upload the app with ios-deploy or ios-sim and the bundle works just fine. But neither hot reload nor attach works on that. When I try to attach I get this error message.

Is it possible to see the output of defold print commands any other way?
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-03T11:37:32.655314</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>959824efadaebc80654f416ca47105ab5642a0f3</td></tr>
<tr><td>Defold engine sha</td><td>4ebe7a1d548eae2398717ed46f9d7d1b103d5503</td></tr>
<tr><td>Defold version</td><td>1.2.169</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d7e9bc6217a94103824555a00fc22411"'>d7e9bc6217a94103824555a00fc22411</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 655</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.5.22</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.4</td></tr>
<table>

**Comment by britzl** [comment] 2020-06-05 12:27
Did you create a Debug bundle? The debugger, connection to the editor and print output will not work in Release builds.

**Comment by szilardhuber** [comment] 2020-06-05 12:33
I think I did. I guess it is only defined by value in the "variant" combobox when creating the bundle (Debug/Release). I also checked in the checkbox for Generating debug symbols.

**Comment by britzl** [comment] 2020-06-05 13:48
Ok, so it's a debug build. That's good. 

Have you read the guide on how to connect using USB: https://defold.com/manuals/dev-app/#connecting-to-an-ios-device-using-usb-on-osx

**Comment by szilardhuber** [comment] 2020-06-05 14:21
I have and I tried that as well, however my main problem right now is the simulator. But actually it behaves the same with both phone and simulator. When I set the right target and build the project, the app quits on the "device" so there seems to be some communication happening but it does not start again and when I click attach (with the app running on the device) I get the error message.

**Comment by britzl** [comment] 2020-06-05 14:42
> however my main problem right now is the simulator

I haven't tried this much myself. Not sure how well it works to be honest.

You mentioned that you wanted to see print output. You can see this using the Console app for instance: https://defold.com/manuals/debugging-game-and-system-logs/#ios

**Comment by szilardhuber** [comment] 2020-06-06 07:50
Great, thanks. Even though it does not solve the original problem but now I can go on with my project. (BTW: I think that write log trigger should be turned on by default as that is a lifesaver.)

**Comment by britzl** [comment] 2020-06-06 11:17
Another question. When connected, does the device show up in the Project->Target menu?

**Comment by szilardhuber** [comment] 2020-06-08 07:54
It does and when I see the communication in wireshark it seems that the simulator/game is sending RST packets to the debugger which (according to a quick google) may mean that the app is crashing. I tried debugging some sample applications though and had the same effect.

**Comment by britzl** [comment] 2022-12-02 19:54
Unable to reproduce. Closing.

**Closed by britzl** 2022-12-02 19:54 UTC
Labels: bug, more info, editor, ios
