### ISSUE TITLE
HTML5 Build java.io.IOException: insufficient bytes written to stream

### ISSUE THREAD

**Issue by SpencerWF** [defold/defold#5491] opened 2021-01-20 20:47 UTC
### Expected behaviour
HTML5 build for testing

### Actual behaviour
java.io.IOException: insufficient bytes written to stream

### Steps to reproduce
Repeatedly run HTML5 Build.

<hr/>

<table>
<tr><td>Build time</td><td>2021-01-20T12:19:39.571004</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9dd4cc8e89bf83dd22f2528153573b5cb3b45c11</td></tr>
<tr><td>Defold engine sha</td><td>af6a29c2a1e2545e2d033790089c606ac9f0bb7a</td></tr>
<tr><td>Defold version</td><td>1.2.178</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d8571b760a344a359252a40543bc39aa"'>d8571b760a344a359252a40543bc39aa</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 450.102.04</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-62-generic</td></tr>
<table>

**Comment by SpencerWF** [comment] 2021-01-21 13:24
It's happened a few times, I was debugging during this time, so might just be related to something I was testing, but I'm not able to guarantee I could reproduce it.  It happened 3 times yesterday.

**Comment by britzl** [comment] 2021-06-20 13:10
Is this still happening @SpencerWF ?

**Comment by britzl** [comment] 2022-12-02 20:04
Unable to reproduce. Closing.

**Closed by britzl** 2022-12-02 20:04 UTC
Labels: bug, more info, editor
