### ISSUE TITLE
Problem in Defold in Ubuntu 20.04

### ISSUE THREAD

**Issue by jayanthbagare** [defold/defold#4954] opened 2020-06-23 16:29 UTC
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-06-22T13:03:26.602841</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c907611b80aaec1c2bd1f4490699c0be3b250f87</td></tr>
<tr><td>Defold engine sha</td><td>5791ee6d96b87e50eee5acd70abaa4026fefef28</td></tr>
<tr><td>Defold version</td><td>1.2.170</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f3cced0979d84c2daca0b0bec9ca2ec9"'>f3cced0979d84c2daca0b0bec9ca2ec9</a></td></tr>
<tr><td>GPU</td><td>Mesa Intel(R) HD Graphics 530 (SKL GT2)</td></tr>
<tr><td>GPU Driver</td><td>OpenGL ES-CM 1.1 Mesa 20.0.4</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.4.0-37-generic</td></tr>
<table>

**Comment by britzl** [comment] 2020-06-23 22:20
class jogamp.opengl.es1.GLES1Impl cannot be cast to class com.jogamp.opengl.GL2ES2

**Comment by britzl** [comment] 2020-06-23 22:21
Duplicate of #4851

**Closed by britzl** 2020-06-23 22:21 UTC
